# Gera descClan_en.lua e descClan_pt.lua na raiz do plugin (SPEC T848, I21, I102e, V210, V24).
#
#   research/clan_body_en.tsv   nome<TAB>livro<TAB>pagina<TAB>corpo   (o lado que tem a FONTE)
#   research/clan_body_pt.tsv   nome<TAB>corpo                       (so a traducao)
#
# Livro e pagina moram SO no lado _en de proposito: sao o mesmo fato para as duas metades, e a
# copia e que faz as duas divergirem (B70, V67). O rotulo e a unica coisa que traduz: p. -> pag.
$ErrorActionPreference = 'Stop'
$root   = Split-Path $PSScriptRoot -Parent
$plugin = Join-Path $root 'Plugins\Sheets\World of Darkness 20th Anniversary Edition'

# O titulo como os 8 modulos que ja existem em disco o escrevem - a grafia ja tem dono, nao se
# reinventa aqui (research/README.md). I142h: U+2019 e DELIMITADOR DE STRING no PS 5.1, entao o
# titulo do bh entra por [char] ou a linha se parte no apostrofo curvo.
$BOOK_TITLE = @{
    core   = 'Vampire: The Masquerade 20th Anniversary Edition'
    lob    = 'Lore of the Bloodlines'
    anarch = 'Anarchs Unbound'
    bh     = ('The Black Hand: A Guide to the Tal' + [char]0x2019 + 'Mahe' + [char]0x2019 + 'Ra')
}

function ReadRows([string]$path) {
    if (-not (Test-Path -LiteralPath $path)) { throw "nao achei $path" }
    $txt = [Text.Encoding]::UTF8.GetString([IO.File]::ReadAllBytes($path))
    if ($txt.Length -gt 0 -and $txt[0] -eq [char]0xFEFF) { $txt = $txt.Substring(1) }
    $out = New-Object System.Collections.ArrayList
    foreach ($l in ($txt -split "`r?`n")) {
        if ($l -eq '' -or $l.StartsWith('#')) { continue }
        [void]$out.Add(($l -split "`t"))
    }
    , $out.ToArray()
}

$en = ReadRows (Join-Path $PSScriptRoot 'clan_body_en.tsv')
$pt = @{}
foreach ($r in (ReadRows (Join-Path $PSScriptRoot 'clan_body_pt.tsv'))) {
    if ($r.Count -ne 2) { throw "linha pt com $($r.Count) campos: $($r[0])" }
    $pt[$r[0]] = $r[1]
}

# A lista do picker e a regua: chave que nao esta nela e texto morto, e nome dela sem chave e o
# `?` que abre em branco. V408 mede a mesma coisa depois, no gate.
$lfm  = [Text.Encoding]::UTF8.GetString([IO.File]::ReadAllBytes((Join-Path $plugin 'WoD20th\WoD20th.lfm')))
$m    = [regex]::Match($lfm, '(?s)\["clan"\]\s*=\s*\{(.*?)\n\s*\},')
$clan = @([regex]::Matches($m.Groups[1].Value, '"([^"]*)"') | ForEach-Object { $_.Groups[1].Value } | Where-Object { $_ -ne '' })
if ($clan.Count -eq 0) { throw "PICKER_LIST[clan] nao foi lido do .lfm" }

# Cada `\n` do .tsv e uma quebra de PARAGRAFO no .lua - uma linha em branco entre os blocos, do
# jeito que os 8 modulos que ja existem sao lidos na pane (MEDIDO em descBackground_en.lua).
function Entry([string]$name, [string]$title, [string]$page, [string]$body, [string]$lang) {
    $label = if ($lang -eq 'pt') { 'pág.' } else { 'p.' }
    $prose = ($body -replace '\\n', "`n`n")
    if ($prose -match '\]==\]') { throw "corpo de '$name' carrega ]==] e fecharia a string Lua" }
    $head  = "$title, $label $page`n`n`n$name`n`n`n"
    @(
        "`t`t`t`t[""$name""] = {"
        "`t`t`t`t`t$lang = [==[$head$prose]==],"
        "`t`t`t`t},"
    )
}

$note = @(
    '-- Clan/bloodline descriptions, the [LANG] half (SPEC I21, I102e, V210, V24 / T848).'
    '--'
    '-- One entry per item of PICKER_LIST["clan"], keyed by the value the sheet SAVES, byte for'
    '-- byte (SPEC V24): "Gargoyles (Scout)", not "Scout Gargoyles" - the book spells four of them'
    '-- differently and the picker wins, because the picker is what gets written to the NDB. Both'
    '-- halves carry the SAME 61 keys - a name in one and not the other reddens V210 in both'
    '-- directions.'
    '--'
    '-- The button that opens this module names the list clanFamily, not clan (WoD20.11.lfm:396),'
    '-- so it offers 23 revenant FAMILIES this module does not hold. That gap is DECLARED on the'
    '-- V408 debt roster against T850, the open task that owes the family text - not swept under.'
    '--'
    '-- Three blocks separated by two blank lines (SPEC I21): source, name, body. The book title'
    '-- does not translate and neither does the name in block 2 - it is the key; only p./pag. does'
    '-- (SPEC I100e). The page is the PRINTED page, measured off the page footer and not off the'
    '-- PDF index - the two differ by one and the first extraction shipped the wrong one.'
    '--'
    '-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24).'
    '-- GENERATED by research/gen_clan_desc.ps1 from the two .tsv in research/. Do not hand-edit:'
    '-- fix the .tsv and run it again.'
    ''
    'return {'
)

foreach ($lang in @('en', 'pt')) {
    $lines = @($note | ForEach-Object { $_ -replace '\[LANG\]', $lang })
    $lines += "`t`t`t`t-- >>> CLAN_DESC_BEGIN (generated - SPEC T848)"
    $seen = 0
    foreach ($r in $en) {
        if ($r.Count -ne 4) { throw "linha en com $($r.Count) campos: $($r[0])" }
        $name = $r[0]
        if (-not $BOOK_TITLE.ContainsKey($r[1])) { throw "livro '$($r[1])' de '$name' nao tem titulo aqui" }
        if (-not $pt.ContainsKey($name))         { throw "'$name' esta no _en e nao no _pt" }
        if ($clan -notcontains $name)            { throw "'$name' nao esta em PICKER_LIST[clan]" }
        $body  = if ($lang -eq 'en') { $r[3] } else { $pt[$name] }
        $lines += Entry $name $BOOK_TITLE[$r[1]] $r[2] $body $lang
        $seen++
    }
    if ($seen -ne $clan.Count) { throw "gerou $seen entradas e o picker oferece $($clan.Count)" }
    $lines += "`t`t`t`t-- <<< CLAN_DESC_END"
    $lines += '};'
    # LF, e NAO o CRLF do resto do repo: V345 mede que os modulos de descricao sao LF de ponta a
    # ponta, porque o corpo ja chega em LF do .tsv e um arquivo com as duas quebras faz o proprio
    # diff mentir sobre o que mudou (SPEC B87). Medido: o gerador nasceu em CRLF e V345 pegou.
    $enc = New-Object Text.UTF8Encoding($false)
    $path = Join-Path $plugin "descClan_$lang.lua"
    [IO.File]::WriteAllBytes($path, $enc.GetBytes((($lines -join "`n") + "`n")))
    "$([IO.Path]::GetFileName($path)): $seen entradas, $((Get-Item $path).Length) bytes"
}

foreach ($k in $pt.Keys) { if (-not ($en | Where-Object { $_[0] -eq $k })) { throw "'$k' esta no _pt e nao no _en" } }
"picker: $($clan.Count) nomes . en: $($en.Count) . pt: $($pt.Count)"
