# gen_bg_desc.ps1 - monta descBackground_en.lua e descBackground_pt.lua (SPEC T765, I102e, I21).
#
# Le tres tabelas e nao decide nada por conta propria:
#   research/bg_essence.tsv, bloco BG_PICK  -> <item do picker>\t<livro>\t<pagina impressa>
#   research/bg_body_en.tsv                 -> <item>\t<corpo EN, \n = quebra de paragrafo>
#   research/bg_body_pt.tsv                 -> idem, a metade [pt] (SPEC V9: traducao do EN)
#
# ASCII puro de proposito (SPEC B84): o PowerShell 5.1 le .ps1 sem BOM como ANSI, e um literal
# acentuado chegaria mojibake DENTRO DO TEXTO QUE O JOGADOR LE, sem erro nenhum. O unico
# acentuado que este script precisa e o `pag.` do bloco 1, montado com [char]0xE1.
param(
    [string]$Research = (Split-Path -Parent $MyInvocation.MyCommand.Path),
    [string]$OutDir   = (Join-Path (Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)) 'Plugins\Sheets\World of Darkness 20th Anniversary Edition')
)
$ErrorActionPreference = 'Stop'
$U8 = New-Object Text.UTF8Encoding($false)
$PAG = 'p' + [char]0xE1 + 'g.'

# Titulo por extenso, a mesma grafia do research/README.md e dos 10 modulos que ja existem.
# O titulo NAO traduz; so o rotulo p./pag. muda de idioma (SPEC I100e, I21).
$TITLE = @{
    core = 'Vampire: The Masquerade 20th Anniversary Edition'
    hh   = 'The Hunters Hunted II'
    m20  = 'Mage: The Ascension 20th Anniversary Edition'
    w20  = 'Werewolf: The Apocalypse 20th Anniversary Edition'
}

function Read-Bodies([string]$path) {
    $h = @{}
    foreach ($l in [IO.File]::ReadAllLines($path, $U8)) {
        if ($l.StartsWith('#') -or $l.Trim() -eq '') { continue }
        $i = $l.IndexOf("`t"); if ($i -lt 1) { continue }
        $h[$l.Substring(0, $i)] = $l.Substring($i + 1)
    }
    return $h
}

# BG_PICK: 1 linha por item do picker, 0 ambiguidade. Quem resolve os homonimos e
# research/resolve_bg_pick.ps1, que gera o bloco; aqui so se le.
$pick = New-Object System.Collections.Generic.List[psobject]
$inBlk = $false
foreach ($l in [IO.File]::ReadAllLines("$Research\bg_essence.tsv", $U8)) {
    if ($l -match 'BG_PICK_BEGIN') { $inBlk = $true; continue }
    if ($l -match 'BG_PICK_END')   { break }
    if (-not $inBlk) { continue }
    if ($l.StartsWith('#') -or $l.Trim() -eq '') { continue }
    $c = $l -split "`t"
    if ($c.Count -lt 3) { continue }
    $pick.Add([pscustomobject]@{ Name = $c[0].Trim(); Book = $c[1].Trim(); Page = $c[2].Trim() })
}
if ($pick.Count -eq 0) { throw 'bloco BG_PICK vazio em bg_essence.tsv' }

$bodyEn = Read-Bodies "$Research\bg_body_en.tsv"
$bodyPt = Read-Bodies "$Research\bg_body_pt.tsv"

# Bloco 1 = fonte, bloco 2 = o nome do PICKER (nao o do livro: `Artifacts` e `Requisitions`
# ficam no plural por decisao do user 2026-08-28), bloco 3 = o corpo. 2 linhas em branco
# entre eles, o que em Lua e "\n\n\n" (SPEC I21).
function Blocks($it, $lang, $txt) {
    $pg = if ($lang -eq 'pt') { $PAG } else { 'p.' }
    # LF, a forma da CASA, inclusive DENTRO do literal [==[ ]==] (SPEC V345, B87). Misturar
    # CRLF aqui nao muda 1 char de texto e faz o diff do arquivo mentir sobre a rodada.
    $b3 = ($txt -replace '\\n', "`n`n")
    return "$($TITLE[$it.Book]), $pg $($it.Page)`n`n`n$($it.Name)`n`n`n$b3"
}

$D = @(
 '-- Background descriptions, the [{0}] half (SPEC I102e, I21, V210 / T765).',
 '--',
 '-- One entry per item of PICKER_LIST["background"], keyed in ENGLISH because that is what',
 '-- the sheet saves (SPEC V24). Three blocks, exactly as the ten description modules already',
 '-- do: "<Book>, p. <n>" - blank - blank - <Name> - blank - blank - <text>. The book title',
 '-- does not translate; only p./pag. does (SPEC I100e).',
 '--',
 '-- Block 2 prints the PICKER name, not the book heading: the sheet offers `Artifacts` and',
 '-- `Requisitions` in the plural (user 2026-08-28) while The Hunters Hunted II writes both',
 '-- in the singular.',
 '--',
 '-- One module PER LANGUAGE and never both halves in one file (SPEC V210): half of every',
 '-- module was the language the session never opens, and require pulled both in to read one.',
 '-- The renderer builds the name by concatenation - require("descBackground_" .. half ..',
 '-- ".lua") and never a constant name (SPEC V210b).',
 '--',
 '-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24).',
 '-- Generated by research/gen_bg_desc.ps1 from research/bg_essence.tsv (block BG_PICK) and',
 '-- research/bg_body_en.tsv / _pt.tsv. Do not hand-edit.',
 ''
)

$miss = @()
foreach ($lang in @('en', 'pt')) {
    $src = if ($lang -eq 'en') { $bodyEn } else { $bodyPt }
    $o = New-Object System.Collections.Generic.List[string]
    foreach ($x in $D) { $o.Add(($x -f $lang)) }
    $o.Add('return {')
    $o.Add("`t`t`t`t-- >>> BACKGROUND_DESC_BEGIN (generated - SPEC T765)")
    $n = 0
    foreach ($it in $pick) {
        if (-not $src.ContainsKey($it.Name)) { $miss += "$lang : $($it.Name)"; continue }
        $o.Add(("`t`t`t`t[""{0}""] = {{" -f ($it.Name -replace '\\', '\\' -replace '"', '\"')))
        $o.Add(("`t`t`t`t`t{0} = [==[{1}]==]," -f $lang, (Blocks $it $lang $src[$it.Name])))
        $o.Add("`t`t`t`t},")
        $n++
    }
    $o.Add("`t`t`t`t-- <<< BACKGROUND_DESC_END")
    $o.Add('};')
    # LF tambem na JUNCAO das linhas, nao so dentro do literal (SPEC V345).
    [IO.File]::WriteAllText("$OutDir\descBackground_$lang.lua", (($o -join "`n") + "`n"), $U8)
    "descBackground_$lang.lua : $n de $($pick.Count) entradas"
}
if ($miss.Count) { "SEM CORPO ($($miss.Count)):"; $miss | ForEach-Object { '   ' + $_ } }
"gravado em $OutDir"
