-- Weapon and armour book data (SPEC I157d / T1004).
--
-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24, V456e). It
-- lives in a module and NOT in the <script> of a .lfm because the CDATA is copied raw
-- into constructNew_*(), so every open sheet would parse its own copy - the disease T479
-- cured for the description tables. The require lives inside mfOpen() (SPEC I157e).
--
-- The seven weapon cells and the three armour cells are DATA PER LANGUAGE, which is why
-- each entry carries an `en` and a `pt` table instead of a name the PT map translates:
-- `Dex + Melee` is two abilities the sheet already spells in Portuguese, and running it
-- through the name map would ask that map to hold every dice pool in the four books.
--
-- A cell the book leaves blank reads `-`, and the `-` is written HERE and not in the Lua
-- (SPEC V457b): the reader writes what the table hands it, so a missing cell is a missing
-- row in research/weapon.tsv and not a silent empty box on the sheet. `notes` is the one
-- that may be "" - it is prose the description pane appends, not a column of the sheet.
--
-- Generated by research/gen_combat_data.ps1 from research/weapon.tsv and
-- research/armor.tsv. Do not hand-edit.

local WEAPON_DATA = {
	[".30 Caliber Machine Gun"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "12", range = "800", rate = "5", clip = "100", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "12", range = "800", rate = "5", clip = "100", conceal = "N" },
	},
	[".50 Caliber Machine Gun"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "16", range = "1000", rate = "5", clip = "200", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "16", range = "1000", rate = "5", clip = "200", conceal = "N" },
	},
	["30 mm Cannon"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "15", range = "1200", rate = "8", clip = "100", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "15", range = "1200", rate = "8", clip = "100", conceal = "N" },
	},
	["3-Round Burst"] = {
		en = { roll = "Dex + Firearms", diff = "7", damage = "Weapon", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas de Fogo", diff = "7", damage = "Arma", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Aiming"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "Weapon", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "Arma", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Aiming (Dark Ages)"] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "Weapon", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "Arma", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Assault Rifle"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "7", range = "150", rate = "3", clip = "30+1", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "7", range = "150", rate = "3", clip = "30+1", conceal = "N" },
	},
	["Assault Rifle (Mage)"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "7", range = "150", rate = "3", clip = "42+1", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "7", range = "150", rate = "3", clip = "42+1", conceal = "N" },
	},
	["Automatic Fire"] = {
		en = { roll = "Dex + Firearms", diff = "8", damage = "Special", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas de Fogo", diff = "8", damage = "Especial", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Axe"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Axe (Mage)"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Axe (Werewolf)"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Barbed Cat"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Baseball Bat"] = {
		en = { roll = "Dex + Melee", diff = "5", damage = "Str + 2 (B)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "5", damage = "For + 2 (C)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Battle-Ax"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 4 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 4 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Bear Mace"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "4 (B)", range = "3", rate = "1", clip = "3", conceal = "P" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "4 (C)", range = "3", rate = "1", clip = "3", conceal = "B" },
	},
	["Biggs Mjollner Mk. IV"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "10", range = "100", rate = "1", clip = "10", conceal = "T" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "10", range = "100", rate = "1", clip = "10", conceal = "M" },
	},
	["Biggs X-5 Model A Protector"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "5", range = "40", rate = "4", clip = "12+1", conceal = "J" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "5", range = "40", rate = "4", clip = "12+1", conceal = "R" },
	},
	["Biggs X-5 Model R Protector"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "5", range = "40", rate = "4", clip = "12", conceal = "J" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "5", range = "40", rate = "4", clip = "12", conceal = "R" },
	},
	["Bite"] = {
		en = { roll = "Dex + Brawl", diff = "6", damage = "Str + 1 (A)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "6", damage = "For + 1 (A)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Bite (Mage)"] = {
		en = { roll = "Dex + Brawl", diff = "5", damage = "Str + 1 to + 3 (B or L)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "5", damage = "For + 1 a + 3 (C ou L)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Blinding"] = {
		en = { roll = "Dex + Subterfuge", diff = "9", damage = "Special", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Lábia", diff = "9", damage = "Especial", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Block"] = {
		en = { roll = "Dex + Brawl", diff = "6", damage = "None (R)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "6", damage = "Nenhum (R)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Body Slam"] = {
		en = { roll = "Dex + Brawl", diff = "6", damage = "Str + 2 (B or L)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "6", damage = "For + 2 (C ou L)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Bolan Mk.13 Weapons System"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "-", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "-", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Brass Knuckles"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str (L)", range = "-", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For (L)", range = "-", rate = "-", clip = "-", conceal = "B" },
	},
	["Broadsword"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Broken Bottle"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "B" },
	},
	["Bullwhip"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Castle-Graves WW-3"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "8", range = "200", rate = "3", clip = "50+1", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "8", range = "200", rate = "3", clip = "50+1", conceal = "N" },
	},
	["Chain"] = {
		en = { roll = "Dex + Melee", diff = "5", damage = "Str (B)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "5", damage = "For (C)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Chain Whip"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Chainsaw"] = {
		en = { roll = "Dex + Melee", diff = "8", damage = "Str + 7 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "8", damage = "For + 7 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Chair"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 2 (B)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 2 (C)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Claw"] = {
		en = { roll = "Dex + Brawl", diff = "6", damage = "Str + 1 (A)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "6", damage = "For + 1 (A)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Claw (Mage)"] = {
		en = { roll = "Dex + Brawl", diff = "6", damage = "Str + 1 to + 3 (L or A)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "6", damage = "For + 1 a + 3 (L ou A)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Clinch"] = {
		en = { roll = "Str + Brawl", diff = "6", damage = "Str (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "For + Briga", diff = "6", damage = "For (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Clinch (Dark Ages)"] = {
		en = { roll = "Dex + Brawl", diff = "6", damage = "Str (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "6", damage = "For (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Club"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (B)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (C)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Club (Dark Ages)"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (B)", range = "-", rate = "-", clip = "-", conceal = "C" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (C)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Counter Throw"] = {
		en = { roll = "Dex + Martial Arts", diff = "6", damage = "Special", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "6", damage = "Especial", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Crossbow"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "5", range = "20", rate = "1", clip = "1", conceal = "T" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "5", range = "20", rate = "1", clip = "1", conceal = "M" },
	},
	["Crossbow (Dark Ages)"] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "3 (L)", range = "90", rate = "-", clip = "-", conceal = "L" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "3 (L)", range = "90", rate = "-", clip = "-", conceal = "M" },
	},
	["Crossbow (Mage)"] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "5", range = "90", rate = "1", clip = "1", conceal = "T" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "5", range = "90", rate = "1", clip = "1", conceal = "M" },
	},
	["Crossbow, Commando"] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "3", range = "20", rate = "1", clip = "1", conceal = "J" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "3", range = "20", rate = "1", clip = "1", conceal = "R" },
	},
	["Crossbow, Hvy."] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "6", range = "100", rate = "1", clip = "1", conceal = "N" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "6", range = "100", rate = "1", clip = "1", conceal = "N" },
	},
	["Crowbar"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Curbstomp"] = {
		en = { roll = "Str + Brawl", diff = "6", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "For + Briga", diff = "6", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Dagger"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (L)", range = "20", rate = "-", clip = "-", conceal = "C" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (L)", range = "20", rate = "-", clip = "-", conceal = "R" },
	},
	["Death Strike"] = {
		en = { roll = "Dex + Martial Arts", diff = "5", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "5", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Deflecting Block"] = {
		en = { roll = "Dex + Martial Arts", diff = "6", damage = "Attacker's Str (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "6", damage = "For do Atacante (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Disarm"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Special", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "Especial", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Disarm (Mage)"] = {
		en = { roll = "Dex + Melee", diff = "7/8", damage = "Special", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas Brancas", diff = "7/8", damage = "Especial", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Dodge"] = {
		en = { roll = "Dex + Athletics", diff = "6", damage = "None (R)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Esportes", diff = "6", damage = "Nenhum (R)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Dragon Tail Sweep"] = {
		en = { roll = "Dex + Martial Arts", diff = "8", damage = "Opponent's Str (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "8", damage = "For do Oponente (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Elbow/Knee Strike"] = {
		en = { roll = "Dex + Martial Arts", diff = "5", damage = "Str + 1 (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "5", damage = "For + 1 (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Flamethrower"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "3 levels/turn (fire)", range = "60", rate = "1", clip = "5", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "3 níveis/turno (fogo)", range = "60", rate = "1", clip = "5", conceal = "N" },
	},
	["Flank/Rear Attack"] = {
		en = { roll = "Dex + Ability", diff = "5/4", damage = "As Attack", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Habilidade", diff = "5/4", damage = "Como o Ataque", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Flogger"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Flying Kick"] = {
		en = { roll = "Dex + Martial Arts", diff = "7", damage = "Str + 2 (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "7", damage = "For + 2 (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Full-Auto"] = {
		en = { roll = "Dex + Firearms", diff = "8", damage = "Weapon + 10 dice", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas de Fogo", diff = "8", damage = "Arma + 10 dados", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Grand Klaive"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 3 (A)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 3 (A)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Grapple"] = {
		en = { roll = "Str + Brawl", diff = "6", damage = "Str or None", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "For + Briga", diff = "6", damage = "For ou Nenhum", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Great Axe"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 6 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 6 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Great Blow"] = {
		en = { roll = "Dex + Brawl/Melee", diff = "7", damage = "Normal + 2", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga/Armas Brancas", diff = "7", damage = "Normal + 2", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Great Sword"] = {
		en = { roll = "Dex + Melee", diff = "5", damage = "Str + 6 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "5", damage = "For + 6 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Greatsword"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 4 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 4 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Hail of Arrows"] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "Weapon", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "Arma", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Halberd"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 4 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 4 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Hand Ax"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "L" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Hand Claws (large)"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "B" },
	},
	["Hand Claws (small)"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "B" },
	},
	["Hard/Soft Strike"] = {
		en = { roll = "Dex + Martial Arts", diff = "5/6", damage = "Str + 1 (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "5/6", damage = "For + 1 (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Hatchet"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Hatchet (Dark Ages)"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (L)", range = "20", rate = "-", clip = "-", conceal = "C" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (L)", range = "20", rate = "-", clip = "-", conceal = "R" },
	},
	["Haymaker"] = {
		en = { roll = "Dex + Brawl", diff = "7", damage = "Str + 2 (B) + Knockdown", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "7", damage = "For + 2 (C) + Derrubada", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Head Butt"] = {
		en = { roll = "Dex + Brawl", diff = "6", damage = "Str + 1 (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "6", damage = "For + 1 (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Heavy Crossbow"] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "4 (L)", range = "90", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "4 (L)", range = "90", rate = "-", clip = "-", conceal = "N" },
	},
	["HIT Mark Chain-Gun"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "8", range = "150", rate = "3", clip = "200", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "8", range = "150", rate = "3", clip = "200", conceal = "N" },
	},
	["Hold"] = {
		en = { roll = "Str + Brawl", diff = "6", damage = "None (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "For + Briga", diff = "6", damage = "Nenhum (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Hook Sword(s)"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Huge Spiked Club"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 4 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 4 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Hunting Bow"] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "5", range = "100", rate = "1", clip = "1", conceal = "N" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "5", range = "100", rate = "1", clip = "1", conceal = "N" },
	},
	["Impale"] = {
		en = { roll = "Dex + Archery", diff = "9", damage = "Special", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Arquearia", diff = "9", damage = "Especial", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Iron Staff"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Jab Pistol"] = {
		en = { roll = "Dex + Brawl", diff = "6", damage = "As Firearm + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "6", damage = "Como a Arma de Fogo + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Javelin"] = {
		en = { roll = "Dex + Athletics", diff = "6", damage = "Str + 2 (L)", range = "50", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Esportes", diff = "6", damage = "For + 2 (L)", range = "50", rate = "-", clip = "-", conceal = "N" },
	},
	["Joint Lock"] = {
		en = { roll = "Dex + Martial Arts", diff = "5", damage = "Grapple + Successes (L)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "5", damage = "Agarrão + Sucessos (L)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Katana"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Katar"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Kick"] = {
		en = { roll = "Dex + Brawl", diff = "7", damage = "Str + 1", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "7", damage = "For + 1", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Kick (Mage)"] = {
		en = { roll = "Dex + Brawl", diff = "7", damage = "Str + 1 (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "7", damage = "For + 1 (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Klaive"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (A)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (A)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Knife"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Knife (Dark Ages)"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str (L)", range = "15", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For (L)", range = "15", rate = "-", clip = "-", conceal = "B" },
	},
	["Knife (Mage)"] = {
		en = { roll = "Dex + Melee", diff = "4", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Armas Brancas", diff = "4", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "B" },
	},
	["Knife, Thrown"] = {
		en = { roll = "Dex + Athletics", diff = "6", damage = "Str (L)", range = "-", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Esportes", diff = "6", damage = "For (L)", range = "-", rate = "-", clip = "-", conceal = "B" },
	},
	["Kusarigama"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 3 (B)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 3 (C)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Lance (Mounted)"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Long Bow"] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "5", range = "120", rate = "1", clip = "1", conceal = "N" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "5", range = "120", rate = "1", clip = "1", conceal = "N" },
	},
	["Longbow"] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "4 (L)", range = "120", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "4 (L)", range = "120", rate = "-", clip = "-", conceal = "N" },
	},
	["Low Blow"] = {
		en = { roll = "Dex + Brawl", diff = "7", damage = "Str + Stun (B or L)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "7", damage = "For + Atordoamento (C ou L)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["M-19 Grenade Launcher"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "8", range = "600", rate = "2", clip = "1", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "8", range = "600", rate = "2", clip = "1", conceal = "N" },
	},
	["M-79 Grenade Launcher"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "6", range = "400", rate = "1", clip = "1", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "6", range = "400", rate = "1", clip = "1", conceal = "N" },
	},
	["Mace"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Mace (Dark Ages)"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "L" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Manriki-Gusari"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Martial Arts Disarm"] = {
		en = { roll = "Dex + Martial Arts", diff = "7", damage = "3", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "7", damage = "3", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Morning Star"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "L" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Multiple Shots"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "Weapon", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "Arma", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Nerve Strike"] = {
		en = { roll = "Dex + Martial Arts", diff = "7", damage = "Str + 3 (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "7", damage = "For + 3 (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Nunchaku"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 2 (B)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 2 (C)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Pacification Spray"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "5 (B)", range = "3", rate = "1", clip = "5", conceal = "P" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "5 (C)", range = "3", rate = "1", clip = "5", conceal = "B" },
	},
	["Parry"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "None (R)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "Nenhum (R)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Pick Ax"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Pistol Whip"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Pistol, Hvy."] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "5", range = "25", rate = "3", clip = "13+1", conceal = "J" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "5", range = "25", rate = "3", clip = "13+1", conceal = "R" },
	},
	["Pistol, Lt."] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "4", range = "20", rate = "4", clip = "15+1", conceal = "P" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "4", range = "20", rate = "4", clip = "15+1", conceal = "B" },
	},
	["Pitchfork"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Point Blank"] = {
		en = { roll = "Dex + Firearms", diff = "4", damage = "Weapon", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas de Fogo", diff = "4", damage = "Arma", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Polearm"] = {
		en = { roll = "Dex + Melee", diff = "7", damage = "Str + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "7", damage = "For + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Punch"] = {
		en = { roll = "Dex + Brawl", diff = "6", damage = "Str (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "6", damage = "For (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Quarterstaff"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 3 (B)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 3 (C)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Reading Opponent"] = {
		en = { roll = "Per + Trait", diff = "6", damage = "Special", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Per + Traço", diff = "6", damage = "Especial", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Revolver, Hvy."] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "6", range = "35", rate = "2", clip = "6", conceal = "J" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "6", range = "35", rate = "2", clip = "6", conceal = "R" },
	},
	["Revolver, Lt."] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "4", range = "12", rate = "3", clip = "6", conceal = "P" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "4", range = "12", rate = "3", clip = "6", conceal = "B" },
	},
	["Rifle"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "8", range = "200", rate = "1", clip = "3+1", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "8", range = "200", rate = "1", clip = "3+1", conceal = "N" },
	},
	["Rifle (Mage)"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "8", range = "200", rate = "1", clip = "5+1", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "8", range = "200", rate = "1", clip = "5+1", conceal = "N" },
	},
	["Riot Baton"] = {
		en = { roll = "Dex + Melee", diff = "5", damage = "Str + 1 (B)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "5", damage = "For + 1 (C)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Riposte"] = {
		en = { roll = "Dex + Brawl/Melee", diff = "7", damage = "Normal + 1", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga/Armas Brancas", diff = "7", damage = "Normal + 1", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Rock"] = {
		en = { roll = "Dex + Athletics", diff = "7", damage = "Str (B)", range = "40", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Esportes", diff = "7", damage = "For (C)", range = "40", rate = "-", clip = "-", conceal = "B" },
	},
	["Rocket Launcher"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "12-16", range = "500+", rate = "1", clip = "1", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "12-16", range = "500+", rate = "1", clip = "1", conceal = "N" },
	},
	["Saber"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "L" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Sai"] = {
		en = { roll = "Dex + Melee", diff = "5", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "5", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Sap"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (B)", range = "-", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (C)", range = "-", rate = "-", clip = "-", conceal = "B" },
	},
	["Sap (Mage)"] = {
		en = { roll = "Dex + Melee", diff = "4", damage = "Str + 1 (B)", range = "-", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Armas Brancas", diff = "4", damage = "For + 1 (C)", range = "-", rate = "-", clip = "-", conceal = "B" },
	},
	["Sap (Werewolf)"] = {
		en = { roll = "Dex + Melee", diff = "4", damage = "Str (B)", range = "-", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Armas Brancas", diff = "4", damage = "For (C)", range = "-", rate = "-", clip = "-", conceal = "B" },
	},
	["Semi-Automatic Pistol, Hvy."] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "5", range = "30", rate = "3", clip = "7+1", conceal = "J" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "5", range = "30", rate = "3", clip = "7+1", conceal = "R" },
	},
	["Semi-Automatic Pistol, Lt."] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "4", range = "20", rate = "4", clip = "17+1", conceal = "P" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "4", range = "20", rate = "4", clip = "17+1", conceal = "B" },
	},
	["Short Bow"] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "4", range = "60", rate = "1", clip = "1", conceal = "N" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "4", range = "60", rate = "1", clip = "1", conceal = "N" },
	},
	["Short Sword"] = {
		en = { roll = "Dex + Melee", diff = "5", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "5", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Shortbow"] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "2 (L)", range = "60", rate = "-", clip = "-", conceal = "L" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "2 (L)", range = "60", rate = "-", clip = "-", conceal = "M" },
	},
	["Shotgun"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "8", range = "20", rate = "1", clip = "5+1", conceal = "T" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "8", range = "20", rate = "1", clip = "5+1", conceal = "M" },
	},
	["Shotgun, Assault"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "8", range = "50", rate = "3", clip = "32+1", conceal = "N" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "8", range = "50", rate = "3", clip = "32+1", conceal = "N" },
	},
	["Shotgun, Sawed Off"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "8", range = "10", rate = "2", clip = "2", conceal = "J" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "8", range = "10", rate = "2", clip = "2", conceal = "R" },
	},
	["Shotgun, Semi-auto"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "8", range = "20", rate = "3", clip = "6+1", conceal = "T" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "8", range = "20", rate = "3", clip = "6+1", conceal = "M" },
	},
	["Shotgun, Semi-Automatic"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "8", range = "25", rate = "3", clip = "6+1", conceal = "T" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "8", range = "25", rate = "3", clip = "6+1", conceal = "M" },
	},
	["Shuriken"] = {
		en = { roll = "Dex + Athletics", diff = "7", damage = "3 (L)", range = "-", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Esportes", diff = "7", damage = "3 (L)", range = "-", rate = "-", clip = "-", conceal = "B" },
	},
	["Sling"] = {
		en = { roll = "Dex + Archery", diff = "6", damage = "3 (B)", range = "40", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Arquearia", diff = "6", damage = "3 (C)", range = "40", rate = "-", clip = "-", conceal = "B" },
	},
	["SMG, Large"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "4", range = "50", rate = "3", clip = "30+1", conceal = "T" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "4", range = "50", rate = "3", clip = "30+1", conceal = "M" },
	},
	["SMG, Small"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "4", range = "20", rate = "3", clip = "17+1", conceal = "J" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "4", range = "20", rate = "3", clip = "17+1", conceal = "R" },
	},
	["SMG, Small (Mage)"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "4", range = "25", rate = "3", clip = "30+1", conceal = "J" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "4", range = "25", rate = "3", clip = "30+1", conceal = "R" },
	},
	["Snake Step"] = {
		en = { roll = "Dex + Martial Arts", diff = "6/5", damage = "Dodge + 3 dice", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "6/5", damage = "Esquiva + 3 dados", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Snap Kick"] = {
		en = { roll = "Dex + Martial Arts", diff = "5", damage = "Str + 1 (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "5", damage = "For + 1 (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Spear"] = {
		en = { roll = "Dex + Athletics", diff = "6", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Esportes", diff = "6", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Spear (Dark Ages)"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (L)", range = "40", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (L)", range = "40", rate = "-", clip = "-", conceal = "N" },
	},
	["Spiked Club"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Spiked Gauntlet"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Spinning Kick"] = {
		en = { roll = "Dex + Martial Arts", diff = "6", damage = "Str + 3 (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "6", damage = "For + 3 (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Staff"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (B)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (C)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Stake"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Stake (Dark Ages)"] = {
		en = { roll = "Dex + Melee", diff = "9", damage = "Special", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas Brancas", diff = "9", damage = "Especial", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Stiletto"] = {
		en = { roll = "Dex + Melee", diff = "4", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "P" },
		pt = { roll = "Des + Armas Brancas", diff = "4", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "B" },
	},
	["Stone"] = {
		en = { roll = "Dex + Athletics", diff = "5", damage = "Str (B)", range = "-", rate = "-", clip = "-", conceal = "varies" },
		pt = { roll = "Des + Esportes", diff = "5", damage = "For (C)", range = "-", rate = "-", clip = "-", conceal = "varia" },
	},
	["Stone, Large"] = {
		en = { roll = "Dex + Athletics", diff = "5", damage = "Str + 3 (B)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Esportes", diff = "5", damage = "For + 3 (C)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Strafing"] = {
		en = { roll = "Dex + Firearms", diff = "8", damage = "Special", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas de Fogo", diff = "8", damage = "Especial", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Strike"] = {
		en = { roll = "Dex + Brawl", diff = "6", damage = "Str", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "6", damage = "For", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Suppressive Fire"] = {
		en = { roll = "Dex + Archery", diff = "4", damage = "Weapon", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Arquearia", diff = "4", damage = "Arma", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Sweep"] = {
		en = { roll = "Dex + Brawl/Melee", diff = "7", damage = "Str (K)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga/Armas Brancas", diff = "7", damage = "For (K)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Sweep (Mage)"] = {
		en = { roll = "Dex + Brawl", diff = "8", damage = "Special", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "8", damage = "Especial", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Sword"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "T" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "M" },
	},
	["Table"] = {
		en = { roll = "Dex + Melee", diff = "8", damage = "Str + 3 (B)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "8", damage = "For + 3 (C)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Tackle"] = {
		en = { roll = "Str + Brawl", diff = "7", damage = "Str + 1 (K)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "For + Briga", diff = "7", damage = "For + 1 (K)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Tackle (Mage)"] = {
		en = { roll = "Dex + Brawl", diff = "7", damage = "Str + Special (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Briga", diff = "7", damage = "For + Especial (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Taser"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "5 (B)", range = "5", rate = "1", clip = "1", conceal = "P" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "5 (C)", range = "5", rate = "1", clip = "1", conceal = "B" },
	},
	["Tear Gas"] = {
		en = { roll = "Dex + Firearms", diff = "6", damage = "3 (B)", range = "3", rate = "1", clip = "5", conceal = "P" },
		pt = { roll = "Des + Armas de Fogo", diff = "6", damage = "3 (C)", range = "3", rate = "1", clip = "5", conceal = "B" },
	},
	["Throw"] = {
		en = { roll = "Dex + Martial Arts", diff = "7/6", damage = "Str + Movement (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "7/6", damage = "For + Movimento (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Thunder Kick"] = {
		en = { roll = "Dex + Martial Arts", diff = "7", damage = "Str + 3 + Successes (B)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "7", damage = "For + 3 + Sucessos (C)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Tomahawk"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Tomahawk, Thrown"] = {
		en = { roll = "Dex + Athletics", diff = "6", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Esportes", diff = "6", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Two Weapons"] = {
		en = { roll = "Dex + Firearms", diff = "6/7", damage = "Weapon", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas de Fogo", diff = "6/7", damage = "Arma", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Vital Strike"] = {
		en = { roll = "Dex + Martial Arts", diff = "7", damage = "Str (L)", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "7", damage = "For (L)", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["War Fan"] = {
		en = { roll = "Dex + Melee", diff = "5", damage = "Str + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "5", damage = "For + 2 (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Warhammer"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 4 (B)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 4 (C)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Weapon Strike"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Weapon", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "Arma", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
	["Whip"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Whip (Werewolf)"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "J" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 1 (L)", range = "-", rate = "-", clip = "-", conceal = "R" },
	},
	["Wind and Fire Wheel"] = {
		en = { roll = "Dex + Melee", diff = "6", damage = "Str + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
		pt = { roll = "Des + Armas Brancas", diff = "6", damage = "For + 3 (L)", range = "-", rate = "-", clip = "-", conceal = "N" },
	},
	["Withering Grasp"] = {
		en = { roll = "Dex + Martial Arts", diff = "7", damage = "Str (B) + Disarm", range = "-", rate = "-", clip = "-", conceal = "-" },
		pt = { roll = "Des + Artes Marciais", diff = "7", damage = "For (C) + Desarme", range = "-", rate = "-", clip = "-", conceal = "-" },
	},
};

local ARMOR_DATA = {
	["Alanson Hardsuit"] = {
		en = { rating = "7", penalty = "-2", notes = "" },
		pt = { rating = "7", penalty = "-2", notes = "" },
	},
	["Bearskin Coat"] = {
		en = { rating = "3", penalty = "3", notes = "" },
		pt = { rating = "3", penalty = "3", notes = "" },
	},
	["Biker Jacket"] = {
		en = { rating = "1", penalty = "-1", notes = "" },
		pt = { rating = "1", penalty = "-1", notes = "" },
	},
	["Chainmail"] = {
		en = { rating = "4", penalty = "-2", notes = "" },
		pt = { rating = "4", penalty = "-2", notes = "" },
	},
	["Class Five (Full Riot Gear)"] = {
		en = { rating = "5", penalty = "3", notes = "Adds its rating to soak against bashing, lethal and aggravated damage from fangs and claws; not against fire or sunlight. The penalty comes off Dexterity-based dice pools." },
		pt = { rating = "5", penalty = "3", notes = "Soma o valor à absorção contra dano de contusão, letal e agravado de presas e garras; não contra fogo ou luz do sol. A penalidade sai das paradas baseadas em Destreza." },
	},
	["Class Five (Knight's Armor)"] = {
		en = { rating = "5", penalty = "3", notes = "" },
		pt = { rating = "5", penalty = "3", notes = "" },
	},
	["Class Four (Flak Jacket)"] = {
		en = { rating = "4", penalty = "2", notes = "Adds its rating to soak against bashing, lethal and aggravated damage from fangs and claws; not against fire or sunlight. The penalty comes off Dexterity-based dice pools." },
		pt = { rating = "4", penalty = "2", notes = "Soma o valor à absorção contra dano de contusão, letal e agravado de presas e garras; não contra fogo ou luz do sol. A penalidade sai das paradas baseadas em Destreza." },
	},
	["Class Four (Heavy Armor)"] = {
		en = { rating = "4", penalty = "2", notes = "" },
		pt = { rating = "4", penalty = "2", notes = "" },
	},
	["Class One (Heavy Clothing)"] = {
		en = { rating = "1", penalty = "-", notes = "" },
		pt = { rating = "1", penalty = "-", notes = "" },
	},
	["Class One (Reinforced Clothing)"] = {
		en = { rating = "1", penalty = "0", notes = "Adds its rating to soak against bashing, lethal and aggravated damage from fangs and claws; not against fire or sunlight. The penalty comes off Dexterity-based dice pools." },
		pt = { rating = "1", penalty = "0", notes = "Soma o valor à absorção contra dano de contusão, letal e agravado de presas e garras; não contra fogo ou luz do sol. A penalidade sai das paradas baseadas em Destreza." },
	},
	["Class Three (Composite Armor)"] = {
		en = { rating = "3", penalty = "1", notes = "" },
		pt = { rating = "3", penalty = "1", notes = "" },
	},
	["Class Three (Kevlar Vest)"] = {
		en = { rating = "3", penalty = "1", notes = "Adds its rating to soak against bashing, lethal and aggravated damage from fangs and claws; not against fire or sunlight. The penalty comes off Dexterity-based dice pools." },
		pt = { rating = "3", penalty = "1", notes = "Soma o valor à absorção contra dano de contusão, letal e agravado de presas e garras; não contra fogo ou luz do sol. A penalidade sai das paradas baseadas em Destreza." },
	},
	["Class Two (Armor T-Shirt)"] = {
		en = { rating = "2", penalty = "1", notes = "Adds its rating to soak against bashing, lethal and aggravated damage from fangs and claws; not against fire or sunlight. The penalty comes off Dexterity-based dice pools." },
		pt = { rating = "2", penalty = "1", notes = "Soma o valor à absorção contra dano de contusão, letal e agravado de presas e garras; não contra fogo ou luz do sol. A penalidade sai das paradas baseadas em Destreza." },
	},
	["Class Two (Cloth/Textile Armor)"] = {
		en = { rating = "2", penalty = "1", notes = "" },
		pt = { rating = "2", penalty = "1", notes = "" },
	},
	["Cosplay Mail"] = {
		en = { rating = "2", penalty = "-1", notes = "" },
		pt = { rating = "2", penalty = "-1", notes = "" },
	},
	["Cybernetic Armor"] = {
		en = { rating = "1-4", penalty = "0", notes = "Built into the wearer; see the Background: Enhancement." },
		pt = { rating = "1-4", penalty = "0", notes = "Embutida no portador; ver o Antecedente: Aprimoramento." },
	},
	["Enhanced Clothing"] = {
		en = { rating = "1-5", penalty = "0", notes = "Clothing woven with advanced or Enlightened materials." },
		pt = { rating = "1-5", penalty = "0", notes = "Roupa tecida com materiais avançados ou Iluminados." },
	},
	["Flak Vest"] = {
		en = { rating = "4", penalty = "-2", notes = "" },
		pt = { rating = "4", penalty = "-2", notes = "" },
	},
	["Full Plate"] = {
		en = { rating = "5", penalty = "-2", notes = "" },
		pt = { rating = "5", penalty = "-2", notes = "" },
	},
	["Kevlar Vest"] = {
		en = { rating = "3", penalty = "-1", notes = "" },
		pt = { rating = "3", penalty = "-1", notes = "" },
	},
	["Leather Duster"] = {
		en = { rating = "2", penalty = "-2", notes = "" },
		pt = { rating = "2", penalty = "-2", notes = "" },
	},
	["Metal Shield"] = {
		en = { rating = "4/+2", penalty = "-2", notes = "Shield: soak bonus / difficulty bonus against attacks." },
		pt = { rating = "4/+2", penalty = "-2", notes = "Escudo: bônus de absorção / bônus de dificuldade contra ataques." },
	},
	["Military Armor"] = {
		en = { rating = "5", penalty = "-2", notes = "" },
		pt = { rating = "5", penalty = "-2", notes = "" },
	},
	["Reinforced Clothing"] = {
		en = { rating = "1-2", penalty = "0", notes = "Clothing stiffened, padded or layered against harm." },
		pt = { rating = "1-2", penalty = "0", notes = "Roupa enrijecida, acolchoada ou em camadas contra ferimentos." },
	},
	["Reinforced Clothing (Werewolf)"] = {
		en = { rating = "1", penalty = "0", notes = "" },
		pt = { rating = "1", penalty = "0", notes = "" },
	},
	["Riot Shield"] = {
		en = { rating = "5/+2", penalty = "-1", notes = "Shield: soak bonus / difficulty bonus against attacks." },
		pt = { rating = "5/+2", penalty = "-1", notes = "Escudo: bônus de absorção / bônus de dificuldade contra ataques." },
	},
	["Riot Suit"] = {
		en = { rating = "4", penalty = "-2", notes = "" },
		pt = { rating = "4", penalty = "-2", notes = "" },
	},
	["Riot Suit (Werewolf)"] = {
		en = { rating = "5", penalty = "3", notes = "" },
		pt = { rating = "5", penalty = "3", notes = "" },
	},
	["Steel Breastplate"] = {
		en = { rating = "3", penalty = "-2", notes = "" },
		pt = { rating = "3", penalty = "-2", notes = "" },
	},
	["Tough Hide"] = {
		en = { rating = "1-3", penalty = "0", notes = "Animals, Bygones, constructs or shapechanged mages with especially thick or armored skin." },
		pt = { rating = "1-3", penalty = "0", notes = "Animais, Relíquias, constructos ou magos transformados com pele especialmente grossa ou blindada." },
	},
	["Trash Can Lid"] = {
		en = { rating = "3/+1", penalty = "0", notes = "Shield: soak bonus / difficulty bonus against attacks." },
		pt = { rating = "3/+1", penalty = "0", notes = "Escudo: bônus de absorção / bônus de dificuldade contra ataques." },
	},
	["Trashcan Lid"] = {
		en = { rating = "2", penalty = "0", notes = "No Dexterity penalty, but a difficulty 6 Dexterity + Melee roll to employ." },
		pt = { rating = "2", penalty = "0", notes = "Sem penalidade de Destreza, mas exige jogada de Destreza + Armas Brancas, dificuldade 6, para usar." },
	},
	["Wooden Shield"] = {
		en = { rating = "2/+2", penalty = "-1", notes = "Shield: soak bonus / difficulty bonus against attacks." },
		pt = { rating = "2/+2", penalty = "-1", notes = "Escudo: bônus de absorção / bônus de dificuldade contra ataques." },
	},
};

return { weapon = WEAPON_DATA, armor = ARMOR_DATA };
