-- Armor descriptions, the [en] half (SPEC I157h, I21, V210 / T1004).
--
-- One entry per item of PICKER_LIST["armor"], keyed in ENGLISH because that is what the sheet
-- saves (SPEC V24). Three blocks, exactly as the twelve description modules already do:
-- "<Book>, p. <n>" - blank - blank - <Name> - blank - blank - <text>. The book title does
-- not translate; only p./pag. does (SPEC I100e).
--
-- One module PER LANGUAGE and never both halves in one file (SPEC V210): half of every
-- module was the language the session never opens, and require pulled both in to read one.
-- The renderer builds the name by concatenation - require("desc<Kind>_" .. half .. ".lua")
-- and never a constant name (SPEC V210b).
--
-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24).
-- Generated by research/gen_combat_data.ps1 from research/weapon.tsv and
-- research/armor.tsv. Do not hand-edit.

return {
				-- >>> ARMOR_DESC_BEGIN (generated - SPEC T1004)
				["Alanson Hardsuit"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Alanson Hardsuit


Rating: 7
Penalty: -2]==],
				},
				["Bearskin Coat"] = {
					en = [==[Werewolf: The Apocalypse 20th Anniversary Edition, p. 292


Bearskin Coat


Rating: 3
Penalty: 3]==],
				},
				["Biker Jacket"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Biker Jacket


Rating: 1
Penalty: -1]==],
				},
				["Chainmail"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Chainmail


Rating: 4
Penalty: -2]==],
				},
				["Class Five (Full Riot Gear)"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 280


Class Five (Full Riot Gear)


Rating: 5
Penalty: 3

Notes: Adds its rating to soak against bashing, lethal and aggravated damage from fangs and claws; not against fire or sunlight. The penalty comes off Dexterity-based dice pools.]==],
				},
				["Class Five (Knight's Armor)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Class Five (Knight's Armor)


Rating: 5
Penalty: 3]==],
				},
				["Class Four (Flak Jacket)"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 280


Class Four (Flak Jacket)


Rating: 4
Penalty: 2

Notes: Adds its rating to soak against bashing, lethal and aggravated damage from fangs and claws; not against fire or sunlight. The penalty comes off Dexterity-based dice pools.]==],
				},
				["Class Four (Heavy Armor)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Class Four (Heavy Armor)


Rating: 4
Penalty: 2]==],
				},
				["Class One (Heavy Clothing)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Class One (Heavy Clothing)


Rating: 1
Penalty: -]==],
				},
				["Class One (Reinforced Clothing)"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 280


Class One (Reinforced Clothing)


Rating: 1
Penalty: 0

Notes: Adds its rating to soak against bashing, lethal and aggravated damage from fangs and claws; not against fire or sunlight. The penalty comes off Dexterity-based dice pools.]==],
				},
				["Class Three (Composite Armor)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Class Three (Composite Armor)


Rating: 3
Penalty: 1]==],
				},
				["Class Three (Kevlar Vest)"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 280


Class Three (Kevlar Vest)


Rating: 3
Penalty: 1

Notes: Adds its rating to soak against bashing, lethal and aggravated damage from fangs and claws; not against fire or sunlight. The penalty comes off Dexterity-based dice pools.]==],
				},
				["Class Two (Armor T-Shirt)"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 280


Class Two (Armor T-Shirt)


Rating: 2
Penalty: 1

Notes: Adds its rating to soak against bashing, lethal and aggravated damage from fangs and claws; not against fire or sunlight. The penalty comes off Dexterity-based dice pools.]==],
				},
				["Class Two (Cloth/Textile Armor)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Class Two (Cloth/Textile Armor)


Rating: 2
Penalty: 1]==],
				},
				["Cosplay Mail"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Cosplay Mail


Rating: 2
Penalty: -1]==],
				},
				["Cybernetic Armor"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Cybernetic Armor


Rating: 1-4
Penalty: 0

Notes: Built into the wearer; see the Background: Enhancement.]==],
				},
				["Enhanced Clothing"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Enhanced Clothing


Rating: 1-5
Penalty: 0

Notes: Clothing woven with advanced or Enlightened materials.]==],
				},
				["Flak Vest"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Flak Vest


Rating: 4
Penalty: -2]==],
				},
				["Full Plate"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Full Plate


Rating: 5
Penalty: -2]==],
				},
				["Kevlar Vest"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Kevlar Vest


Rating: 3
Penalty: -1]==],
				},
				["Leather Duster"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Leather Duster


Rating: 2
Penalty: -2]==],
				},
				["Metal Shield"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Metal Shield


Rating: 4/+2
Penalty: -2

Notes: Shield: soak bonus / difficulty bonus against attacks.]==],
				},
				["Military Armor"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Military Armor


Rating: 5
Penalty: -2]==],
				},
				["Reinforced Clothing"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Reinforced Clothing


Rating: 1-2
Penalty: 0

Notes: Clothing stiffened, padded or layered against harm.]==],
				},
				["Reinforced Clothing (Werewolf)"] = {
					en = [==[Werewolf: The Apocalypse 20th Anniversary Edition, p. 292


Reinforced Clothing (Werewolf)


Rating: 1
Penalty: 0]==],
				},
				["Riot Shield"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Riot Shield


Rating: 5/+2
Penalty: -1

Notes: Shield: soak bonus / difficulty bonus against attacks.]==],
				},
				["Riot Suit"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Riot Suit


Rating: 4
Penalty: -2]==],
				},
				["Riot Suit (Werewolf)"] = {
					en = [==[Werewolf: The Apocalypse 20th Anniversary Edition, p. 292


Riot Suit (Werewolf)


Rating: 5
Penalty: 3]==],
				},
				["Steel Breastplate"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Steel Breastplate


Rating: 3
Penalty: -2]==],
				},
				["Tough Hide"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Tough Hide


Rating: 1-3
Penalty: 0

Notes: Animals, Bygones, constructs or shapechanged mages with especially thick or armored skin.]==],
				},
				["Trash Can Lid"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Trash Can Lid


Rating: 3/+1
Penalty: 0

Notes: Shield: soak bonus / difficulty bonus against attacks.]==],
				},
				["Trashcan Lid"] = {
					en = [==[Werewolf: The Apocalypse 20th Anniversary Edition, p. 292


Trashcan Lid


Rating: 2
Penalty: 0

Notes: No Dexterity penalty, but a difficulty 6 Dexterity + Melee roll to employ.]==],
				},
				["Wooden Shield"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Wooden Shield


Rating: 2/+2
Penalty: -1

Notes: Shield: soak bonus / difficulty bonus against attacks.]==],
				},
				-- <<< ARMOR_DESC_END
};
