-- Revenant family traits, the en half (SPEC I21, I148d, V432, V210, V24 / T850).
--
-- One entry per item of PICKER_LIST["family"], keyed by the value the sheet SAVES, byte for
-- byte (SPEC V24). Block 3 is MECHANICS and nothing else - the Disciplines and the Weakness -
-- because that is what the owner asked the ? to say (SPEC I148d). The trio is read off CLANS
-- on the root form; the weakness sentence comes off FAMILY_WEAKNESS (family, root form) or
-- research/clan_weakness.tsv (clan, T970): the module is DERIVED from them and V432 reads it
-- back against them, so a drift shows up as a red gate and not as a pane that disagrees
-- with the slots (SPEC V135).
--
-- Three blocks separated by two blank lines (SPEC I21): source, name, body. The book title
-- does not translate and neither does the name in block 2 - it is the key; only p./pag. does.
--
-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24).
-- GENERATED by research/gen_traits_desc.ps1. Do not hand-edit: fix the table or the .tsv
-- it reads and run it again.

return {
				-- >>> FAMILY_DESC_BEGIN (generated - SPEC T850)
				["Basarab"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 454


Basarab


Disciplines: Animalism, Dominate, Presence

Weakness: Repelled by garlic and holy symbols: presented with either, a Willpower roll or they must remove themselves from its presence.]==],
				},
				["Bratovich (Dark Ages)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 454


Bratovich (Dark Ages)


Disciplines: Animalism, Potence, Vicissitude

Weakness: Given over to their own savagery, they suffer the same frenzy effects as the Brujah.]==],
				},
				["Bratovitch (Modern)"] = {
					en = [==[Ghouls & Revenants, p. 90-91


Bratovitch (Modern)


Disciplines: Animalism, Fortitude, Vicissitude

Weakness: +2 difficulty on every roll to resist frenzy. They may not spend Willpower to avoid a frenzy, only to end one.]==],
				},
				["D'Habi"] = {
					en = [==[Ghouls & Revenants, p. 92-93


D'Habi


Disciplines: Presence, Obfuscate, Daimonion

Weakness: Broken by centuries of infernal servitude, they are extraordinarily suggestible: +2 difficulty on all Willpower rolls.]==],
				},
				["Danislav"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 455


Danislav


Disciplines: Auspex, Protean, Vicissitude

Weakness: They take aggravated damage from silver.]==],
				},
				["Ducheski"] = {
					en = [==[Ghouls & Revenants, p. 94-95


Ducheski


Disciplines: Auspex, Dominate, Thaumaturgy

Weakness: Centuries under the Tremere left them far from their human side: no Ducheski may ever have a Social Attribute above 2.]==],
				},
				["Enrathi"] = {
					en = [==[Ghouls & Revenants, p. 96-97


Enrathi


Disciplines: Dominate, Obfuscate, Potence

Weakness: Centuries of moral decay: they may not have Humanity higher than 3, nor Conscience higher than 2.]==],
				},
				["Grimaldi (Dark Ages)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 455


Grimaldi (Dark Ages)


Disciplines: Celerity, Dominate, Fortitude

Weakness: Tzimisce blood runs thin in this family, which has no native ties to the Voivodate: they have only eight blood points.]==],
				},
				["Grimaldi (Modern)"] = {
					en = [==[Ghouls & Revenants, p. 98-99


Grimaldi (Modern)


Disciplines: Celerity, Dominate, Fortitude

Weakness: Family arrogance: whenever there is a chance to boast of the family, a Willpower roll at difficulty 7 to hold back their scorn.]==],
				},
				["Kairouan Brotherhood"] = {
					en = [==[Ghouls & Revenants, p. 100-101


Kairouan Brotherhood


Disciplines: Auspex, Celerity, Obfuscate

Weakness: Years of genetic manipulation: every member suffers the Slow Healing Flaw (V20 p. 483).]==],
				},
				["Keskinen"] = {
					en = [==[Ghouls & Revenants, p. 114


Keskinen


Disciplines: Thaumaturgy, plus two of Auspex, Dominate or Obfuscate

Weakness: All Keskinen share their patron's obsession with blotting out the sun, which manifests as a Derangement.]==],
				},
				["Khavi"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 455


Khavi


Disciplines: Animalism, Obfuscate, Vicissitude

Weakness: Vulnerable to sunlight: they take sunlight damage as a Cainite would, but bashing rather than aggravated, and may soak it with Stamina and Fortitude.]==],
				},
				["Krevcheski"] = {
					en = [==[Ghouls & Revenants, p. 94


Krevcheski


Disciplines: Auspex, Dominate

Weakness: Krevcheski are distrusted by the Tzimisce, and thus have only learned two family Disciplines instead of the normal three.]==],
				},
				["Marijava"] = {
					en = [==[Ghouls & Revenants, p. 114


Marijava


Disciplines: Celerity, Obfuscate, Presence

Weakness: Quite susceptible to the blood bond: they become Bound to a vampire after a single drink.]==],
				},
				["Obertus"] = {
					en = [==[Ghouls & Revenants, p. 102-103


Obertus


Disciplines: Auspex, Obfuscate, Vicissitude

Weakness: Bred for intellect and prone to psychological disorders: the vast majority suffer the Obsessive-Compulsive Derangement (V20 pp. 291-292).]==],
				},
				["Obertus (Narov)"] = {
					en = [==[Ghouls & Revenants, p. 102-103


Obertus (Narov)


Disciplines: Auspex, Dominate, Vicissitude

Weakness: Members of the resurging Narov line are afflicted with the Megalomania Derangement instead (V20 pp. 291-292).]==],
				},
				["Oprichniki"] = {
					en = [==[Ghouls & Revenants, p. 104-105


Oprichniki


Disciplines: Animalism, Obfuscate, Potence

Weakness: Cursed for their founders' crimes: they suffer the Haunted Flaw (V20 p. 495) permanently, and banishing one ghost only brings another.]==],
				},
				["Rafastio"] = {
					en = [==[Ghouls & Revenants, p. 106-107


Rafastio


Disciplines: Animalism, Auspex, Thaumaturgy

Weakness: Cursed by the moon: +2 difficulty to use Disciplines at the new moon, +1 waxing and waning, -1 at the full moon. Their blood rejects the Embrace, which has always killed them.]==],
				},
				["Rossellini"] = {
					en = [==[Ghouls & Revenants, p. 108-109


Rossellini


Disciplines: Dominate, Fortitude, Necromancy

Weakness: All of them suffer the Deathsight Flaw (V20 p. 494): -2 difficulty to resist Appearance-based rolls, +2 difficulty on Perception rolls and +1 on Social rolls.]==],
				},
				["Servants of Anushin-Rawan"] = {
					en = [==[Ghouls & Revenants, p. 110-111


Servants of Anushin-Rawan


Disciplines: Auspex, Obfuscate, Presence

Weakness: In the presence of a vampire descended from Anushin-Rawan they are compelled to protect that Ventrue as if blood bound, for 10 nights minus their Willpower.]==],
				},
				["Szantovich"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 455


Szantovich


Disciplines: Auspex, Presence, Vicissitude

Weakness: Addictive personalities: exposed to a sensual experience that has weakened them, a Willpower roll to do anything but pursue it, and Willpower may not be spent to resist the addiction.]==],
				},
				["Vlaszy"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 455


Vlaszy


Disciplines: Animalism, Potence, Presence

Weakness: Every Vlaszy swears a Blood Oath to a Fiend upon reaching the age of majority.]==],
				},
				["Zantosa"] = {
					en = [==[Ghouls & Revenants, p. 112-113


Zantosa


Disciplines: Auspex, Presence, Vicissitude

Weakness: Exposed to a pleasurable experience, a Willpower roll or they become obsessed with it. They may not spend Willpower to resist a supernatural power that entices them to a new pleasure.]==],
				},
				-- <<< FAMILY_DESC_END
};
