-- Road/Path descriptions, the [en] half (SPEC I141, I21, V210, V409 / T931).
--
-- One entry per item of PICKER_LIST["road"], keyed by the value the sheet SAVES, byte for
-- byte (SPEC V24, I142e): "Path of Humanity", not "Humanity". Both halves carry the SAME
-- 55 keys - a name in one and not the other reddens V210 in both directions.
--
-- FOUR blocks, not three (SPEC I141a): the third block of I21 splits in two, into the AURA
-- and the hierarchy of sins. Separator is the same two blank lines the other ten modules
-- use (SPEC Q56). The book title does not translate; only p./pag. does (SPEC I100e), and
-- neither does the name in block 2 - it is the key.
--
-- The aura name is the string BEARING already shows on the ROAD line of the Main tab, read
-- from WoD20th.lfm at generation time (SPEC I141b): there is no second identity for it, and
-- V409(c) measures exactly that. The pt spelling is the sheet PT map, same single owner.
--
-- A Path that inherits its table carries the mother table with its own levels SUBSTITUTED,
-- BAKED into the string (SPEC I141e, I141f): the levels it does not name keep the mother
-- text verbatim, so nothing at runtime needs to know who is mother to whom.
--
-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24).
-- GENERATED by research/gen_road_desc.ps1 from the .tsv in research/. Do not hand-edit:
-- fix the .tsv and run it again.

return {
				-- >>> ROAD_DESC_BEGIN (generated - SPEC T931)
				["Path of Humanity"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 310


Path of Humanity


Aura: Normalcy. Vampires on Humanity have a bearing of normalcy; the humane connection that such vampires hold keeps them from seeming strange and terrifying to mortals. The bearing modifier affects Social rolls for appearing normal and winning sympathy.


Hierarchy of Sin — Humanity

10 — Selfish thoughts

9 — Minor selfish acts

8 — Injury to another (accidental or otherwise)

7 — Theft

6 — Accidental violation (drinking a vessel dry out of starvation)

5 — Intentional property damage

4 — Impassioned violation (manslaughter, killing a vessel in frenzy)

3 — Planned violation (outright murder, savored exsanguination)

2 — Casual violation (thoughtless killing, feeding past satiation)

1 — Utter perversion or heinous acts]==],
				},
				["The Path of Blood"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 316


The Path of Blood


Aura: Resolve. Followers of the Path of Blood know the seriousness of their task and are incredibly dedicated to it. Their aura modifier affects Willpower rolls.


Path of Blood Hierarchy of Sins

10 — Killing a mortal for sustenance
      Human blood is nourishing to the body, but the murder of lessers is poison to the soul.

9 — Breaking a word of honor to a Clanmate
      Solidarity is important to the Assamites’ holy cause.

8 — Refusing to offer a non-Assamite an opportunity to convert
      The childer of Khayyin are accursed and must be saved.

7 — Failing to destroy an unrepentant Kindred outside the Clan
      Those who do not accept Haqim’s teachings forfeit their unlives.

6 — Succumbing to frenzy
      Haqim teaches ascendance, not indulgence.

5 — Failing to pursue the lore of Khayyin
      To oppose one’s enemies successfully, one must learn all about them.

4 — Failing to demand blood as payment
      Other members of the Clan may benefit from such vitae, no matter how diluted.

3 — Refusal to aid a more advanced member of the Path
      To act selfishly is to fall into the snares of Khayyin’s pawn.

2 — Failing to tithe blood
      Haqim has decreed this as paramount to his childer’s cause.

1 — Acting against another Assamite
      This is treason to the Path and the Clan.]==],
				},
				["The Path of the Bones"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 318


The Path of the Bones


Aura: Silence. The Gravediggers, accustomed as they are to long hours of quiet study and contemplation of the grave, radiate the stillness of death. The bearing modifier applies to rolls involving Stealth and attempts to go unnoticed.


Path of the Bones Hierarchy of Sins

10 — Showing a fear of death
      Fear inhibits learning.

9 — Failing to study an occurrence of death
      Refusal to learn indicates refusal to understand.

8 — Accidental killing
      There is no opportunity to gain insight.

7 — Postponing feeding when hungry
      Denial of the self serves no greater purpose.

6 — Succumbing to frenzy
      The Beast is irrational, and emotion serves little to advance understanding.

5 — Refusing to kill when an opportunity presents itself
      Experimentation proves theory, and without proof, there is no conclusion.

4 — Making a decision based on emotion rather than logic
      Vampires are dead; so, too, are their emotions.

3 — Inconveniencing oneself for another’s benefit
      Death is inevitable; what meaning does easing another’s doomed discomfort have?

2 — Needlessly preventing a death
      One must not prevent the cycle, but should learn from it.

1 — Actively preventing a death
      Such emotional ties befit humans, not Kindred.]==],
				},
				["The Path of Caine"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 320


The Path of Caine


Aura: Faith. The righteousness of the Cainite is apparent to all. The bearing modifier affects all rolls that rely on the vampire’s image as a devout Kindred and scholar of Caine’s teachings.


Path of Caine Hierarchy of Sins

10 — Failing to engage in research or study each night, regardless of circumstances
      The search for truth requires dedication.

9 — Failing to instruct other vampires in the Path of Caine
      All vampires must have the opportunity to explore their potential.

8 — Befriending or co-existing with mortals
      Caine was separated from mortals, as all vampires should be.

7 — Showing disrespect to other students of Caine
      All of the Children of Caine deserve the respect due their heritage, as long as they strive to understand themselves.

6 — Failing to ride the wave in frenzy
      Direct the Beast; do not be directed by it.

5 — Succumbing to Rötschreck
      Master your fear. Terror is for lesser beings.

4 — Failing to diablerize a “humane” vampire
      Those who do not explore their potential forfeit that potential.

3 — Failing to regularly test the limits of abilities and Disciplines
      Develop your capabilities to their limits in order to discern your true nature.

2 — Failing to pursue lore about vampirism when the opportunity arises
      Every scrap of knowledge adds a piece to the puzzle of undead existence.

1 — Denying vampiric needs (by refusing to feed, showing compassion, or failing to learn about one’s vampiric abilities)
      To be a vampire, one must satisfy a vampire’s needs.]==],
				},
				["The Path of Cathari"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 323


The Path of Cathari


Aura: Seduction. The Cathari are temptation incarnate, and they have an uncanny knack for knowing the desires of others. The bearing modifier affects rolls to tempt and seduce others.


Path of Cathari Hierarchy of Sins

10 — Exercising restraint
      One’s purpose is excess, not moderation.

9 — Showing trust
      Use or be used.

8 — Failing to pass on the Curse to the passionately wicked or virtuous
      The depraved can serve evil better as vampires; the virtuous can be overcome by the Curse.

7 — Failing to ride the wave in frenzy
      The Beast, as well as the higher self, must be indulged.

6 — Acting against another Albigensian
      Those of like purpose should fulfill that purpose, not quarrel among themselves.

5 — Impassioned killing
      Murder achieves no greater end; dead men cannot sully their souls.

4 — Sacrificing gratification for someone else’s convenience
      Promote physical pleasures, not altruistic achievements.

3 — Refraining from indulgence
      The material world is a place for the gratification of the flesh.

2 — Arbitrary killing
      Killing a mortal prevents his bringing about his own damnation.

1 — Encouraging others to exercise restraint
      Vampires are creatures of evil; the vampire’s purpose is to corrupt, not save.]==],
				},
				["The Path of the Feral Heart"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 324


The Path of the Feral Heart


Aura: Menace. Those in the presence of a Beast know that she is a true hunter, just as deer do when confronting a wolf. The bearing modifier applies to rolls aimed at terrifying or cowing an opponent.


Path of the Feral Heart Hierarchy of Sins

10 — Hunting with means other than your own vampiric powers
      The perfect hunter needs no tools.

9 — Engaging in politics
      Political struggles do not yield sustenance.

8 — Remaining in the presence of fire or sunlight, except to kill an enemy
      There is no sense in courting Final Death.

7 — Acting in an overly cruel manner
      Death is natural; feeding is natural. Torture and cruelty are not.

6 — Failing to hunt when hungry
      The vampire’s purpose is to feed.

5 — Failing to support your pack or allies
      Support your family, and it will support you.

4 — Killing without need
      A dead vessel may not be fed from in the future.

3 — Failing to follow one’s instincts
      Instinct is the basis of predatory nature.

2 — Killing a creature other than for survival
      A kill’s purpose is sustenance.

1 — Refusing to kill to survive
      Vampires are hunters; everyone else is the hunted.]==],
				},
				["The Path of Honorable Accord"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 326


The Path of Honorable Accord


Aura: Devotion. The Knights keep their word, and are very difficult to sway from their duty. The bearing modifier affects rolls to resist attempts to manipulate or force them to go against their given purpose.


Path of Honorable Accord Hierarchy of Sins

10 — Failing to uphold all the precepts of your group
      True duty to a cause requires sterling character.

9 — Failing to show hospitality to your allies
      Hospitality and generosity are the wealth of the soul.

8 — Associating with the dishonorable
      Serve as an example, but do not be dragged into pettiness.

7 — Failing to participate in your group’s rituals
      Tradition and ritual are important parts of heritage.

6 — Disobeying your leader
      Loyalty is the keystone of hierarchy.

5 — Failing to protect your allies
      Defend those who are worthy of your esteem.

4 — Placing personal concerns over duty
      Duty is the vampire’s purpose.

3 — Showing cowardice
      Honor lies in fighting for a cause, not in fleeing it.

2 — Killing without reason
      Life and death are God’s to decree.

1 — Breaking your word or oath; failing to honor an agreement
      To break one’s oath is to be without the honor that defines existence.]==],
				},
				["The Path of Lilith"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 329


The Path of Lilith


Aura: Tribulation. The Bahari see enlightenment through pain and conflict, and they learn to turn pain to their advantage. The bearing modifier affects rolls impacted by their own wound penalties.


Path of Lilith Hierarchy of Sins

10 — Feeding immediately when hungry
      Deprivation and hunger taught Lilith to survive.

9 — Pursuing temporal wealth or power
      True wealth comes from inside, not from money or influence.

8 — Not correcting the errors of others regarding Caine and Lilith
      Caine was a murderer, traitor, and fool who deserves no reverence.

7 — Feeling remorse for bringing pain to someone
      Pain and suffering help others to learn and grow.

6 — Failing to participate in a Bahari ritual
      The rituals handed down through time contain clues to awakening.

5 — Fearing death
      Death is simply an inevitable change to a new form of existence.

4 — Killing a living or unliving being
      Death denies one the chance to transcend.

3 — Not seeking out the teachings of Lilith
      Lilith hid her works in many places; they must be found.

2 — Failing to dispense pain and anguish
      Be a teacher through the pain.

1 — Shunning pain
      Only through pain are we reborn.To shun pain is to embrace ignorance.]==],
				},
				["The Path of Metamorphosis"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 331


The Path of Metamorphosis


Aura: Inhumanity. Metamorphosists work steadily to become something other than human. Bearing modifiers apply to Intimidation, as well as any Manipulation rolls that can be positively affected by frightening the target.


Path of Metamorphosis Hierarchy of Sins

10 — Postponing feeding when hungry
      Hunger causes distraction.

9 — Indulging in pleasure
      Hedonism deters one from greater ends.

8 — Asking another for knowledge
      The lessons of Metamorphosis are secrets that must be uncovered, not copied.

7 — Sharing knowledge with another
      Knowledge must be learned, not simply illustrated.

6 — Refusing to kill when knowledge may be gained from it
      Before transcending death, the Metamorphosist must understand it.

5 — Failing to ride out a frenzy
      A Kindred must know the Beast to transcend it.

4 — Considering the needs of others
      Those who cannot be bothered to attain Metamorphosis are beneath one’s attention.

3 — Failure to experiment, even at risk to oneself
      The Path can be understood only through empirical research.

2 — Neglecting to alter one’s own body
      Physical change must be attained before any more significant metamorphosis.

1 — Exhibiting compassion for others
      The fates of others drag one into devolution, not transcendence.]==],
				},
				["The Path of Night"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 332


The Path of Night


Aura: Darkness. Nihilists give off a faint air of inner darkness, inspiring those around them to dwell on their darkest fears and thoughts. Their bearing modifier applies to any attempts to bring out a victim’s inner darkness, such as eliciting dirty secrets from a wellrespected politician or convincing a saint to break her vow of chastity.


Path of Night Hierarchy of Sins

10 — Killing a mortal for food
      Dead mortals feel no dread.

9 — Acting in the interests of another
      There is no time to fulfill petty agendas.

8 — Failing to be innovative in one’s depredations
      Familiarity for one’s vile acts breeds contempt for them in others, and they may soon fail to shock.

7 — Asking aid of another
      Those who cannot provide for themselves fulfill their ends poorly.

6 — Accidental killing
      God has made Kindred horrors, not murderers.

5 — Bowing to another Kindred’s will
      The games of the Jyhad are diversions from the Damned’s true purpose.

4 — Intentional or impassioned killing
      Death serves no one; it merely deprives one of a victim.

3 — Aiding another
      Compassion has no place in a vampire’s undead heart.

2 — Accepting another’s claim to superiority
      All Kindred are equal under God’s plan.

1 — Repenting one’s behavior
      The Kindred’s purpose is to cause repentance, not to practice it.]==],
				},
				["The Path of Paradox"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 335


The Path of Paradox


Aura: Confidence. The Shilmulo believe that they are in the exact place and time they are meant to be, doing what they are meant to do — and it shows. The bearing modifier applies to attempts to manipulate or lead others.


Path of Paradox Hierarchy of Sins

10 — Embracing a woman
      Women should be bearers of life, not death.

9 — Embracing outside the jati
      Most others fail to comprehend the depth of the Paradox philosophy.

8 — Destroying another Shilmulo
      Charity does not, as is widely believed, begin at home.

7 — Killing a mortal for sustenance
      Death robs a person of the ability to fulfill their svadharma.

6 — Failing to destroy a vampire on another Path
      Those who cannot see the true way should be returned to a productive role in the cycle.

5 — Killing a mortal for reasons other than survival
      A person may not have achieved her svadharma, and preventing such is anathema.

4 — Failure to aid another’s svadharma
      The gods have set this as the Shilmulo’s purpose.

3 — Allowing one’s Sect affairs to take precedence over one’s dharma
      One’s allegiance should be to the gods, not one’s companions.

2 — Becoming blood bound
      One may never destroy one’s regnant, which is the whole purpose of this Path.

1 — Embracing needlessly or out of personal desire
      One must return others to the cycle, not extract them from it.]==],
				},
				["The Path of Power and the Inner Voice"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 336


The Path of Power and the Inner Voice


Aura: Command. Unifiers are destined for power, and they know it. Those around them can feel their commanding presence. Their bearing modifier affects rolls to command or lead others.


Path of Power and the Inner Voice Hierarchy of Sins

10 — Denying responsibility for your actions
      Dereliction of responsibility is a failure to lead properly.

9 — Treating your underlings poorly
      Reward competence as an incentive, but do so sparingly.

8 — Failing to respect your superiors
      Give the respect that is due, that you might learn something in turn.

7 — Helping others when it is not to your advantage
      Always gain something from your actions.

6 — Accepting defeat
      Succeed, or die.

5 — Failing to kill when it’s in your interests
      Do not hesitate to eliminate those who would stand against you.

4 — Submitting to the error of others
      Be right and you will be vindicated. Follow a fool and you will suffer for it.

3 — Not using the most effective tools for control
      Power must be seized. Be iron-fisted and resolute.

2 — Not punishing failure
      Failure is instructive only when used as a negative example.

1 — Turning down the opportunity for power
      Personal power is the means to all ends.]==],
				},
				["The Path of Typhon"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 338


The Path of Typhon


Aura: Devotion. The Theophidians do everything with an eye to how they might best serve Set. The bearing modifier aids in attempts to win converts and in rolls to resist powers based on other faiths (such as True Faith – see p. 372).


Path of Typhon Hierarchy of Sins

10 — Pursuing one’s own indulgences instead of another’s
      The slide into vice is a tool, not a recreation.

9 — Refusing to aid another follower of the Path
      Teams work more efficiently than individuals to raise Set.

8 — Failing to destroy a vampire in Golconda
      Those who have transcended their desires cannot brought under sway.

7 — Failing to observe Setite religious ritual
      You must not deny Set his due.

6 — Failing to undermine the current social order in favor of the Setites
      Other Kindred are purposeless or misled, and this indolence delays Set’s revival.

5 — Failing to do whatever is necessary to corrupt another
      The more individuals in the Setites’ debt, the better.

4 — Failing to pursue arcane knowledge
      The mysteries of Set’s resurrection may be hidden anywhere.

3 — Obstructing another Setite’s efforts
      The ranks of the righteous are no place for petty power plays.

2 — Failing to take advantage of another’s weakness
      Compassion has no place in Set’s greater plans.

1 — Refusing to aid in Set’s resurrection
      This is the purview of unbelievers.]==],
				},
				["The Path of the Hive"] = {
					en = [==[The Black Hand: A Guide to the Tal’Mahe’Ra, p. 53


The Path of the Hive


Aura: Justice. Abelenes carry an atmosphere of divine retribution. Their bearing modifier affects rolls to convince others of the righteousness of their actions.


Via Hyron: Path of the Hive Hierarchy of Sins

10 — Failing to ride the wave in frenzy
      The heart of Abel’s prized Beast was to him by the One Above. Its voice is sacred and unleashing its divinity protects his angels from assault.

9 — Failing to staunch the influence of institutionalized religion
      Throughout history, the deceiver, Lucifer, has twisted faith and clothed the spread of ignorance, bigotry, delusion, greed, and mayhem in the hypocrisy of religion. It is the duty of the Molochim to shepherd Caine’s flock.

8 — Feeding on the children of Seth
      Reclaim Abel’s blood in vengeance from the builders, Caine’s children. Those living in harmony with Creation in the wild are not subject to retribution from the One Above.

7 — Not actively pursuing safe knowledge of sorcery and the demonic
      Know thy enemy. Ignorance is darkness, and darkness is where the infernal hides. Blood sorcery is the sacrament in the arsenal against atrocity.

6 — Refusing an opportunity to convert those seeking redemption
      The larger the hive, the greater the swarm. Those who have faced the infernal are hornets without a Nest waiting to be saved. Bind them through the blood and release them when they find shelter

5 — Refusing to sing a lullaby to the sleepers
      The sleepers’ dreams are fueled by havoc and devastation visited upon Creation. Without fuel, the sleepers turn their attentions away from dreaming and seek to awaken.

4 — Not being selective in a lullaby
      Undirected destruction that does not serve as fertilizer for new Creation to emerge is no better than an awoken sleeper. Shepherd Creation by strategic application of violence and suffering.

3 — Failing to enslave or extinguish the demonic
      The One Above damned Lucifer and his children; their existence is forfeit.

2 — Failing to cleanse the infernal
      Each utterance of a sleeper’s name and soul lost to the demonic stirs the sleepers from dream.

1 — Failing to Nest
      Independence is the gateway to the infernal; Lucifer preys first upon individuals alone. Unity is the of the hive, isolation weakens the swarm. If leaving a Nest, find another.]==],
				},
				["The Path of the Scorched Heart"] = {
					en = [==[The Black Hand: A Guide to the Tal’Mahe’Ra, p. 55


The Path of the Scorched Heart


Aura: Intellect. Unforgiving are not easily swayed by appeals to emotion. Their bearing modifier affects rolls meant to influence them through Social Attributes.


Path of the Scorched Heart Hierarchy of Sins

10 — Failing to acquire knowledge that is safely and readily available
      Knowledge is the wellspring of truth; you can never know enough.

9 — Committing to any action without purpose
      Do not waste effort on what does not enhance you.

8 — Sacrificing when you gain less
      A victory that costs you more than you earn garners no benefit.

7 — Relying on others
      Your actions are the only ones you can predict with absolute certainty.

6 — Making assumptions
      Without clarity, error hides in the fog of unconsidered data.

5 — Acting rashly
      You cannot learn from indiscriminate action. Observe, think, calculate, consider, then act.

4 — Speaking falsely
      Truth is a bullet. Without trust, truth has no gun.

3 — Falling to frenzy or Rötschreck
      Carelessness is dangerous. You cannot control the threats you fail to see when not objective. If you cannot master yourself, you have no defense against others mastering you.

2 — Making decisions based on emotion
      The urges of emotion are the words of the Beast, not your own. Purge them.

1 — Acknowledging your emotions
      The Beast feels. You do not. Deny the Beast and it withers.]==],
				},
				["The Path of Self-Focus"] = {
					en = [==[The Black Hand: A Guide to the Tal’Mahe’Ra, p. 58


The Path of Self-Focus


Aura: Balance. Those around Internalists are relaxed by their peaceful presence. Their bearing modifier affects rolls to avoid confrontation or calm others down.


Path of Self-Focus Hierarchy of Sins

10 — Accepting everything
      A bowl filled to the brim will spill.

9 — Accepting nothing
      Oversharpen your knife and it will break.

8 — Laziness
      An ant on the move does more than a sleeping elephant.

7 — Interfering in the universe
      In order to lead, walk behind.

6 — Restraining the Beast
      Struggle creates conflict and moves you out of line with yourself.

5 — Failure to treat others as you would be treated
      Even a teacher must be questioned.

4 — Allowing the universe to interfere with you
      You alone control your actions.

3 — Overconfidence
      To know strength, harness weakness.

2 — Rejecting nothing
      Water is gentler and more flexible than anything, and yet nothing can resist it.

1 — Rejecting everything
      By not changing direction, you always arrive where you are headed.]==],
				},
				["The Path of Asakku"] = {
					en = [==[The Black Hand: A Guide to the Tal’Mahe’Ra, p. 115


The Path of Asakku


Aura: Otherworldly. Followers adopt an alien demeanor. Most utilize their Vicissitude constantly. Even when they attempt to blend in, all but the cleverest make unusual mistakes, marking themselves as beings unfamiliar with the human world. They ignore social conventions and stare in odd directions. An Asakku’s bearing modifier applies to Awareness and Occult rolls to sense supernatural energies.


Hierarchy of Sins against the Asakku

10 — Using or answering to your former name
      You are not a vampire. You are one strand in a web of power.

9 — Refusing to use Vicissitude at every opportunity
      Become your power.

8 — Failing to increase your command of Vicissitude to the greatest extent possible
      You must apply all your efforts to identifying with the Watcher within.

7 — Failing to commit Amaranth or convert a member of the Clan that practices Vicissitude
      Take back the power they have stolen.

6 — Refusing to teach Vicissitude
      Let the Watcher see through a thousand eyes.

5 — Allowing enemies to discover your true haven
      Your lair belongs to the Watcher.

4 — Betraying another of the Corrupted
      We emanate from the same darkness and must claw our way into the world together.

3 — Allowing enemies to discover your true nature
      Let Caine’s bastards forget the origins of their gifts until we are ready to reclaim them openly.

2 — Refusing to convert those under the blood bond to the Path
      The Watcher requires followers to manifest more powerfully.

1 — Failing to use Vicissitude nightly, unless in torpor
      The murmuring shadow within must speak]==],
				},
				["The Path of Entelechy"] = {
					en = [==[Lore of the Clans, p. 51


The Path of Entelechy


Aura: Stoicism. The Philosophers bring a pragmatism to undeath that allows them to maintain equanimity in the face of the childish taunts and cruel barbs of their less enlightened Kindred. The bearing modifier adds on all rolls to resist frenzy when provoked by insults or other deliberately provocative actions by others. It does not affect frenzy rolls triggered by other forms of rage-inducing stimuli.


PATH OF ENTELECHY HIERARCHY OF SINS

10 — Ill-defined or idle thinking
      Only rigidity of thought can allow for mastery over the Beast.

9 — Refusing to intervene when another vampire is at risk for degeneration
      In helping others to control their impulses, you learn more on how to control your own.

8 — Acting on impulse
      Acting without careful thought leads to a loss of control.

7 — Theft, robbery, or vandalism
      Acting against others is the path away from Humanity.

6 — Refusing to stand up for a moral principle out of fear or cowardice
      It is only through the defense of morality that you can understand it.

5 — Causing deliberate harm to a mortal, including violent nonconsensual feeding
      If you harm a mortal’s body, you also harm your own spirituality.

4 — Aiding a follower of another Path that does not respect humanity
      Aiding those who reject humanity (and Humanity) is as bad as rejecting it yourself.

3 — Succumbing to frenzy when wise conduct could have avoided it
      Do not give the Beast a chance to flourish.

2 — Allowing any violent crime against an innocent to go unpunished
      If you allow others to come to harm without punishment, it is as if you committed the harm yourself.

1 — The murder of innocents
      Taking a life is the worst loss of control one can commit.]==],
				},
				["The Path of Ecstasy"] = {
					en = [==[Lore of the Clans, p. 70


The Path of Ecstasy


Aura: Rapture. Ecstatics know how to use earthly sensations and passions to transcend the mundane. Their bearing modifier affects rolls to excite extreme and transformative emotional responses in themselves and others.


Path of Ecstasy Hierarchy of Sins

10 — Suffering an innocent to live
      A soul unwilling to touch the beyond, via sensation, should be sent by a more direct route.

9 — Not wallowing in absolute decadence
      Always, always drown the Beast.

8 — Refusing to break a taboo
      Transgressing any sacred border deteriorates the paradigm of the Aeons.

7 — Allowing an infector of impurity (i.e. priest, nun, etc.) to live without good reason
      Unless they can be compromised, the hypocrites will continue serving the purpose of the Aeons.

6 — Failing to create a beautiful moment
      In a world choked in nihilism, it is a sin to not open a window to the divine when inspiration strikes.

5 — Not attempting to corrupt an innocent
      Free the shackled sheep when you can.

4 — Not taking at least one drug regularly
      A malleable mind is more open to the supernal.

3 — Restraining your natural impulses unnecessarily
      The compulsion of repression is a useless artifact, implanted by the Aeons, and must be cut out.

2 — Refusing to subvert the chains of the Aeons
      Without our glorious purpose, we are naught but shabby hedonists.

1 — Destroying something of beauty, even an innocent
      We refuse to make the world any less interesting.]==],
				},
				["The Path of the Warrior"] = {
					en = [==[Lore of the Clans, p. 72


The Path of the Warrior


Aura: Fury. The Wraths burn with divine rage. Their bearing modifier applies to cowing others (Intimidation rolls) and even their own Beasts (rolls to resist both frenzy and Rötschreck).


Path of the Warrior Hierarchy of Sins

10 — Not subjecting yourself to the most painful tortures
      Your flesh must be purified for its holy purpose.

9 — Failing any test set before you, physical or mental
      Failure is unworthy of the Dark God.

8 — Not developing your body to its fullest potential
      You are a weapon wielded by Set, and you must be sharp.

7 — Spending blood points to heal your wounds the same night they are inflicted
      Pain is a teacher. Do not skirt your lessons.

6 — Not developing your Disciplines to their fullest potential
      Divinity is wasted on those who do not unlock its gifts.

5 — Killing swiftly and mercifully
      A dying enemy must know despair if Set is to hear your offering.

4 — Showing any sign of pain
      Your pain belongs to you and to no one else whom you do not give it to.

3 — Succumbing to frenzy or Rötschreck
      If you have all the power in the world, and the Beast controls you, you have nothing.

2 — Thinking too long before acting
      Hesitation is a mortal failing and unworthy of you.

1 — Refusing to aid in Set’s resurrection
      The final battle cannot begin until the God of Storm and Sky returns.]==],
				},
				["Road of the Beast"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 117


Road of the Beast


Aura: Menace. The Beast is welcome in the Apostate’s skin, and it shows not only in the penetration of her stare, but in the flickering reflection of her soul. The Beast, in many ways, is her spirit, and its dangerous lust for survival at all costs paints savage shadows and blood all over her aura.


HIERARCHY OF SINS AGAINST WHO YOU ARE

10 — Risking your own life
      Survival is paramount.

9 — Acknowledging a leader
      There is no “us”, only “me.”

8 — Killing for pleasure
      Never waste.

7 — Choosing to live in order over chaos
      Civilization softens you.

6 — Cruelty for pleasure
      Cruelty is wasted energy.

5 — Doing something for nothing
      Charity doesn’t feed the Beast.

4 — Failing to kill when survival is on the line
      If it comes down to you or them, it must be you.

3 — Not protecting what is yours
      Make it yours, keep it yours.

2 — Having no things that are yours
      Mark your territory, mark your people, mark your herd.

1 — Refusing to feed when hungry
      There is no balance when the Beast is denied.]==],
				},
				["Road of Humanity"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 122


Road of Humanity


Aura: Normalcy. The Cainite walking the Road of Humanity strives to emulate her past state wherever possible. In matters of empathy and mutual understanding with mortals, her Aura will influence the outcome.


HIERARCHY OF SINS AGAINST THE SOUL

10 — Selfish thoughts
      If it can be thought, it can be done.

9 — Minor selfish acts
      Putting oneself first lets the Beast in.

8 — Injury to another
      Accidental or not, there is still blood on your hands.

7 — Theft
      Only an animal takes without thought of consequence

6 — Accidental violation of another
      Humanity is a shared condition, his suffering is your own.

5 — Wanton destruction
      Are you a person or an animal?

4 — Impassioned violation of another
      Passion behind violence is the whispering of the Beast.

3 — Planned violation of another
      To be so cold is to reject the warmth of humanity.

2 — Casual violation of another
      Even wild animals know better.

1 — The most monstrous, vile acts
      Are you a person or a monster?]==],
				},
				["Road of Kings"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 126


Road of Kings


Aura: Command. Luminaries are self-possessed and confident in their right to rule. Others can feel their commanding presence like a chain placed around the neck.


HIERARCHY OF SINS AGAINST KINGSHIP

10 — Forgoing your duty
      Those who do not maintain responsibilities often lose them.

9 — Treating a peer with disrespect
      Respect must be given to earn it from others.

8 — Placing personal desires over duty
      A leader must do what is best for the many, not the one.

7 — Treating an inferior as an equal
      Everyone should know their place, including you.

6 — Killing without purpose
      Displays of power should inspire fear or respect.

5 — Showing weakness in front of inferiors
      A leader must be strong at all times.

4 — Failing to answer a challenge to your honor
      Honor and reputation are everything.

3 — Treating your superior with disrespect
      Superiors must be given the respect they are due.

2 — Breaking your word or oath
      Your word is your honor. If you have no honor, you have no worth.

1 — Giving in to your Beast, such as frenzy
      If you cannot control yourself, how can you control others?]==],
				},
				["Road of Lilith"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 129


Road of Lilith


Aura: Carved and bleeding. A Bahari’s aura manifests as any other vampire’s might, though chunks and swirls may appear carved out of the whole. If one concentrates, they might think they see symbols in these shifting carvings, but can catch none of them. Further, the aura seems to bleed or drip, making the “carvings” appear more like wounds. Acts of creation and mentorship receive the character’s aura modifier.


HIERARCHY OF SINS AGAINST WHO YOU ARE

10 — Feeding immediately when hungry
      There is a lesson in every denial, and there is control in self-denial.

9 — Joining a system created by those with no wisdom
      Live outside their lies.

8 — Ignoring one of Lilith’s faces
      Wherever you go, the Dark Mother has left messages for you. Read their myths and show them where Lilith lives.

7 — Rejecting the suffering of others or dismissing it
      Teach whenever the opportunity presents itself, even if you think the lessons learned would be beneath you.

6 — Cruelty for its own sake
      As a teacher, you must craft your lessons. Petty abuses are beneath you. The pain you inflict must be divine.

5 — Stealing great learning and claiming it as your own
      If you did not discover the wisdom yourself, you have no rights claiming it or authority based on it.

4 — Destroying a thinking being
      They can neither learn from you nor teach you if they have been destroyed.

3 — Not seeking out the teachings of Lilith
      Turn over the leaf, split the wood, and find her secrets wherever they hide.

2 — Getting between someone and a valuable lesson
      Better to pull the stars from the heavens than to rob someone of moments of true gnosis.

1 — Shunning pain
      The harder it is, the more rewarding the growth.]==],
				},
				["Road of Metamorphosis"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 133


Road of Metamorphosis


Aura: Inhumanity. Seekers are decidedly alien, having worked so very hard to cast aside their own humanity. Modifiers apply anytime another’s fear, anxiety, or discomfort might impact a roll.


HIERARCHY OF SINS AGAINST TRANSMOGRIFICATION

10 — Failing to ride out a frenzy
      While you can glean knowledge from the Beast, you must not allow your baser impulses to control you.

9 — Offering unsolicited knowledge to another
      Most are not on your path, but do not presume to take away their choice.

8 — Allowing pleasure or emotion to distract you
      Hedonism deters greater ends.

7 — Asking another for knowledge
      No one can teach you apotheosis. You must discover its secrets yourself.

6 — Denying yourself sustenance
      Hunger is the most basic distraction.

5 — Succumbing to conventional morality when knowledge could be gained
      Without transgressing, you will never find what is hidden from sight.

4 — Placing others above your quest for knowledge
      Those who wish to chain themselves to this world will hold you back as well.

3 — Failure to experiment due to compassion, discomfort, or personal risk
      We may flounder in the dark, and it may be unpleasant, but it is our only way forward.

2 — Loving another
      Love puts itself above all things, even Metamorphosis. Do not allow this.

1 — Neglecting to alter one’s own body
      If the forms we have were suited for ascension, we would already have ascended.]==],
				},
				["Road of Sin"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 135


Road of Sin


Aura: Temptation. The Sinners are free and their Road full of promise, and they are adept at recognizing the desires of others. Their aura modifier affects rolls to cajole and entice.


HIERARCHY OF SINS AGAINST YOURSELF

10 — Acknowledging any authority over your own
      You are beyond submission.

9 — Failing to indulge a new desire
      No pleasure should be denied you.

8 — Failing to ride the wave of frenzy
      The Beast tires with exercise, strengthens with denial.

7 — Forfeiting long-term pleasures for short-term ones
      Do not exchange floods of desire for a draught.

6 — Putting the needs of others ahead of your own pleasure
      Your need outweighs everything else.

5 — Swearing an oath
      Be bound by none, least of all yourself.

4 — Refusing to act against those who attempt to bind you
      The truest chains are self-imposed, but false ones can bind just as well.

3 — Refusing to feed or kill when necessary
      No life is worth more than your own.

2 — Encouraging the tenets or virtues of another Road
      All other Roads lead to gilded cages and liberated Beasts.

1 — Refusing to act in your own best interests
      Only fools sacrifice themselves.]==],
				},
				["Road of Bones"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 140


Road of Bones


Aura: Silence. The stillness of the grave and the hush of quiet study surround followers of this road. Their aura modifier applies to all Stealth rolls.


HIERARCHY OF SINS AGAINST KNOWLEDGE

10 — Refusing to share knowledge with a worthy recipient
      Scholarship is improved with informed review.

9 — Wanton destruction and cruelty
      Beasts and idiots will discover nothing but the stake.

8 — Refusing to kill when useful or necessary
      Let no mortal squeamishness impede your quest.

7 — Being swayed by emotion
      Study emotion as an expression of the soul, but do not let it guide your hand.

6 — Succumbing to frenzy
      A raging Beast is a poor observer.

5 — Pursuing power, prestige, or mortal attachments instead of knowledge
      These things are means to an end and nothing more.

4 — Allowing compassion or pity to influence you
      Affecting compassion may be useful to manipulate your enemies, but don’t let it enter your heart.

3 — Needlessly preventing a death
      All flesh is dust.

2 — Showing fear of death
      Be not afraid of the truth.

1 — Destroying irreplaceable sources of knowledge
      Destroying an artifact destroys an entire world.]==],
				},
				["Road of Yasa"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 141


Road of Yasa


Aura: Trust. Those above you trust you will do your duty obediently. Those beneath you trust you will treat them fairly. Enemies trust you will respect them by doing everything in your power to defeat them. The aura modifier affects Leadership rolls applied against subordinates, and Intimidation rolls against enemies.


HIERARCHY OF SINS AGAINST THE YASA

10 — Ignoring an insult
      You have earned the respect of others.

9 — Insulting another undeservedly
      You must show respect to those who have earned it.

8 — Lying to one who has proved themselves honest
      Honesty demands honesty.

7 — Abusing your herd
      The herd is not just for one.

6 — Showing mercy to one who has not submitted
      The weak must accept you as their master.

5 — Losing a battle due to pride
      Defeat your enemy now. Assuage your ego later.

4 — Harming family, anda, herd, or allies while in frenzy
      A warrior’s essential quality is discipline.

3 — Disobeying the order of your noyan
      Obedience is the foundation of honor.

2 — Betraying your family
      You will never know a stronger bond than that of blood.

1 — Betraying your Bloodbrothers
      The family of choice is the strongest.]==],
				},
				["Road of Blood"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 432


Road of Blood


Aura: Resolve. A follower of the Road of Blood takes his task seriously and is dedicated to following through. The aura modifier affects Willpower rolls.


Sins Against the Blood

10 — Acting impulsively in any situation
      Discipline is strength.

9 — Allowing actions to be dictated by emotion
      Passion is the first stirring of the Beast.

8 — Succumbing to frenzy
      Our will must be unshakable.

7 — Failing to diablerize an unworthy vampire
      Return the blood of the unworthy to Haqim.

6 — Acting cowardly or dishonorably
      Our actions reflect on our father, Haqim.

5 — Allowing the unworthy to go unpunished
      We are the judges of the unliving.

4 — Showing weakness before the unworthy
      We represent Haqim in all things.

3 — Failing to honor an oath
      Our honor is what sets us apart.

2 — Submitting to the will of an unworthy prince or elder
      Nothing in this world may sway us from our sacred purpose.

1 — Becoming oathbound to another Cainite
      We serve Haqim and no other.]==],
				},
				["Road of Paradox"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 445


Road of Paradox


Aura: Confidence. The Asura are certain that they are always where they should be, doing what they are meant to do. Their confidence washes over others, inspiring them to great things.


SINS AGAINST PARADOX

10 — Failing to accept death
      Your svadharma is only temporary, you must eventually return to the samsara.

9 — Embracing outside the jati
      Only Embrace those that will follow the Road of Paradox.

8 — Destroying another Asura
      Your fellows on this Road have a svadharma, do not stop them.

7 — Killing a mortal for sustenance
      Death prevents a person from fulfilling their svadharma in this part of the cycle.

6 — Failing to kill vampires on another Road
      Only by accepting the true path to moksha can a vampire atone. Otherwise, they are useless.

5 — Allowing personal affairs to interfere in your svadharma
      You must follow your sacred duty at all times.

4 — Failure to aid another’s svadharma
      This is your only purpose before returning to the cycle.

3 — Killing a mortal for any reason other than survival
      Preventing others from achieving their svadharma is anathema.

2 — Becoming blood bound
      You cannot destroy your regnant, which could prevent you from following your svadharma.

1 — Embracing needlessly out of personal desire
      You must allow others to continue their cycle, not remove them from it.]==],
				},
				["The Code of Samiel"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 448


The Code of Samiel


Aura: Sacrifice. The Aura of Samiel’s chosen helps with any attempt to put oneself in harm’s way for another.


HIERARCHY OF SINS AGAINST RIGHTEOUSNESS

10 — Failing to punish corruption and sin
      Evil prospers in the unchallenged heart.

9 — Acting out of avarice or lust
      Honor must be stronger than steel.

8 — Bearing false witness
      Your sword is that of truth.

7 — Feeding from the innocent without permission
      As the Healers are bound, so shall we be.

6 — Failing to defend or aid a person in need
      A dead heart finds life in service to others.

5 — Failing to defend or aid a Healer in need
      The red right hand defends the left.

4 — Letting a worthy challenge go unanswered
      Be as the lion, not as the lamb.

3 — Failing to challenge a vampire with a low Road
      Their souls endanger Cainite and kine.

2 — Neglecting an opportunity to exact vengeance
      Let retribution be your pride and purview.

1 — Aiding demons, Baali, Setites, or other evils
      Offer the wicked no succor but salt and fire.]==],
				},
				["Road of the Abyss"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 442


Road of the Abyss


Aura: Darkness. Their Aura affects any attempt to chase the darkness, and to pursue forbidden truths.


The Road of the Abyss

10 — Showing fear of the dark
      Darkness has much to teach us about the Abyss.

9 — Failing to observe a manifestation of darkness
      Only through observation can one increase knowledge.

8 — Expressing reverence for creation
      Creation is a blight, a taint of the purity of the Abyss.

7 — Refusing to feed when hungry
      Hunger is a manifestation of the void.

6 — Refusing to kill when it is the most expedient path
      Everything returns to the Abyss in time.

5 — Giving in to frenzy
      In order to master the darkness, you must first master yourself.

4 — Refusing to share knowledge with another Abyss mystic
      Full understanding of the Abyss cannot be attained without the insight of others.

3 — Letting morality hinder study of the Abyss
      Morals are a light-born weakness. We are creatures of darkness.

2 — Needlessly avoiding the darkness
      We are creatures of darkness. To reject it is to reject yourself.

1 — Showing aversion to the Abyss
      You cannot master that which you fear.]==],
				},
				["Road of Set"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 449


Road of Set


Aura: Devotion. Their Aura benefits attempts to proselytize for their god.


HIERARCHY OF SINS AGAINST SET

10 — Pursuing personal indulgence over the interests of the Path
      Dissolution is the pastime of the weak.

9 — Refusing to aid another follower of the Path
      We must work together if we are to eliminate our enemies.

8 — Failing to acquire leverage against enemies of the Road
      The unrighteous shall be destroyed and the weak converted.

7 — Refusing to spread the worship of Set
      Those who bear the blood of Set bear a sacred duty to spread his word.

6 — Failing to observe Setite rituals
      Only through our devotion do we earn Set’s favor.

5 — Failing to sow chaos among the enemies of the Road
      Let the ungodly be cast down.

4 — Failing to do whatever is needed to convert the pious of other faiths
      Where they lead, others will follow.

3 — Obstructing another Setite’s efforts
      We all work toward a common purpose.

2 — Refusing to aid in Set’s resurrection
      It is our sacred duty to restore our lord’s place in the world.

1 — Worshipping any god but Set
      Set is our progenitor and protector. There is no true god but Set.]==],
				},
				["Path of the Archangel"] = {
					en = [==[Dark Ages Companion, p. 70


Path of the Archangel


Aura: Melancholia. A Childe of the Archangel applies modifiers whenever her great loss and longing would engender a reaction, or when being seen as a martyr is relevant.


SINS AGAINST THE ARCHANGEL

10 — Indulging in any temptation
      True katharsis purges all passions.

9 — Going one night without performing any creative work
      In art, we illuminate truth.

8 — Turning away from those who need inspiration
      An angel’s work is in guiding the lost.

7 — Refusing to make a minor sacrifice
      Shedding earthly things brings us closer to divinity.

6 — Leaving fellow Toreador to languish unbaptized
      We are all Michael’s chosen.

5 — Going one week without performing any creative work
      Art is how the soul worships.

4 — Indulging in temptations of the flesh
      In katharsis we renounce carnal passions.

3 — Abandoning any in your charge
      We must earn the worship of the flock.

2 — Giving in to your Beast, such as frenzy
      Katharsis purges our basest urges first and foremost.

1 — Refusing to make a major sacrifice
      We follow Michael’s example in all things.]==],
				},
				["Road of Angra Mainyu"] = {
					en = [==[Dark Ages Companion, p. 84


Road of Angra Mainyu


Aura: Corruption. Vampires on the Road of Angra Mainyu carry an aura of corruption. Their voices are honeyed and they gain a +2 dice bonus to persuade people to evil.


HIERARCHY OF SINS AGAINST APEP

10 — Committing any act of kindness
      The vampire is a servant of Angra Mainyu, the bringer of evil.

9 — Delaying carnal gratification
      Denial of one’s desires is a denial of one’s true self.

8 — Refusing an opportunity to corrupt a mortal
      Order prevents us from being who we truly are.

7 — Refusing an opportunity to corrupt a vampire
      We are the children of Apep. His gift must not be rejected.

6 — Refusing an opportunity to corrupt a holy figure
      Weakness must be cast aside.

5 — Failing to undermine the prevailing mortal environment
      Stagnation promotes weakness.

4 — Failing to undermine Cainite structures of power
      Times of strife help us discover our true strength.

3 — Placing another’s wishes above your own
      Civilization is a lie.

2 — Feeding on evil men
      The vampire must not harm other servants of Angra Mainyu.

1 — Fearing frenzy
      Rage and Hunger are gifts from Angra Mainyu, and the vampire must embrace them.]==],
				},
				["Road of Ahura Mazda"] = {
					en = [==[Dark Ages Companion, p. 84


Road of Ahura Mazda


Aura: Holiness. Vampires on the Road of Ahura Mazda gain an aura of goodness. They can spend two Willpower during frenzy to name something they absolutely won’t do, i.e. “I won’t harm that child.” (“I won’t harm any children” is too broad, and the child of the first example is still fair game in a later frenzy.)


HIERARCHY OF SINS AGAINST THE SOUL

10 — Fearing Final Death
      The vampire has worked her way back to Ahura Mazda. Heaven awaits when she dies.

9 — Minor selfish acts
      Putting oneself first lets the Beast in.

8 — Speaking evil words, speaking ill of others
      Words carry to the ear of Ahura Mazda.

7 — Theft
      Only an animal takes without thought of consequence

6 — Accidental violation of another
      Humanity is a shared condition, his suffering is your own.

5 — Wanton destruction
      Are you a person or an animal?

4 — Impassioned violation of another
      Passion behind violence is the whispering of the Beast.

3 — Planned violation of another
      To be so cold is to reject the warmth of humanity.

2 — Casual violation of another
      Even wild animals know better.

1 — Feeding on good men
      The vampire has chosen Ahura Mazda, and must protect the good and righteous.]==],
				},
				["Path of the Hunter"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 117


Path of the Hunter


Aura: Menace. The Beast is welcome in the Apostate’s skin, and it shows not only in the penetration of her stare, but in the flickering reflection of her soul. The Beast, in many ways, is her spirit, and its dangerous lust for survival at all costs paints savage shadows and blood all over her aura.


HIERARCHY OF SINS AGAINST THE HUNT

10 — Risking your own life
      Survival is paramount.

9 — Acknowledging a leader
      There is no “us”, only “me.”

8 — Ignoring potential threats to your hunt.
      Others will try to limit your hunting rights. Do not let them.

7 — Acting without a plan
      A careless Hunter is a failure before she starts.

6 — Cruelty for pleasure
      Cruelty is wasted energy.

5 — Doing something for nothing
      Charity doesn’t feed the Beast.

4 — Failing to kill when survival is on the line
      If it comes down to you or them, it must be you.

3 — Not protecting what is yours
      Make it yours, keep it yours.

2 — Hunting without ritual preparation
      The Hunt is the only sacred thing.

1 — Refusing to feed when hungry
      There is no balance when the Beast is denied.]==],
				},
				["Path of Journeys"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 118


Path of Journeys


Aura: Menace. The Beast is welcome in the Apostate’s skin, and it shows not only in the penetration of her stare, but in the flickering reflection of her soul. The Beast, in many ways, is her spirit, and its dangerous lust for survival at all costs paints savage shadows and blood all over her aura.


HIERARCHY OF SINS AGAINST JOURNEYS

10 — Risking your own life
      Survival is paramount.

9 — Acknowledging a leader
      There is no “us”, only “me.”

8 — Killing for pleasure
      Never waste.

7 — Choosing to live in order over chaos
      Civilization softens you.

6 — Cruelty for pleasure
      Cruelty is wasted energy.

5 — Doing something for nothing
      Charity doesn’t feed the Beast.

4 — Failing to kill when survival is on the line
      If it comes down to you or them, it must be you.

3 — Failing to explore
      You cannot know what lies around the corner if you don’t go looking.

2 — Acknowledging ties to a land or people
      Reject their titles and their attempts to domesticate you.

1 — Refusing to feed when hungry
      There is no balance when the Beast is denied.]==],
				},
				["Path of Liberation"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 118


Path of Liberation


Aura: Menace. The Beast is welcome in the Apostate’s skin, and it shows not only in the penetration of her stare, but in the flickering reflection of her soul. The Beast, in many ways, is her spirit, and its dangerous lust for survival at all costs paints savage shadows and blood all over her aura.


HIERARCHY OF SINS AGAINST LIBERATION

10 — Risking your own life
      Survival is paramount.

9 — Acknowledging a leader
      There is no “us”, only “me.”

8 — Failing to expose someone to a hard truth
      Liberation belongs to everyone.

7 — Choosing to live in order over chaos
      Civilization softens you.

6 — Taking comfort in the city instead of dismantling it
      If it makes your life easier, it makes you weaker. Destroy it.

5 — Doing something for nothing
      Charity doesn’t feed the Beast.

4 — Failing to kill when survival is on the line
      If it comes down to you or them, it must be you.

3 — Not protecting what is yours
      Make it yours, keep it yours.

2 — Having no things that are yours
      Mark your territory, mark your people, mark your herd.

1 — Empowering tyranny
      You create liberation, if they want it or not.]==],
				},
				["Path of Christianity"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 120


Path of Christianity


Aura: Holiness. The Faithful receive bonuses whenever they are in situations where being seen as holy would lend them social advantage.


THE PATH OF CHRIST (CHRISTIANITY)

10 — Failing to denounce corruption and sin
      All that evil needs to triumph is the inaction of the righteous.

9 — Acting out of pride, avarice, lust, or other sinful impulse
      The road to the Beast is paved in sin.

8 — Bearing false witness
      A lying tongue is hateful in the eyes of the Lord.

7 — Causing harm to a pious person
      God protects the innocent.

6 — Feeding from an innocent without permission
      Corruption of the innocent is a grave sin.

5 — Blasphemy or heresy in word or act
      Blasphemy is a sin against God.

4 — Murder of innocents
      Thou shalt not kill, sayeth the Lord.

3 — Worshiping false idols
      Thou shalt not have any other god before me.

2 — Aiding demons or supernatural evil
      It is the duty of the righteous to smite the wicked.

1 — Failing to spread the Gospel of Christ
      It is the duty of all Christians to spread the good news of our Lord]==],
				},
				["Path of Life/Judaism"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 120


Path of Life/Judaism


Aura: Holiness. The Faithful receive bonuses whenever they are in situations where being seen as holy would lend them social advantage.


DERECH CHAIM — THE PATH OF LIFE (JUDAISM)

10 — Failing to maintain a state of ritual purity
      And ye shall be holy men unto me.

9 — Unnecessary contact with non-Jews
      The people must be protected.

8 — Failing to find a rabbinical authority to make rulings for you, and obey those rulings
      In whatever place there is a profanation of God’s name, they do not show respect to their rabbi.

7 — Failing to obey the laws and customs of the local Jewish community
      The spiritual needs of the individual can only be met through community.

6 — Failing to maintain a connection to a local Jewish community
      Jews cannot exist in isolation.

5 — Drinking impermissible blood
      For the life of the flesh is in the blood.

4 — Worshipping idols
      Hear, O Israel, God is One.

3 — Committing sexual violence
      It is worse to wrong a fellow person than it is to wrong God.

2 — Murder
      Whoever sheds the blood of man, by man shall his blood be shed.

1 — Endangering the Jewish community
      You shall not stand by the blood of your fellow.]==],
				},
				["Path of the Prophet/Islam"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 121


Path of the Prophet/Islam


Aura: Holiness. The Faithful receive bonuses whenever they are in situations where being seen as holy would lend them social advantage.


THE PATH OF THE PROPHET (ISLAM)

10 — Failing to honor your elders
      Say not to them a word of contempt but address them in terms of honor.

9 — Failing to care for the defenseless
      All power is a gift from God.

8 — Being dishonest or unfair in your dealings with others
      Give full measure for measure and weigh with a balance that is straight.

7 — Breaking a promise
      Every covenant will be inquired into on the Day of Reckoning.

6 — Boastfulness or arrogance
      Successful are those who humble themselves in prayers.

5 — Feeding from a non-Muslim
      He hath forbidden that which has been immolated to any other god.

4 — Killing unjustly
      Nor take life — which Allah has made sacred — for unjust cause.

3 — Acknowledging any god but Allah (and Muhammad is His Prophet)
      Take not with Allah another object of worship.

2 — Breaking the unity of Islam
      You Muslims are the best nation brought out for Mankind.

1 — Failing to submit to the will of Allah as revealed through his Prophet and revelation
      God alone possesses all power and glory.]==],
				},
				["Path of Breath"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 123


Path of Breath


Aura: Normalcy. The Cainite walking the Road of Humanity strives to emulate her past state wherever possible. In matters of empathy and mutual understanding with mortals, her Aura will influence the outcome.


HIERARCHY OF SINS AGAINST BREATH

10 — Allowing yourself to think or act as a vampire

9 — Minor selfish acts
      Putting oneself first lets the Beast in.

8 — Injury to another
      Accidental or not, there is still blood on your hands.

7 — Knowingly letting a human suffer

6 — Accidental violation of another
      Humanity is a shared condition, his suffering is your own.

5 — Wanton destruction
      Are you a person or an animal?

4 — Impassioned violation of another
      Passion behind violence is the whispering of the Beast.

3 — Planned violation of another
      To be so cold is to reject the warmth of humanity.

2 — Casual violation of another
      Even wild animals know better.

1 — Spending a night without human contact]==],
				},
				["Path of Community"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 124


Path of Community


Aura: Normalcy. The Cainite walking the Road of Humanity strives to emulate her past state wherever possible. In matters of empathy and mutual understanding with mortals, her Aura will influence the outcome.


HIERARCHY OF SINS AGAINST COMMUNITY

10 — Selfish thoughts
      If it can be thought, it can be done.

9 — Minor selfish acts
      Putting oneself first lets the Beast in.

8 — Injury to another
      Accidental or not, there is still blood on your hands.

7 — Accidental destruction of public property

6 — Accidental violation of another
      Humanity is a shared condition, his suffering is your own.

5 — Wanton destruction
      Are you a person or an animal?

4 — Theft

3 — Planned violation of another
      To be so cold is to reject the warmth of humanity.

2 — Casual violation of another
      Even wild animals know better.

1 — Genocide or any action that ends a community’s ability to grow and thrive]==],
				},
				["Path of Illumination"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 124


Path of Illumination


Aura: Normalcy. The Cainite walking the Road of Humanity strives to emulate her past state wherever possible. In matters of empathy and mutual understanding with mortals, her Aura will influence the outcome.


HIERARCHY OF SINS AGAINST ILLUMINATION

10 — Staying any place that is not furthering you along your journey

9 — Minor selfish acts
      Putting oneself first lets the Beast in.

8 — Injury to another
      Accidental or not, there is still blood on your hands.

7 — Any act that will prevent a Cainite from following the journey you have begun.

6 — Accidental violation of another
      Humanity is a shared condition, his suffering is your own.

5 — Wanton destruction
      Are you a person or an animal?

4 — Impassioned violation of another
      Passion behind violence is the whispering of the Beast.

3 — Planned violation of another
      To be so cold is to reject the warmth of humanity.

2 — Casual violation of another
      Even wild animals know better.

1 — Letting true darkness in, to squelch the light. Accepting Evil.]==],
				},
				["Path of Chivalry"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 126


Path of Chivalry


Aura: Command. Luminaries are self-possessed and confident in their right to rule. Others can feel their commanding presence like a chain placed around the neck.


HIERARCHY OF SINS AGAINST CHIVALRY

10 — Neglecting your duty for any reason
      Duty must come first.

9 — Dishonorable acts (deceit, murder, etc.)
      Your honor is the most important thing.

8 — Treating another with disrespect
      Respect must be given to earn it from others.

7 — Behaving in an unjust manner
      It is your duty to uphold justice.

6 — Failing to come to the aid of another
      It is your duty to protect the weak.

5 — Treating your superior with disrespect
      Superiors must be given the respect they are due.

4 — Placing personal desires over duty
      Selfish thoughts have no place in a Paladin’s heart.

3 — Failing to answer a challenge to your honor
      Honor and reputation are everything.

2 — Breaking your word
      Your word is your honor. If you have no honor, you have no worth.

1 — Breaking a sworn oath
      Oaths of fealty are what make civilized society.]==],
				},
				["Path of Devaraja"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 126


Path of Devaraja


Aura: Command. Luminaries are self-possessed and confident in their right to rule. Others can feel their commanding presence like a chain placed around the neck.


HIERARCHY OF SINS AGAINST DEVARAJA

10 — Failing to recognize the divine
      Your power comes from the divine will.

9 — Forgoing your duty
      Those who do not maintain responsibilities often lose them.

8 — Treating another with disrespect
      Respect must be given to earn it from others.

7 — Treating an inferior as an equal
      You are a god; you must not forget this.

6 — Placing personal desires over duty
      A leader must do what is best for the many, not the one.

5 — Failing to seize power when the chance arises
      You must prove to the divine that you deserve its blessing.

4 — Failing to answer a challenge to your honor.
      True gods smite their detractors.

3 — Killing without purpose
      It is your divine duty to protect your worshippers, not kill them.

2 — Breaking your word or oath
      Your word is your honor. If you have no honor, you have no worth.

1 — Giving into your Beast, such as frenzy
      If you cannot control yourself, how can you accept the divine?]==],
				},
				["Path of Daena"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 128


Path of Daena


Aura: Command. Luminaries are self-possessed and confident in their right to rule. Others can feel their commanding presence like a chain placed around the neck.


HIERARCHY OF SINS AGAINST DAENA

10 — Neglecting your duty for any reason
      Duty must come first.

9 — Breaking the law
      You must uphold the law at all costs.

8 — Treating another with disrespect
      Respect must be given to earn it from others.

7 — Behaving in an unjust manner
      It is your duty to uphold justice.

6 — Killing without purpose
      Displays of power should inspire fear or respect.

5 — Failing to come to the aid of another
      To gain power, you must first gather goodwill.

4 — Treating your superior with disrespect
      Superiors must be given the respect they are due.

3 — Failing to uphold the law
      It is your duty to uphold the law not matter the price.

2 — Breaking your word or oath
      Your word is your honor. If you have no honor, you have no worth.

1 — Giving into your Beast, such as frenzy
      If you cannot control yourself, how can you control others?]==],
				},
				["Path of Thorns"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 130


Path of Thorns


Aura: Carved and bleeding. A Bahari’s aura manifests as any other vampire’s might, though chunks and swirls may appear carved out of the whole. If one concentrates, they might think they see symbols in these shifting carvings, but can catch none of them. Further, the aura seems to bleed or drip, making the “carvings” appear more like wounds. Acts of creation and mentorship receive the character’s aura modifier.


HIERARCHY OF SINS AGAINST THORNS

10 — Feeding immediately when hungry
      There is a lesson in every denial, and there is control in self-denial.

9 — Joining any community of fools.

8 — Ignoring one of Lilith’s faces
      Wherever you go, the Dark Mother has left messages for you. Read their myths and show them where Lilith lives.

7 — Rejecting the suffering of others or dismissing it
      Teach whenever the opportunity presents itself, even if you think the lessons learned would be beneath you.

6 — Cruelty for its own sake
      As a teacher, you must craft your lessons. Petty abuses are beneath you. The pain you inflict must be divine.

5 — Accepting a student (formal or informal) the first time they come to you.

4 — Destroying a thinking being
      They can neither learn from you nor teach you if they have been destroyed.

3 — Not seeking out the teachings of Lilith
      Turn over the leaf, split the wood, and find her secrets wherever they hide.

2 — Putting the learning of another before your own.

1 — Shunning pain
      The harder it is, the more rewarding the growth.]==],
				},
				["Path of Veils"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 131


Path of Veils


Aura: Carved and bleeding. A Bahari’s aura manifests as any other vampire’s might, though chunks and swirls may appear carved out of the whole. If one concentrates, they might think they see symbols in these shifting carvings, but can catch none of them. Further, the aura seems to bleed or drip, making the “carvings” appear more like wounds. Acts of creation and mentorship receive the character’s aura modifier.


HIERARCHY OF SINS AGAINST VEILS

10 — Feeding immediately when hungry
      There is a lesson in every denial, and there is control in self-denial.

9 — Accepting and abiding any law of Caine or God.

8 — Failing to destroy the works of Noddist-liars.

7 — Rejecting the suffering of others or dismissing it
      Teach whenever the opportunity presents itself, even if you think the lessons learned would be beneath you.

6 — Cruelty for its own sake
      As a teacher, you must craft your lessons. Petty abuses are beneath you. The pain you inflict must be divine.

5 — Stealing great learning and claiming it as your own
      If you did not discover the wisdom yourself, you have no rights claiming it or authority based on it.

4 — Snuffing the spark of a candle that desires to burn brighter.

3 — Not seeking out the teachings of Lilith
      Turn over the leaf, split the wood, and find her secrets wherever they hide.

2 — Getting between someone and a valuable lesson
      Better to pull the stars from the heavens than to rob someone of moments of true gnosis.

1 — Shunning pain
      The harder it is, the more rewarding the growth.]==],
				},
				["Path of Making"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 131


Path of Making


Aura: Carved and bleeding. A Bahari’s aura manifests as any other vampire’s might, though chunks and swirls may appear carved out of the whole. If one concentrates, they might think they see symbols in these shifting carvings, but can catch none of them. Further, the aura seems to bleed or drip, making the “carvings” appear more like wounds. Acts of creation and mentorship receive the character’s aura modifier.


HIERARCHY OF SINS AGAINST MAKING

10 — Rejecting the advances of demons with seed in hand.

9 — Joining a system created by those with no wisdom
      Live outside their lies.

8 — Ignoring one of Lilith’s faces
      Wherever you go, the Dark Mother has left messages for you. Read their myths and show them where Lilith lives.

7 — Abandoning a thing because it is ugly or frightening.

6 — Cruelty for its own sake
      As a teacher, you must craft your lessons. Petty abuses are beneath you. The pain you inflict must be divine.

5 — Not taking a secret of making and creating from savages who don’t know the divine purpose behind it.

4 — Destroying a thinking being
      They can neither learn from you nor teach you if they have been destroyed.

3 — Not seeking out the teachings of Lilith
      Turn over the leaf, split the wood, and find her secrets wherever they hide.

2 — Getting between someone and a valuable lesson
      Better to pull the stars from the heavens than to rob someone of moments of true gnosis.

1 — Rejecting the advances of angels with seed in hand.]==],
				},
				["Path of Pleasure"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 135


Path of Pleasure


Aura: Temptation. The Sinners are free and their Road full of promise, and they are adept at recognizing the desires of others. Their aura modifier affects rolls to cajole and entice.


HIERARCHY OF SINS AGAINST PLEASURE

10 — Being shamed by your actions
      Shame is disapproval in the eyes of others; your actions can only please yourself.

9 — Failing to indulge your desires
      Satiation keeps the Beast at bay.

8 — Failing to ride the wave of frenzy
      The red rages are but another pleasure to experience.

7 — Any display of modesty
      Modesty is morality imposed from without. Never submit to it.

6 — Putting the needs of others ahead of your own interests
      Your desires come before their need.

5 — Swearing an oath
      A wild heart must never be chained.

4 — Associating with those who bring you no pleasure
      The Beast rages when denied; never give license to its fury.

3 — Refusing to feed or kill when necessary
      These are your greatest and purest joys.

2 — Encouraging virtue or agents of virtue
      Why exert effort to aid those who would chain you?

1 — Refusing to act in your own best interests
      Your desires are all that truly matters.]==],
				},
				["Path of the Devil"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 135


Path of the Devil


Aura: Temptation. The Sinners are free and their Road full of promise, and they are adept at recognizing the desires of others. Their aura modifier affects rolls to cajole and entice.


HIERARCHY OF SINS AGAINST REBELLION

10 — Acknowledging the laws of God or Man
      Never give credence to those who would enslave others.

9 — Failing to indulge a new desire
      Passion is the fire of the soul.

8 — Failing to ride the wave of frenzy
      The Beast may only be understood after struggle.

7 — Refusing to aid a lost soul in need
      The weak cannot understand their nature, and must be taught by the strong.

6 — Refusing a pleasure that injures none
      Seeking to pleasure yourself is the fondest pursuit.

5 — Swearing an oath
      Forced servitude cannot be helped, and is to be pitied; self-enforced servitude is hideous, and is to be resisted.

4 — Refusing to act against those who choose to bind you
      Punish those who attempt to control you.

3 — Refusing to feed or kill when necessary
      Never feel shame for doing what must be done.

2 — Pursuing material gain at the expense of higher concerns
      Enrich your soul before you fill your coffers.

1 — Encouraging false virtue or agents of false virtue
      Constrictions of laws enslave the mind and strangle the soul.]==],
				},
				["Path of Screams"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 136


Path of Screams


Aura: Temptation. The Sinners are free and their Road full of promise, and they are adept at recognizing the desires of others. Their aura modifier affects rolls to cajole and entice.


HIERARCHY OF SINS AGAINST DAMNATION

10 — Acknowledging any laws but that of Hell
      Divinity and mundanity have no meaning for the Damned.

9 — Failing to indulge your desires
      Pleasure strengthens you, which strengthens your masters.

8 — Failing to ride the wave of frenzy
      The Beast is the clarion call of your soul.

7 — Refusing to feed or kill when necessary
      Beautiful is the blood that darkens the soil.

6 — Avoiding injury to others for any reason
      Blood spilled is your gift to the world, your greatest pleasure.

5 — Any display of mercy or pity
      Mercy is for the weak, and Damnation makes you strong.

4 — Failing to act on behalf of Hell
      You serve Hell, even when it does not serve you.

3 — Any altruistic behavior
      You owe others nothing.

2 — Acting against the minions of Hell
      We are all as drones in the hive of the Pit.

1 — Encouraging virtue or agents of virtue
      Nothing pure may withstand you, even the purity of Sin.]==],
				},
				["Path of Watchful Gods"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 137


Path of Watchful Gods


Aura: Temptation. The Sinners are free and their Road full of promise, and they are adept at recognizing the desires of others. Their aura modifier affects rolls to cajole and entice.


HIERARCHY OF SINS AGAINST THE WATCHFUL GODS

10 — Failing to make regular sacrifices
      Regular sacrifices give the gods strength.

9 — Lying
      Do not dishonor yourself in the eyes of the gods with false words.

8 — Offending the gods or spirits with violence
      Do not disrespect the spirits with violence, for they are quick to take offense and their memory is long.

7 — Failing to act honorably
      The gods reward honor and punish dishonor.

6 — Stealing from offerings or sacrifices
      Give the gods the first fruits of your labor and do not grudge them their portion.

5 — Not honoring priests
      Priests are the servants of order and balance favored by the gods.

4 — Killing a sacred animal
      Honor that which the gods have decreed sacred.

3 — Defiling sacred places
      Defiling a temple is like cursing the gods themselves.

2 — Damaging the image of the gods
      One should strive always to honor the gods in thought and deed.

1 — Reviling a god or the gods
      The gods are the source of all life and goodness.]==],
				},
				-- <<< ROAD_DESC_END
};
