-- Road/Path descriptions, the [pt] half (SPEC I141, I21, V210, V409 / T931).
--
-- One entry per item of PICKER_LIST["road"], keyed by the value the sheet SAVES, byte for
-- byte (SPEC V24, I142e): "Path of Humanity", not "Humanity". Both halves carry the SAME
-- 55 keys - a name in one and not the other reddens V210 in both directions.
--
-- FOUR blocks, not three (SPEC I141a): the third block of I21 splits in two, into the AURA
-- and the hierarchy of sins. Separator is the same two blank lines the other ten modules
-- use (SPEC Q56). The book title does not translate; only p./pag. does (SPEC I100e), and
-- neither does the name in block 2 - it is the key.
--
-- The aura name is the string BEARING already shows on the ROAD line of the Main tab, read
-- from WoD20th.lfm at generation time (SPEC I141b): there is no second identity for it, and
-- V409(c) measures exactly that. The pt spelling is the sheet PT map, same single owner.
--
-- A Path that inherits its table carries the mother table with its own levels SUBSTITUTED,
-- BAKED into the string (SPEC I141e, I141f): the levels it does not name keep the mother
-- text verbatim, so nothing at runtime needs to know who is mother to whom.
--
-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24).
-- GENERATED by research/gen_road_desc.ps1 from the .tsv in research/. Do not hand-edit:
-- fix the .tsv and run it again.

return {
				-- >>> ROAD_DESC_BEGIN (generated - SPEC T931)
				["Path of Humanity"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 310


Path of Humanity


Aura: Normalidade. Vampiros em Humanidade têm uma aura de normalidade; a conexão humana que esses vampiros mantêm impede que pareçam estranhos e aterrorizantes aos mortais. O modificador de aura afeta testes Sociais para parecer normal e conquistar simpatia.


Hierarquia do Pecado — Humanidade

10 — Pensamentos egoístas

9 — Pequenos atos egoístas

8 — Ferir alguém (por acidente ou não)

7 — Furto

6 — Violação acidental (drenar uma vítima até o fim por inanição)

5 — Dano material intencional

4 — Violação passional (homicídio culposo, matar uma vítima em frenesi)

3 — Violação premeditada (assassinato deliberado, exsanguinação saboreada)

2 — Violação casual (matar sem pensar, alimentar-se além da saciedade)

1 — Perversão absoluta ou atos hediondos]==],
				},
				["The Path of Blood"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 316


The Path of Blood


Aura: Determinação. Os seguidores da Trilha do Sangue conhecem a seriedade de sua tarefa e são incrivelmente dedicados a ela. O modificador de aura deles afeta testes de Força de Vontade.


Hierarquia de Pecados da Trilha do Sangue

10 — Matar um mortal para se sustentar
      O sangue humano nutre o corpo, mas o assassinato dos menores é veneno para a alma.

9 — Quebrar a palavra de honra dada a um irmão de Clã
      A solidariedade é importante para a causa sagrada dos Assamitas.

8 — Recusar-se a oferecer a um não-Assamita a chance de se converter
      Os filhos de Khayyin são amaldiçoados e precisam ser salvos.

7 — Deixar de destruir um Membro impenitente de fora do Clã
      Quem não aceita os ensinamentos de Haqim perde o direito à sua não-vida.

6 — Sucumbir ao frenesi
      Haqim ensina a ascensão, não a indulgência.

5 — Deixar de perseguir o saber sobre Khayyin
      Para se opor aos inimigos com êxito, é preciso aprender tudo sobre eles.

4 — Deixar de exigir sangue como pagamento
      Outros membros do Clã podem se beneficiar dessa vitae, por mais diluída que esteja.

3 — Recusar ajuda a um membro mais avançado da Trilha
      Agir por egoísmo é cair nas armadilhas do peão de Khayyin.

2 — Deixar de pagar o dízimo de sangue
      Haqim decretou isto como primordial para a causa de seus filhos.

1 — Agir contra outro Assamita
      Isto é traição à Trilha e ao Clã.]==],
				},
				["The Path of the Bones"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 318


The Path of the Bones


Aura: Silêncio. Os Coveiros, acostumados como são a longas horas de estudo silencioso e contemplação do túmulo, irradiam a quietude da morte. O modificador de aura se aplica a testes que envolvam Furtividade e tentativas de passar despercebido.


Hierarquia de Pecados da Trilha dos Ossos

10 — Demonstrar medo da morte
      O medo impede o aprendizado.

9 — Deixar de estudar uma ocorrência de morte
      Recusar-se a aprender é recusar-se a compreender.

8 — Matar acidentalmente
      Não há oportunidade de obter discernimento.

7 — Adiar a alimentação quando faminto
      Negar a si mesmo não serve a propósito maior nenhum.

6 — Sucumbir ao frenesi
      A Besta é irracional, e a emoção pouco contribui para o entendimento.

5 — Recusar-se a matar quando surge a oportunidade
      A experimentação comprova a teoria, e sem prova não há conclusão.

4 — Tomar uma decisão pela emoção em vez da lógica
      Vampiros estão mortos; suas emoções também.

3 — Incomodar-se em benefício de outro
      A morte é inevitável; que sentido tem aliviar o desconforto de um condenado?

2 — Impedir uma morte sem necessidade
      Não se deve impedir o ciclo, e sim aprender com ele.

1 — Impedir ativamente uma morte
      Laços emocionais assim convêm a humanos, não a Membros.]==],
				},
				["The Path of Caine"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 320


The Path of Caine


Aura: Fé. A retidão do Cainita é evidente a todos. O modificador de aura afeta todos os testes que dependam da imagem do vampiro como Membro devoto e estudioso dos ensinamentos de Caim.


Hierarquia de Pecados da Trilha de Caim

10 — Deixar de pesquisar ou estudar todas as noites, sejam quais forem as circunstâncias
      A busca pela verdade exige dedicação.

9 — Deixar de instruir outros vampiros na Trilha de Caim
      Todo vampiro precisa ter a chance de explorar seu potencial.

8 — Fazer amizade com mortais ou conviver com eles
      Caim foi separado dos mortais, como todo vampiro deveria ser.

7 — Faltar com respeito a outros estudiosos de Caim
      Todos os Filhos de Caim merecem o respeito devido à sua herança, desde que se esforcem para compreender a si mesmos.

6 — Deixar de cavalgar a onda em frenesi
      Dirija a Besta; não seja dirigido por ela.

5 — Sucumbir ao Rötschreck
      Domine seu medo. O terror é para seres menores.

4 — Deixar de diablerizar um vampiro "humano"
      Quem não explora o próprio potencial perde esse potencial.

3 — Deixar de testar regularmente os limites de habilidades e Disciplinas
      Desenvolva suas capacidades até o limite para discernir sua verdadeira natureza.

2 — Deixar de buscar o saber sobre o vampirismo quando surge a oportunidade
      Cada fragmento de conhecimento acrescenta uma peça ao enigma da existência morta-viva.

1 — Negar as necessidades vampíricas (recusando-se a se alimentar, demonstrando compaixão ou deixando de aprender sobre as próprias capacidades vampíricas)
      Para ser vampiro, é preciso satisfazer as necessidades de um vampiro.]==],
				},
				["The Path of Cathari"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 323


The Path of Cathari


Aura: Sedução. Os Cátaros são a tentação encarnada, e têm um dom estranho para conhecer os desejos alheios. O modificador de aura afeta testes para tentar e seduzir os outros.


Hierarquia de Pecados da Trilha dos Cátaros

10 — Exercer moderação
      O propósito de cada um é o excesso, não a moderação.

9 — Demonstrar confiança
      Use ou seja usado.

8 — Deixar de transmitir a Maldição aos apaixonadamente perversos ou virtuosos
      Os depravados servem melhor ao mal como vampiros; os virtuosos podem ser vencidos pela Maldição.

7 — Deixar de cavalgar a onda em frenesi
      Tanto a Besta quanto o eu superior precisam ser satisfeitos.

6 — Agir contra outro Albigense
      Quem partilha um propósito deve cumpri-lo, não brigar entre si.

5 — Matar por paixão
      O assassinato não alcança fim maior; homens mortos não podem manchar a própria alma.

4 — Sacrificar a satisfação pela conveniência alheia
      Promova os prazeres da carne, não conquistas altruístas.

3 — Abster-se da indulgência
      O mundo material é lugar para a gratificação da carne.

2 — Matar arbitrariamente
      Matar um mortal impede que ele conquiste a própria condenação.

1 — Incentivar outros a exercer moderação
      Vampiros são criaturas do mal; o propósito do vampiro é corromper, não salvar.]==],
				},
				["The Path of the Feral Heart"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 324


The Path of the Feral Heart


Aura: Ameaça. Quem está diante de uma Besta sabe que ela é uma verdadeira caçadora, do mesmo modo que o cervo sabe ao encarar o lobo. O modificador de aura se aplica a testes voltados a aterrorizar ou intimidar um oponente.


Hierarquia de Pecados da Trilha do Coração Selvagem

10 — Caçar com meios que não sejam seus próprios poderes vampíricos
      O caçador perfeito não precisa de ferramentas.

9 — Envolver-se em política
      Disputas políticas não rendem sustento.

8 — Permanecer diante do fogo ou da luz do sol, exceto para matar um inimigo
      Não há sentido em cortejar a Morte Final.

7 — Agir com crueldade excessiva
      A morte é natural; alimentar-se é natural. Tortura e crueldade não são.

6 — Deixar de caçar quando faminto
      O propósito do vampiro é alimentar-se.

5 — Deixar de apoiar sua matilha ou seus aliados
      Ampare sua família e ela o amparará.

4 — Matar sem necessidade
      De uma vítima morta não se pode beber de novo.

3 — Deixar de seguir os próprios instintos
      O instinto é a base da natureza predatória.

2 — Matar uma criatura por outro motivo que não a sobrevivência
      O propósito de uma morte é o sustento.

1 — Recusar-se a matar para sobreviver
      Vampiros são caçadores; todo o resto é caça.]==],
				},
				["The Path of Honorable Accord"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 326


The Path of Honorable Accord


Aura: Devoção. Os Cavaleiros mantêm sua palavra e são muito difíceis de desviar de seu dever. O modificador de aura afeta testes para resistir a tentativas de manipulá-los ou forçá-los a agir contra o propósito que assumiram.


Hierarquia de Pecados da Trilha do Acordo Honrado

10 — Deixar de sustentar todos os preceitos do seu grupo
      O verdadeiro dever para com uma causa exige caráter impecável.

9 — Deixar de oferecer hospitalidade aos seus aliados
      Hospitalidade e generosidade são a riqueza da alma.

8 — Associar-se aos desonrados
      Sirva de exemplo, mas não se deixe arrastar para a mesquinhez.

7 — Deixar de participar dos rituais do seu grupo
      Tradição e ritual são partes importantes da herança.

6 — Desobedecer ao seu líder
      A lealdade é a pedra angular da hierarquia.

5 — Deixar de proteger seus aliados
      Defenda quem é digno da sua estima.

4 — Colocar interesses pessoais acima do dever
      O dever é o propósito do vampiro.

3 — Demonstrar covardia
      A honra está em lutar por uma causa, não em fugir dela.

2 — Matar sem motivo
      A vida e a morte cabem a Deus decretar.

1 — Quebrar sua palavra ou seu juramento; deixar de honrar um acordo
      Quebrar o próprio juramento é ficar sem a honra que define a existência.]==],
				},
				["The Path of Lilith"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 329


The Path of Lilith


Aura: Tribulação. Os Bahari veem a iluminação pela dor e pelo conflito, e aprendem a transformar a dor em vantagem. O modificador de aura afeta testes atingidos por suas próprias penalidades de ferimento.


Hierarquia de Pecados da Trilha de Lilith

10 — Alimentar-se assim que sente fome
      A privação e a fome ensinaram Lilith a sobreviver.

9 — Buscar riqueza ou poder temporal
      A verdadeira riqueza vem de dentro, não do dinheiro ou da influência.

8 — Não corrigir os erros alheios a respeito de Caim e Lilith
      Caim foi um assassino, um traidor e um tolo que não merece reverência.

7 — Sentir remorso por causar dor a alguém
      A dor e o sofrimento ajudam os outros a aprender e crescer.

6 — Deixar de participar de um ritual Bahari
      Os rituais transmitidos ao longo do tempo guardam pistas do despertar.

5 — Temer a morte
      A morte é apenas uma mudança inevitável para uma nova forma de existência.

4 — Matar um ser vivo ou morto-vivo
      A morte nega a alguém a chance de transcender.

3 — Não buscar os ensinamentos de Lilith
      Lilith escondeu suas obras em muitos lugares; é preciso encontrá-las.

2 — Deixar de dispensar dor e angústia
      Seja mestre por meio da dor.

1 — Fugir da dor
      Só pela dor renascemos. Fugir da dor é abraçar a ignorância.]==],
				},
				["The Path of Metamorphosis"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 331


The Path of Metamorphosis


Aura: Desumanidade. Os Metamorfistas trabalham sem descanso para se tornar algo que não seja humano. Modificadores de aura se aplicam a Intimidação, bem como a qualquer teste de Manipulação que possa ser favorecido por assustar o alvo.


Hierarquia de Pecados da Trilha da Metamorfose

10 — Adiar a alimentação quando faminto
      A fome causa distração.

9 — Entregar-se ao prazer
      O hedonismo desvia de fins mais altos.

8 — Pedir conhecimento a outrem
      As lições da Metamorfose são segredos que precisam ser descobertos, não copiados.

7 — Partilhar conhecimento com outrem
      O conhecimento precisa ser aprendido, não simplesmente ilustrado.

6 — Recusar-se a matar quando disso se pode obter conhecimento
      Antes de transcender a morte, o Metamorfista precisa compreendê-la.

5 — Deixar de cavalgar um frenesi
      Um Membro precisa conhecer a Besta para transcendê-la.

4 — Levar em conta as necessidades alheias
      Quem não se dá ao trabalho de alcançar a Metamorfose está abaixo da sua atenção.

3 — Deixar de experimentar, mesmo com risco para si
      A Trilha só pode ser compreendida pela pesquisa empírica.

2 — Negligenciar a alteração do próprio corpo
      A mudança física precisa ser alcançada antes de qualquer metamorfose mais significativa.

1 — Demonstrar compaixão pelos outros
      O destino alheio arrasta você para a involução, não para a transcendência.]==],
				},
				["The Path of Night"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 332


The Path of Night


Aura: Escuridão. Os Niilistas exalam um leve ar de escuridão interior, levando quem está por perto a remoer seus medos e pensamentos mais sombrios. O modificador de aura deles se aplica a qualquer tentativa de trazer à tona a escuridão interior de uma vítima, como arrancar segredos sujos de um político respeitado ou convencer uma santa a romper seu voto de castidade.


Hierarquia de Pecados da Trilha da Noite

10 — Matar um mortal por alimento
      Mortais mortos não sentem pavor.

9 — Agir no interesse de outro
      Não há tempo para cumprir agendas mesquinhas.

8 — Deixar de ser inovador nas próprias depredações
      A familiaridade com seus atos vis gera desprezo por eles nos outros, e logo eles podem deixar de chocar.

7 — Pedir ajuda a outrem
      Quem não consegue prover a si mesmo cumpre mal seus fins.

6 — Matar acidentalmente
      Deus fez dos Membros horrores, não assassinos.

5 — Curvar-se à vontade de outro Membro
      Os jogos da Jyhad são desvios do verdadeiro propósito dos Condenados.

4 — Matar intencionalmente ou por paixão
      A morte não serve a ninguém; apenas priva você de uma vítima.

3 — Ajudar outrem
      A compaixão não tem lugar no coração morto-vivo de um vampiro.

2 — Aceitar a alegação de superioridade de outro
      Todos os Membros são iguais sob o plano de Deus.

1 — Arrepender-se do próprio comportamento
      O propósito do Membro é causar arrependimento, não praticá-lo.]==],
				},
				["The Path of Paradox"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 335


The Path of Paradox


Aura: Confiança. Os Shilmulo acreditam estar exatamente no lugar e no tempo em que deveriam estar, fazendo o que deveriam fazer — e isso transparece. O modificador de aura se aplica a tentativas de manipular ou liderar os outros.


Hierarquia de Pecados da Trilha do Paradoxo

10 — Abraçar uma mulher
      Mulheres devem ser portadoras da vida, não da morte.

9 — Abraçar fora da jati
      A maioria dos outros não compreende a profundidade da filosofia do Paradoxo.

8 — Destruir outro Shilmulo
      A caridade não começa em casa, como se costuma crer.

7 — Matar um mortal para se sustentar
      A morte rouba de uma pessoa a capacidade de cumprir seu svadharma.

6 — Deixar de destruir um vampiro de outra Trilha
      Quem não enxerga o caminho verdadeiro deve ser devolvido a um papel produtivo no ciclo.

5 — Matar um mortal por motivos que não a sobrevivência
      Uma pessoa pode ainda não ter cumprido seu svadharma, e impedir isso é anátema.

4 — Deixar de auxiliar o svadharma de outrem
      Os deuses estabeleceram isto como o propósito do Shilmulo.

3 — Permitir que assuntos da sua Seita tenham precedência sobre o seu dharma
      Sua lealdade deve ser aos deuses, não aos seus companheiros.

2 — Tornar-se preso pelo vínculo de sangue
      Nunca se pode destruir o próprio regente, e é este o propósito inteiro desta Trilha.

1 — Abraçar sem necessidade ou por desejo pessoal
      É preciso devolver os outros ao ciclo, não retirá-los dele.]==],
				},
				["The Path of Power and the Inner Voice"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 336


The Path of Power and the Inner Voice


Aura: Comando. Os Unificadores estão destinados ao poder, e sabem disso. Quem está por perto sente sua presença imperiosa. O modificador de aura deles afeta testes para comandar ou liderar os outros.


Hierarquia de Pecados da Trilha do Poder e da Voz Interior

10 — Negar responsabilidade pelos próprios atos
      Abandonar a responsabilidade é falhar em liderar como se deve.

9 — Tratar mal seus subordinados
      Recompense a competência como incentivo, mas faça-o com parcimônia.

8 — Deixar de respeitar seus superiores
      Dê o respeito devido, para que possa aprender algo em troca.

7 — Ajudar os outros quando não é vantajoso para você
      Sempre obtenha algo de suas ações.

6 — Aceitar a derrota
      Vença, ou morra.

5 — Deixar de matar quando é do seu interesse
      Não hesite em eliminar quem se puser contra você.

4 — Submeter-se ao erro alheio
      Esteja certo e será justificado. Siga um tolo e sofrerá por isso.

3 — Não usar as ferramentas mais eficazes de controle
      O poder precisa ser tomado. Seja de punho de ferro e resoluto.

2 — Não punir o fracasso
      O fracasso só instrui quando usado como exemplo negativo.

1 — Recusar a oportunidade de obter poder
      O poder pessoal é o meio para todos os fins.]==],
				},
				["The Path of Typhon"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 338


The Path of Typhon


Aura: Devoção. Os Teofidianos fazem tudo de olho em como podem servir melhor a Set. O modificador de aura ajuda em tentativas de ganhar convertidos e em testes para resistir a poderes baseados em outras fés (como a Fé Verdadeira — veja p. 372).


Hierarquia de Pecados da Trilha de Tífon

10 — Buscar as próprias indulgências em vez das de outrem
      O deslize para o vício é ferramenta, não recreação.

9 — Recusar ajuda a outro seguidor da Trilha
      Equipes trabalham mais eficientemente que indivíduos para erguer Set.

8 — Deixar de destruir um vampiro em Golconda
      Quem transcendeu os próprios desejos não pode ser dominado.

7 — Deixar de observar o ritual religioso Setita
      Você não deve negar a Set o que lhe é devido.

6 — Deixar de solapar a ordem social vigente em favor dos Setitas
      Os outros Membros não têm propósito ou estão iludidos, e essa indolência atrasa o retorno de Set.

5 — Deixar de fazer o que for preciso para corromper outrem
      Quanto mais indivíduos em dívida com os Setitas, melhor.

4 — Deixar de buscar o conhecimento arcano
      Os mistérios da ressurreição de Set podem estar escondidos em qualquer lugar.

3 — Obstruir os esforços de outro Setita
      As fileiras dos justos não são lugar para disputas mesquinhas de poder.

2 — Deixar de tirar proveito da fraqueza alheia
      A compaixão não tem lugar nos planos maiores de Set.

1 — Recusar-se a ajudar na ressurreição de Set
      Isso é coisa de descrentes.]==],
				},
				["The Path of the Hive"] = {
					pt = [==[The Black Hand: A Guide to the Tal’Mahe’Ra, pág. 53


The Path of the Hive


Aura: Justiça. Os Abelenos carregam uma atmosfera de retribuição divina. O modificador de aura deles afeta testes para convencer os outros da retidão de seus atos.


Via Hyron: Hierarquia de Pecados da Trilha da Colmeia

10 — Deixar de cavalgar a onda em frenesi
      O coração da Besta predileta de Abel lhe foi dado pelo Altíssimo. A voz dela é sagrada, e desatar sua divindade protege os anjos dele do assalto.

9 — Deixar de estancar a influência da religião institucionalizada
      Ao longo da história, o enganador, Lúcifer, torceu a fé e vestiu a propagação da ignorância, do fanatismo, da ilusão, da ganância e do caos com a hipocrisia da religião. É dever dos Molochim pastorear o rebanho de Caim.

8 — Alimentar-se dos filhos de Sete
      Reclame o sangue de Abel em vingança dos construtores, os filhos de Caim. Quem vive em harmonia com a Criação na natureza não está sujeito à retribuição do Altíssimo.

7 — Não buscar ativamente o conhecimento seguro da feitiçaria e do demoníaco
      Conhece o teu inimigo. Ignorância é escuridão, e a escuridão é onde o infernal se esconde. A feitiçaria de sangue é o sacramento no arsenal contra a atrocidade.

6 — Recusar a oportunidade de converter aqueles que buscam redenção
      Quanto maior a colmeia, maior o enxame. Quem encarou o infernal é uma vespa sem Ninho à espera de salvação. Prenda-os pelo sangue e liberte-os quando encontrarem abrigo

5 — Recusar-se a cantar uma canção de ninar aos adormecidos
      Os sonhos dos adormecidos se alimentam da devastação e do estrago lançados sobre a Criação. Sem combustível, os adormecidos desviam a atenção do sonho e buscam despertar.

4 — Não ser seletivo numa canção de ninar
      Destruição sem rumo, que não sirva de adubo para uma Criação nova brotar, não é melhor que um adormecido desperto. Pastoreie a Criação pela aplicação estratégica da violência e do sofrimento.

3 — Deixar de escravizar ou extinguir o demoníaco
      O Altíssimo condenou Lúcifer e seus filhos; a existência deles está perdida.

2 — Deixar de purgar o infernal
      Cada vez que o nome de um adormecido é pronunciado, e cada alma perdida para o demoníaco, desperta um pouco os adormecidos do sonho.

1 — Deixar de formar Ninho
      A independência é o portão do infernal; Lúcifer ataca primeiro quem está sozinho. A união é a força da colmeia, o isolamento enfraquece o enxame. Ao deixar um Ninho, encontre outro.]==],
				},
				["The Path of the Scorched Heart"] = {
					pt = [==[The Black Hand: A Guide to the Tal’Mahe’Ra, pág. 55


The Path of the Scorched Heart


Aura: Intelecto. Os Implacáveis não se deixam abalar facilmente por apelos à emoção. O modificador de aura deles afeta testes que pretendam influenciá-los por Atributos Sociais.


Hierarquia de Pecados da Trilha do Coração Chamuscado

10 — Deixar de adquirir conhecimento que esteja disponível com segurança e facilidade
      O conhecimento é a nascente da verdade; nunca se sabe o bastante.

9 — Empenhar-se em qualquer ação sem propósito
      Não desperdice esforço no que não o engrandece.

8 — Sacrificar quando o ganho é menor
      Uma vitória que custa mais do que rende não traz benefício algum.

7 — Depender de outros
      Suas ações são as únicas que você pode prever com certeza absoluta.

6 — Fazer suposições
      Sem clareza, o erro se esconde na névoa do dado não examinado.

5 — Agir precipitadamente
      Não se aprende com a ação indiscriminada. Observe, pense, calcule, pondere, e só então aja.

4 — Falar falsamente
      A verdade é uma bala. Sem confiança, a verdade não tem arma.

3 — Cair em frenesi ou Rötschreck
      O descuido é perigoso. Você não controla as ameaças que deixa de ver quando não está objetivo. Quem não domina a si mesmo não tem defesa contra quem queira dominá-lo.

2 — Tomar decisões com base na emoção
      Os impulsos da emoção são palavras da Besta, não suas. Purgue-os.

1 — Reconhecer as próprias emoções
      A Besta sente. Você não. Negue a Besta e ela definha.]==],
				},
				["The Path of Self-Focus"] = {
					pt = [==[The Black Hand: A Guide to the Tal’Mahe’Ra, pág. 58


The Path of Self-Focus


Aura: Equilíbrio. Quem está perto de um Internalista se acalma com sua presença pacífica. O modificador de aura deles afeta testes para evitar confronto ou acalmar os outros.


Hierarquia de Pecados da Trilha do Foco Interior

10 — Aceitar tudo
      Uma tigela cheia até a borda transborda.

9 — Não aceitar nada
      Afie demais a faca e ela quebra.

8 — Preguiça
      Uma formiga em movimento faz mais que um elefante adormecido.

7 — Interferir no universo
      Para liderar, caminhe atrás.

6 — Conter a Besta
      A luta gera conflito e o tira do alinhamento consigo mesmo.

5 — Deixar de tratar os outros como gostaria de ser tratado
      Até um mestre precisa ser questionado.

4 — Permitir que o universo interfira em você
      Só você controla suas ações.

3 — Excesso de confiança
      Para conhecer a força, domine a fraqueza.

2 — Não rejeitar nada
      A água é mais suave e mais flexível que qualquer coisa, e ainda assim nada lhe resiste.

1 — Rejeitar tudo
      Quem não muda de direção sempre chega aonde estava indo.]==],
				},
				["The Path of Asakku"] = {
					pt = [==[The Black Hand: A Guide to the Tal’Mahe’Ra, pág. 115


The Path of Asakku


Aura: Sobrenatural. Os seguidores adotam um comportamento alienígena. A maioria usa Vicissitude constantemente. Mesmo quando tentam se misturar, todos exceto os mais espertos cometem erros incomuns, marcando-se como seres pouco familiarizados com o mundo humano. Ignoram convenções sociais e encaram direções estranhas. O modificador de aura de um Asakku se aplica a testes de Prontidão e Ocultismo para sentir energias sobrenaturais.


Hierarquia de Pecados contra os Asakku

10 — Usar seu antigo nome ou atender por ele
      Você não é um vampiro. Você é um fio numa teia de poder.

9 — Recusar-se a usar Vicissitude a cada oportunidade
      Torne-se o seu poder.

8 — Deixar de ampliar seu domínio de Vicissitude ao máximo possível
      Você precisa aplicar todo o seu esforço em identificar-se com o Vigia interior.

7 — Deixar de cometer Amaranto ou de converter um membro do Clã que pratique Vicissitude
      Retome o poder que eles roubaram.

6 — Recusar-se a ensinar Vicissitude
      Deixe que o Vigia enxergue por mil olhos.

5 — Permitir que inimigos descubram seu verdadeiro refúgio
      Sua toca pertence ao Vigia.

4 — Trair outro dos Corrompidos
      Emanamos da mesma escuridão e precisamos abrir caminho até o mundo juntos.

3 — Permitir que inimigos descubram sua verdadeira natureza
      Que os bastardos de Caim esqueçam a origem de seus dons até que estejamos prontos para reclamá-los abertamente.

2 — Recusar-se a converter à Trilha aqueles sob o vínculo de sangue
      O Vigia exige seguidores para manifestar-se com mais força.

1 — Deixar de usar Vicissitude todas as noites, exceto em torpor
      A sombra que murmura dentro de você precisa falar]==],
				},
				["The Path of Entelechy"] = {
					pt = [==[Lore of the Clans, pág. 51


The Path of Entelechy


Aura: Estoicismo. Os Filósofos trazem à morte-viva um pragmatismo que lhes permite manter a equanimidade diante das provocações infantis e das farpas cruéis de Membros menos iluminados. O modificador de aura soma em todos os testes para resistir ao frenesi quando provocado por insultos ou por outras ações deliberadamente provocativas. Ele não afeta testes de frenesi disparados por outras formas de estímulo indutor de fúria.


HIERARQUIA DE PECADOS DA TRILHA DA ENTELEQUIA

10 — Pensamento mal definido ou ocioso
      Só a rigidez de pensamento permite o domínio sobre a Besta.

9 — Recusar-se a intervir quando outro vampiro corre risco de degeneração
      Ao ajudar os outros a controlar seus impulsos, você aprende mais sobre como controlar os seus.

8 — Agir por impulso
      Agir sem pensamento cuidadoso leva à perda de controle.

7 — Furto, roubo ou vandalismo
      Agir contra os outros é o caminho que se afasta da Humanidade.

6 — Recusar-se a defender um princípio moral por medo ou covardia
      É só pela defesa da moral que se pode compreendê-la.

5 — Causar dano deliberado a um mortal, inclusive alimentação violenta e não consentida
      Se você fere o corpo de um mortal, fere também a própria espiritualidade.

4 — Auxiliar um seguidor de outra Trilha que não respeite a humanidade
      Auxiliar quem rejeita a humanidade (e a Humanidade) é tão ruim quanto rejeitá-la você mesmo.

3 — Sucumbir ao frenesi quando uma conduta sábia poderia tê-lo evitado
      Não dê à Besta a chance de florescer.

2 — Deixar impune qualquer crime violento contra um inocente
      Se você permite que outros sejam feridos sem punição, é como se você mesmo tivesse ferido.

1 — O assassinato de inocentes
      Tirar uma vida é a pior perda de controle que se pode cometer.]==],
				},
				["The Path of Ecstasy"] = {
					pt = [==[Lore of the Clans, pág. 70


The Path of Ecstasy


Aura: Arrebatamento. Os Extáticos sabem usar sensações e paixões terrenas para transcender o mundano. O modificador de aura deles afeta testes para excitar respostas emocionais extremas e transformadoras em si mesmos e nos outros.


Hierarquia de Pecados da Trilha do Êxtase

10 — Deixar um inocente viver
      Uma alma que não se dispõe a tocar o além pela sensação deve ser enviada por via mais direta.

9 — Não se afundar em decadência absoluta
      Sempre, sempre afogue a Besta.

8 — Recusar-se a quebrar um tabu
      Transgredir qualquer fronteira sagrada deteriora o paradigma dos Éons.

7 — Deixar viver, sem bom motivo, um infector de impureza (padre, freira etc.)
      A menos que possam ser comprometidos, os hipócritas continuarão servindo ao propósito dos Éons.

6 — Deixar de criar um momento belo
      Num mundo sufocado de niilismo, é pecado não abrir uma janela para o divino quando a inspiração chega.

5 — Não tentar corromper um inocente
      Liberte a ovelha acorrentada quando puder.

4 — Não usar ao menos uma droga regularmente
      Uma mente maleável está mais aberta ao supremo.

3 — Conter seus impulsos naturais sem necessidade
      A compulsão da repressão é um artefato inútil, implantado pelos Éons, e precisa ser extirpada.

2 — Recusar-se a subverter as correntes dos Éons
      Sem nosso propósito glorioso, não passamos de hedonistas reles.

1 — Destruir algo de beleza, mesmo um inocente
      Recusamo-nos a tornar o mundo menos interessante.]==],
				},
				["The Path of the Warrior"] = {
					pt = [==[Lore of the Clans, pág. 72


The Path of the Warrior


Aura: Fúria. Os Iracundos ardem em fúria divina. O modificador de aura deles se aplica a intimidar os outros (testes de Intimidação) e até as próprias Bestas (testes para resistir tanto ao frenesi quanto ao Rötschreck).


Hierarquia de Pecados da Trilha do Guerreiro

10 — Não se submeter às torturas mais dolorosas
      Sua carne precisa ser purificada para seu propósito sagrado.

9 — Falhar em qualquer prova posta diante de você, física ou mental
      O fracasso é indigno do Deus Sombrio.

8 — Não desenvolver seu corpo até o máximo do potencial
      Você é uma arma empunhada por Set, e precisa estar afiado.

7 — Gastar pontos de sangue para curar ferimentos na mesma noite em que os sofreu
      A dor é uma mestra. Não fuja das suas lições.

6 — Não desenvolver suas Disciplinas até o máximo do potencial
      A divindade é desperdiçada em quem não destrava seus dons.

5 — Matar de forma rápida e misericordiosa
      Um inimigo agonizante precisa conhecer o desespero para que Set ouça sua oferenda.

4 — Demonstrar qualquer sinal de dor
      Sua dor pertence a você e a mais ninguém a quem você não a dê.

3 — Sucumbir ao frenesi ou ao Rötschreck
      Se você tem todo o poder do mundo e a Besta o controla, você não tem nada.

2 — Pensar demais antes de agir
      A hesitação é falha mortal e indigna de você.

1 — Recusar-se a ajudar na ressurreição de Set
      A batalha final não pode começar até que o Deus da Tempestade e do Céu retorne.]==],
				},
				["Road of the Beast"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 117


Road of the Beast


Aura: Ameaça. A Besta é bem-vinda na pele do Apóstata, e isso aparece não só na penetração de seu olhar, mas no reflexo trêmulo de sua alma. A Besta é, de muitas maneiras, o espírito dela, e a perigosa sede de sobreviver a qualquer custo pinta sombras selvagens e sangue por toda a sua aura.


HIERARQUIA DE PECADOS CONTRA QUEM VOCÊ É

10 — Arriscar a própria vida
      A sobrevivência está acima de tudo.

9 — Reconhecer um líder
      Não existe "nós", só "eu".

8 — Matar por prazer
      Nunca desperdice.

7 — Escolher viver na ordem em vez do caos
      A civilização o amolece.

6 — Crueldade por prazer
      Crueldade é energia desperdiçada.

5 — Fazer algo em troca de nada
      Caridade não alimenta a Besta.

4 — Deixar de matar quando a sobrevivência está em jogo
      Se for você ou eles, tem de ser você.

3 — Não proteger o que é seu
      Torne seu, mantenha seu.

2 — Não ter nada que seja seu
      Marque seu território, marque seu povo, marque seu rebanho.

1 — Recusar-se a alimentar quando faminto
      Não há equilíbrio quando a Besta é negada.]==],
				},
				["Road of Humanity"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 122


Road of Humanity


Aura: Normalidade. O Cainita que trilha o Caminho da Humanidade se esforça para emular seu estado passado sempre que possível. Em questões de empatia e entendimento mútuo com mortais, sua Aura influenciará o resultado.


HIERARQUIA DE PECADOS CONTRA A ALMA

10 — Pensamentos egoístas
      Se pode ser pensado, pode ser feito.

9 — Pequenos atos egoístas
      Pôr-se em primeiro lugar deixa a Besta entrar.

8 — Ferir outra pessoa
      Acidental ou não, ainda há sangue em suas mãos.

7 — Furto
      Só um animal toma sem pensar nas consequências

6 — Violação acidental de outrem
      A humanidade é uma condição partilhada; o sofrimento dele é o seu.

5 — Destruição gratuita
      Você é uma pessoa ou um animal?

4 — Violação passional de outrem
      A paixão por trás da violência é o sussurro da Besta.

3 — Violação premeditada de outrem
      Ser tão frio é rejeitar o calor da humanidade.

2 — Violação casual de outrem
      Até animais selvagens sabem melhor.

1 — Os atos mais monstruosos e vis
      Você é uma pessoa ou um monstro?]==],
				},
				["Road of Kings"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 126


Road of Kings


Aura: Comando. Os Luminares são senhores de si e confiantes em seu direito de governar. Os outros sentem sua presença imperiosa como uma corrente posta em volta do pescoço.


HIERARQUIA DE PECADOS CONTRA A REALEZA

10 — Abrir mão do seu dever
      Quem não mantém suas responsabilidades costuma perdê-las.

9 — Tratar um igual com desrespeito
      É preciso dar respeito para recebê-lo dos outros.

8 — Colocar desejos pessoais acima do dever
      Um líder deve fazer o melhor para muitos, não para um só.

7 — Tratar um inferior como igual
      Cada um deve conhecer o seu lugar, inclusive você.

6 — Matar sem propósito
      Demonstrações de poder devem inspirar medo ou respeito.

5 — Demonstrar fraqueza diante de inferiores
      Um líder precisa ser forte o tempo todo.

4 — Deixar de responder a um desafio à sua honra
      Honra e reputação são tudo.

3 — Tratar seu superior com desrespeito
      Aos superiores deve ser dado o respeito que lhes é devido.

2 — Quebrar sua palavra ou seu juramento
      Sua palavra é sua honra. Sem honra, você não tem valor.

1 — Ceder à sua Besta, como no frenesi
      Se você não controla a si mesmo, como controlaria os outros?]==],
				},
				["Road of Lilith"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 129


Road of Lilith


Aura: Talhado e sangrando. A aura de um Bahari se manifesta como a de qualquer outro vampiro, embora possam surgir pedaços e espirais como que talhados no conjunto. Se alguém se concentra, pode julgar ver símbolos nesses entalhes movediços, mas não consegue apreender nenhum deles. Além disso, a aura parece sangrar ou gotejar, fazendo os "entalhes" parecerem mais feridas. Atos de criação e de ensino recebem o modificador de aura do personagem.


HIERARQUIA DE PECADOS CONTRA QUEM VOCÊ É

10 — Alimentar-se assim que sente fome
      Há uma lição em cada negação, e há controle na autonegação.

9 — Entrar num sistema criado por quem não tem sabedoria
      Viva fora das mentiras deles.

8 — Ignorar uma das faces de Lilith
      Aonde quer que você vá, a Mãe Sombria deixou mensagens para você. Leia os mitos deles e mostre-lhes onde Lilith vive.

7 — Rejeitar o sofrimento alheio ou desprezá-lo
      Ensine sempre que a oportunidade se apresentar, mesmo que você julgue as lições aprendidas abaixo de você.

6 — Crueldade por si mesma
      Como mestre, você precisa lapidar suas lições. Abusos mesquinhos estão abaixo de você. A dor que você inflige precisa ser divina.

5 — Roubar um grande aprendizado e reivindicá-lo como seu
      Se não foi você quem descobriu a sabedoria, não tem direito de reivindicá-la nem autoridade baseada nela.

4 — Destruir um ser pensante
      Eles não podem aprender com você nem lhe ensinar se forem destruídos.

3 — Não buscar os ensinamentos de Lilith
      Vire a folha, rache a madeira e encontre os segredos dela onde quer que se escondam.

2 — Interpor-se entre alguém e uma lição valiosa
      Melhor arrancar as estrelas do céu do que roubar de alguém momentos de verdadeira gnose.

1 — Fugir da dor
      Quanto mais difícil, mais recompensador o crescimento.]==],
				},
				["Road of Metamorphosis"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 133


Road of Metamorphosis


Aura: Desumanidade. Os Buscadores são decididamente alienígenas, tendo trabalhado tanto para lançar fora a própria humanidade. Os modificadores se aplicam sempre que o medo, a ansiedade ou o desconforto de outra pessoa possam afetar um teste.


HIERARQUIA DE PECADOS CONTRA A TRANSMOGRIFICAÇÃO

10 — Deixar de cavalgar um frenesi
      Embora se possa colher conhecimento da Besta, você não pode permitir que seus impulsos mais baixos o controlem.

9 — Oferecer conhecimento não solicitado a outrem
      A maioria não segue a sua trilha, mas não presuma tirar deles a escolha.

8 — Permitir que o prazer ou a emoção o distraiam
      O hedonismo desvia de fins mais altos.

7 — Pedir conhecimento a outrem
      Ninguém pode lhe ensinar a apoteose. Você precisa descobrir os segredos dela sozinho.

6 — Negar sustento a si mesmo
      A fome é a mais básica das distrações.

5 — Sucumbir à moral convencional quando havia conhecimento a obter
      Sem transgredir, você nunca encontrará o que está oculto à vista.

4 — Colocar os outros acima da sua busca por conhecimento
      Quem deseja acorrentar-se a este mundo vai segurar você também.

3 — Deixar de experimentar por compaixão, desconforto ou risco pessoal
      Podemos tropeçar no escuro, e pode ser desagradável, mas é o nosso único caminho adiante.

2 — Amar outra pessoa
      O amor se põe acima de tudo, até da Metamorfose. Não permita isso.

1 — Negligenciar a alteração do próprio corpo
      Se as formas que temos servissem à ascensão, já teríamos ascendido.]==],
				},
				["Road of Sin"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 135


Road of Sin


Aura: Tentação. Os Pecadores são livres e seu Caminho é cheio de promessas, e eles são hábeis em reconhecer os desejos alheios. O modificador de aura deles afeta testes para persuadir e atrair.


HIERARQUIA DE PECADOS CONTRA VOCÊ MESMO

10 — Reconhecer qualquer autoridade acima da sua
      Você está além da submissão.

9 — Deixar de satisfazer um desejo novo
      Nenhum prazer deve lhe ser negado.

8 — Deixar de cavalgar a onda do frenesi
      A Besta se cansa com o exercício e se fortalece com a negação.

7 — Abrir mão de prazeres duradouros por prazeres passageiros
      Não troque enchentes de desejo por um gole.

6 — Colocar as necessidades alheias à frente do seu prazer
      Sua necessidade pesa mais que tudo o mais.

5 — Fazer um juramento
      Não se prenda a ninguém, muito menos a si mesmo.

4 — Recusar-se a agir contra quem tenta prendê-lo
      As correntes mais verdadeiras são as que se impõe, mas as falsas prendem igual.

3 — Recusar-se a alimentar ou matar quando necessário
      Nenhuma vida vale mais que a sua.

2 — Incentivar os preceitos ou virtudes de outro Caminho
      Todos os outros Caminhos levam a gaiolas douradas e Bestas soltas.

1 — Recusar-se a agir no seu próprio interesse
      Só tolos se sacrificam.]==],
				},
				["Road of Bones"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 140


Road of Bones


Aura: Silêncio. A quietude do túmulo e o silêncio do estudo cercam os seguidores deste Caminho. O modificador de aura deles se aplica a todos os testes de Furtividade.


HIERARQUIA DE PECADOS CONTRA O CONHECIMENTO

10 — Recusar-se a partilhar conhecimento com um destinatário digno
      A erudição melhora com a revisão informada.

9 — Destruição gratuita e crueldade
      Bestas e idiotas não descobrirão nada além da estaca.

8 — Recusar-se a matar quando é útil ou necessário
      Que nenhum melindre mortal atrapalhe sua busca.

7 — Deixar-se levar pela emoção
      Estude a emoção como expressão da alma, mas não deixe que ela guie sua mão.

6 — Sucumbir ao frenesi
      Uma Besta enfurecida observa mal.

5 — Buscar poder, prestígio ou vínculos mortais em vez de conhecimento
      Essas coisas são meios para um fim e nada mais.

4 — Permitir que a compaixão ou a piedade o influenciem
      Fingir compaixão pode ser útil para manipular seus inimigos, mas não a deixe entrar no seu coração.

3 — Impedir uma morte sem necessidade
      Toda carne é pó.

2 — Demonstrar medo da morte
      Não tema a verdade.

1 — Destruir fontes insubstituíveis de conhecimento
      Destruir um artefato destrói um mundo inteiro.]==],
				},
				["Road of Yasa"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 141


Road of Yasa


Aura: Confiabilidade. Quem está acima de você confia que você cumprirá seu dever com obediência. Quem está abaixo confia que você os tratará com justiça. Os inimigos confiam que você os respeitará fazendo tudo ao seu alcance para derrotá-los. O modificador de aura afeta testes de Liderança aplicados contra subordinados e testes de Intimidação contra inimigos.


HIERARQUIA DE PECADOS CONTRA A YASA

10 — Ignorar um insulto
      Você conquistou o respeito dos outros.

9 — Insultar outrem sem que ele mereça
      É preciso mostrar respeito a quem o conquistou.

8 — Mentir para quem provou ser honesto
      A honestidade exige honestidade.

7 — Abusar do seu rebanho
      O rebanho não é de um só.

6 — Mostrar misericórdia a quem não se submeteu
      Os fracos precisam aceitá-lo como seu senhor.

5 — Perder uma batalha por orgulho
      Derrote seu inimigo agora. Console seu ego depois.

4 — Ferir família, anda, rebanho ou aliados durante o frenesi
      A qualidade essencial de um guerreiro é a disciplina.

3 — Desobedecer à ordem do seu noyan
      A obediência é o alicerce da honra.

2 — Trair sua família
      Você nunca conhecerá laço mais forte que o do sangue.

1 — Trair seus Irmãos de Sangue
      A família de escolha é a mais forte.]==],
				},
				["Road of Blood"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 432


Road of Blood


Aura: Determinação. Um seguidor do Caminho do Sangue leva sua tarefa a sério e é dedicado a levá-la até o fim. O modificador de aura afeta testes de Força de Vontade.


Pecados Contra o Sangue

10 — Agir por impulso em qualquer situação
      A disciplina é força.

9 — Permitir que a emoção dite as ações
      A paixão é o primeiro estremecer da Besta.

8 — Sucumbir ao frenesi
      Nossa vontade precisa ser inabalável.

7 — Deixar de diablerizar um vampiro indigno
      Devolva a Haqim o sangue dos indignos.

6 — Agir com covardia ou desonra
      Nossos atos recaem sobre nosso pai, Haqim.

5 — Deixar um indigno impune
      Somos os juízes dos não-vivos.

4 — Demonstrar fraqueza diante dos indignos
      Representamos Haqim em todas as coisas.

3 — Deixar de honrar um juramento
      Nossa honra é o que nos distingue.

2 — Submeter-se à vontade de um príncipe ou ancião indigno
      Nada neste mundo pode nos desviar do nosso propósito sagrado.

1 — Prender-se por juramento a outro Cainita
      Servimos a Haqim e a mais ninguém.]==],
				},
				["Road of Paradox"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 445


Road of Paradox


Aura: Confiança. Os Asura têm certeza de estar sempre onde deveriam estar, fazendo o que deveriam fazer. A confiança deles se derrama sobre os outros, inspirando-os a grandes feitos.


PECADOS CONTRA O PARADOXO

10 — Deixar de aceitar a morte
      Seu svadharma é apenas temporário; você precisa retornar ao samsara um dia.

9 — Abraçar fora da jati
      Só Abrace quem vá seguir o Caminho do Paradoxo.

8 — Destruir outro Asura
      Seus companheiros neste Caminho têm um svadharma; não os detenha.

7 — Matar um mortal para se sustentar
      A morte impede uma pessoa de cumprir seu svadharma nesta parte do ciclo.

6 — Deixar de matar vampiros de outro Caminho
      Só aceitando o verdadeiro caminho até moksha um vampiro pode se redimir. Fora isso, são inúteis.

5 — Permitir que assuntos pessoais interfiram no seu svadharma
      Você precisa seguir seu dever sagrado o tempo todo.

4 — Deixar de auxiliar o svadharma de outrem
      Este é seu único propósito antes de retornar ao ciclo.

3 — Matar um mortal por qualquer motivo que não a sobrevivência
      Impedir que outros alcancem seu svadharma é anátema.

2 — Tornar-se preso pelo vínculo de sangue
      Você não pode destruir seu regente, e isso pode impedi-lo de seguir seu svadharma.

1 — Abraçar sem necessidade, por desejo pessoal
      Você precisa deixar que os outros sigam seu ciclo, não retirá-los dele.]==],
				},
				["The Code of Samiel"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 448


The Code of Samiel


Aura: Sacrifício. A Aura dos escolhidos de Samiel ajuda em qualquer tentativa de se colocar em perigo por outra pessoa.


HIERARQUIA DE PECADOS CONTRA A RETIDÃO

10 — Deixar de punir a corrupção e o pecado
      O mal prospera no coração que ninguém desafia.

9 — Agir por avareza ou luxúria
      A honra precisa ser mais forte que o aço.

8 — Dar falso testemunho
      Sua espada é a da verdade.

7 — Alimentar-se do inocente sem permissão
      Como os Curandeiros estão presos, assim estaremos nós.

6 — Deixar de defender ou socorrer alguém em necessidade
      Um coração morto encontra vida no serviço aos outros.

5 — Deixar de defender ou socorrer um Curandeiro em necessidade
      A mão direita vermelha defende a esquerda.

4 — Deixar sem resposta um desafio digno
      Seja como o leão, não como o cordeiro.

3 — Deixar de desafiar um vampiro de Caminho baixo
      As almas deles põem em risco Cainitas e mortais.

2 — Desperdiçar uma oportunidade de vingança
      Que a retribuição seja seu orgulho e sua alçada.

1 — Auxiliar demônios, Baali, Setitas ou outros males
      Não ofereça aos ímpios socorro algum, senão sal e fogo.]==],
				},
				["Road of the Abyss"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 442


Road of the Abyss


Aura: Escuridão. A Aura deles afeta qualquer tentativa de perseguir a escuridão e de buscar verdades proibidas.


O Caminho do Abismo

10 — Demonstrar medo do escuro
      A escuridão tem muito a nos ensinar sobre o Abismo.

9 — Deixar de observar uma manifestação da escuridão
      Só pela observação se aumenta o conhecimento.

8 — Manifestar reverência pela criação
      A criação é uma praga, uma mácula na pureza do Abismo.

7 — Recusar-se a alimentar quando faminto
      A fome é uma manifestação do vazio.

6 — Recusar-se a matar quando esse é o caminho mais rápido
      Tudo retorna ao Abismo com o tempo.

5 — Ceder ao frenesi
      Para dominar a escuridão, primeiro é preciso dominar a si mesmo.

4 — Recusar-se a partilhar conhecimento com outro místico do Abismo
      A compreensão plena do Abismo não se alcança sem o discernimento alheio.

3 — Deixar a moral atrapalhar o estudo do Abismo
      Moral é fraqueza nascida da luz. Somos criaturas da escuridão.

2 — Evitar a escuridão sem necessidade
      Somos criaturas da escuridão. Rejeitá-la é rejeitar a si mesmo.

1 — Demonstrar aversão ao Abismo
      Não se domina aquilo que se teme.]==],
				},
				["Road of Set"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 449


Road of Set


Aura: Devoção. A Aura deles favorece tentativas de fazer proselitismo em nome de seu deus.


HIERARQUIA DE PECADOS CONTRA SET

10 — Buscar a indulgência pessoal acima dos interesses da Trilha
      A dissolução é o passatempo dos fracos.

9 — Recusar ajuda a outro seguidor da Trilha
      Precisamos trabalhar juntos se quisermos eliminar nossos inimigos.

8 — Deixar de obter vantagem contra os inimigos do Caminho
      Os injustos serão destruídos e os fracos, convertidos.

7 — Recusar-se a espalhar o culto a Set
      Quem carrega o sangue de Set carrega o dever sagrado de espalhar a palavra dele.

6 — Deixar de observar os rituais Setitas
      Só por nossa devoção conquistamos o favor de Set.

5 — Deixar de semear o caos entre os inimigos do Caminho
      Que os ímpios sejam derrubados.

4 — Deixar de fazer o que for preciso para converter os devotos de outras fés
      Aonde eles forem, outros seguirão.

3 — Obstruir os esforços de outro Setita
      Todos trabalhamos por um propósito comum.

2 — Recusar-se a ajudar na ressurreição de Set
      É nosso dever sagrado restaurar o lugar do nosso senhor no mundo.

1 — Adorar qualquer deus que não Set
      Set é nosso progenitor e protetor. Não há outro deus verdadeiro senão Set.]==],
				},
				["Path of the Archangel"] = {
					pt = [==[Dark Ages Companion, pág. 70


Path of the Archangel


Aura: Melancolia. Um Filho do Arcanjo aplica modificadores sempre que sua grande perda e seu anseio provoquem uma reação, ou quando ser visto como mártir for relevante.


PECADOS CONTRA O ARCANJO

10 — Ceder a qualquer tentação
      A verdadeira katharsis purga todas as paixões.

9 — Passar uma noite sem realizar trabalho criativo algum
      Na arte, iluminamos a verdade.

8 — Dar as costas a quem precisa de inspiração
      O trabalho de um anjo é guiar os perdidos.

7 — Recusar-se a fazer um sacrifício menor
      Despojar-se das coisas terrenas nos aproxima da divindade.

6 — Deixar um companheiro Toreador definhar sem batismo
      Somos todos os escolhidos de Michael.

5 — Passar uma semana sem realizar trabalho criativo algum
      A arte é como a alma adora.

4 — Ceder às tentações da carne
      Na katharsis renunciamos às paixões carnais.

3 — Abandonar alguém sob sua responsabilidade
      Precisamos merecer a adoração do rebanho.

2 — Ceder à sua Besta, como no frenesi
      A katharsis purga primeiro e acima de tudo nossos impulsos mais baixos.

1 — Recusar-se a fazer um sacrifício maior
      Seguimos o exemplo de Michael em tudo.]==],
				},
				["Road of Angra Mainyu"] = {
					pt = [==[Dark Ages Companion, pág. 84


Road of Angra Mainyu


Aura: Corrupção. Vampiros do Caminho de Angra Mainyu carregam uma aura de corrupção. Suas vozes são melífluas e eles ganham um bônus de +2 dados para persuadir as pessoas ao mal.


HIERARQUIA DE PECADOS CONTRA APEP

10 — Cometer qualquer ato de bondade
      O vampiro é servo de Angra Mainyu, aquele que traz o mal.

9 — Adiar a satisfação carnal
      Negar os próprios desejos é negar o próprio eu verdadeiro.

8 — Recusar a oportunidade de corromper um mortal
      A ordem nos impede de ser quem realmente somos.

7 — Recusar a oportunidade de corromper um vampiro
      Somos os filhos de Apep. O dom dele não pode ser rejeitado.

6 — Recusar a oportunidade de corromper uma figura sagrada
      A fraqueza precisa ser posta de lado.

5 — Deixar de solapar o ambiente mortal vigente
      A estagnação promove a fraqueza.

4 — Deixar de solapar as estruturas de poder Cainitas
      Tempos de conflito nos ajudam a descobrir nossa verdadeira força.

3 — Colocar os desejos alheios acima dos seus
      A civilização é uma mentira.

2 — Alimentar-se de homens maus
      O vampiro não deve ferir outros servos de Angra Mainyu.

1 — Temer o frenesi
      A Fúria e a Fome são dons de Angra Mainyu, e o vampiro precisa abraçá-las.]==],
				},
				["Road of Ahura Mazda"] = {
					pt = [==[Dark Ages Companion, pág. 84


Road of Ahura Mazda


Aura: Santidade. Vampiros do Caminho de Ahura Mazda ganham uma aura de bondade. Eles podem gastar dois pontos de Força de Vontade durante o frenesi para nomear algo que absolutamente não farão, por exemplo: "Não farei mal àquela criança." ("Não farei mal a criança alguma" é amplo demais, e a criança do primeiro exemplo continua sendo presa legítima num frenesi posterior.)


HIERARQUIA DE PECADOS CONTRA A ALMA

10 — Temer a Morte Final
      O vampiro trilhou o caminho de volta a Ahura Mazda. O Paraíso o espera quando morrer.

9 — Pequenos atos egoístas
      Pôr-se em primeiro lugar deixa a Besta entrar.

8 — Dizer palavras más, falar mal dos outros
      As palavras chegam ao ouvido de Ahura Mazda.

7 — Furto
      Só um animal toma sem pensar nas consequências

6 — Violação acidental de outrem
      A humanidade é uma condição partilhada; o sofrimento dele é o seu.

5 — Destruição gratuita
      Você é uma pessoa ou um animal?

4 — Violação passional de outrem
      A paixão por trás da violência é o sussurro da Besta.

3 — Violação premeditada de outrem
      Ser tão frio é rejeitar o calor da humanidade.

2 — Violação casual de outrem
      Até animais selvagens sabem melhor.

1 — Alimentar-se de homens bons
      O vampiro escolheu Ahura Mazda e precisa proteger os bons e justos.]==],
				},
				["Path of the Hunter"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 117


Path of the Hunter


Aura: Ameaça. A Besta é bem-vinda na pele do Apóstata, e isso aparece não só na penetração de seu olhar, mas no reflexo trêmulo de sua alma. A Besta é, de muitas maneiras, o espírito dela, e a perigosa sede de sobreviver a qualquer custo pinta sombras selvagens e sangue por toda a sua aura.


HIERARQUIA DE PECADOS CONTRA A CAÇADA

10 — Arriscar a própria vida
      A sobrevivência está acima de tudo.

9 — Reconhecer um líder
      Não existe "nós", só "eu".

8 — Ignorar ameaças em potencial à sua caçada.
      Outros tentarão limitar seus direitos de caça. Não deixe.

7 — Agir sem um plano
      Um Caçador descuidado já fracassou antes de começar.

6 — Crueldade por prazer
      Crueldade é energia desperdiçada.

5 — Fazer algo em troca de nada
      Caridade não alimenta a Besta.

4 — Deixar de matar quando a sobrevivência está em jogo
      Se for você ou eles, tem de ser você.

3 — Não proteger o que é seu
      Torne seu, mantenha seu.

2 — Caçar sem preparação ritual
      A Caçada é a única coisa sagrada.

1 — Recusar-se a alimentar quando faminto
      Não há equilíbrio quando a Besta é negada.]==],
				},
				["Path of Journeys"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 118


Path of Journeys


Aura: Ameaça. A Besta é bem-vinda na pele do Apóstata, e isso aparece não só na penetração de seu olhar, mas no reflexo trêmulo de sua alma. A Besta é, de muitas maneiras, o espírito dela, e a perigosa sede de sobreviver a qualquer custo pinta sombras selvagens e sangue por toda a sua aura.


HIERARQUIA DE PECADOS CONTRA AS JORNADAS

10 — Arriscar a própria vida
      A sobrevivência está acima de tudo.

9 — Reconhecer um líder
      Não existe "nós", só "eu".

8 — Matar por prazer
      Nunca desperdice.

7 — Escolher viver na ordem em vez do caos
      A civilização o amolece.

6 — Crueldade por prazer
      Crueldade é energia desperdiçada.

5 — Fazer algo em troca de nada
      Caridade não alimenta a Besta.

4 — Deixar de matar quando a sobrevivência está em jogo
      Se for você ou eles, tem de ser você.

3 — Deixar de explorar
      Você não pode saber o que há depois da esquina se não for olhar.

2 — Reconhecer laços com uma terra ou um povo
      Rejeite os títulos deles e as tentativas de domesticá-lo.

1 — Recusar-se a alimentar quando faminto
      Não há equilíbrio quando a Besta é negada.]==],
				},
				["Path of Liberation"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 118


Path of Liberation


Aura: Ameaça. A Besta é bem-vinda na pele do Apóstata, e isso aparece não só na penetração de seu olhar, mas no reflexo trêmulo de sua alma. A Besta é, de muitas maneiras, o espírito dela, e a perigosa sede de sobreviver a qualquer custo pinta sombras selvagens e sangue por toda a sua aura.


HIERARQUIA DE PECADOS CONTRA A LIBERTAÇÃO

10 — Arriscar a própria vida
      A sobrevivência está acima de tudo.

9 — Reconhecer um líder
      Não existe "nós", só "eu".

8 — Deixar de expor alguém a uma verdade dura
      A libertação pertence a todos.

7 — Escolher viver na ordem em vez do caos
      A civilização o amolece.

6 — Buscar conforto na cidade em vez de desmontá-la
      Se torna sua vida mais fácil, o torna mais fraco. Destrua isso.

5 — Fazer algo em troca de nada
      Caridade não alimenta a Besta.

4 — Deixar de matar quando a sobrevivência está em jogo
      Se for você ou eles, tem de ser você.

3 — Não proteger o que é seu
      Torne seu, mantenha seu.

2 — Não ter nada que seja seu
      Marque seu território, marque seu povo, marque seu rebanho.

1 — Fortalecer a tirania
      Você cria libertação, queiram eles ou não.]==],
				},
				["Path of Christianity"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 120


Path of Christianity


Aura: Santidade. Os Fiéis recebem bônus sempre que estiverem em situações nas quais ser visto como sagrado lhes dê vantagem social.


A TRILHA DE CRISTO (CRISTIANISMO)

10 — Deixar de denunciar a corrupção e o pecado
      Basta ao mal, para triunfar, a inação dos justos.

9 — Agir por orgulho, avareza, luxúria ou outro impulso pecaminoso
      O caminho até a Besta é pavimentado de pecado.

8 — Dar falso testemunho
      Língua mentirosa é odiosa aos olhos do Senhor.

7 — Causar dano a uma pessoa piedosa
      Deus protege os inocentes.

6 — Alimentar-se de um inocente sem permissão
      Corromper o inocente é pecado grave.

5 — Blasfêmia ou heresia em palavra ou ato
      A blasfêmia é pecado contra Deus.

4 — Assassinato de inocentes
      Não matarás, diz o Senhor.

3 — Adorar falsos ídolos
      Não terás outros deuses diante de mim.

2 — Auxiliar demônios ou o mal sobrenatural
      É dever dos justos ferir os ímpios.

1 — Deixar de espalhar o Evangelho de Cristo
      É dever de todo cristão espalhar a boa nova de Nosso Senhor]==],
				},
				["Path of Life/Judaism"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 120


Path of Life/Judaism


Aura: Santidade. Os Fiéis recebem bônus sempre que estiverem em situações nas quais ser visto como sagrado lhes dê vantagem social.


DERECH CHAIM — A TRILHA DA VIDA (JUDAÍSMO)

10 — Deixar de manter um estado de pureza ritual
      E sereis para mim homens santos.

9 — Contato desnecessário com não-judeus
      O povo precisa ser protegido.

8 — Deixar de encontrar uma autoridade rabínica que decida por você, e de obedecer a essas decisões
      Onde quer que haja profanação do nome de Deus, não se mostra respeito ao rabino.

7 — Deixar de obedecer às leis e aos costumes da comunidade judaica local
      As necessidades espirituais do indivíduo só podem ser atendidas pela comunidade.

6 — Deixar de manter vínculo com uma comunidade judaica local
      Judeus não podem existir isolados.

5 — Beber sangue não permitido
      Pois a vida da carne está no sangue.

4 — Adorar ídolos
      Ouve, ó Israel, Deus é Um.

3 — Cometer violência sexual
      É pior injustiçar um semelhante do que injustiçar a Deus.

2 — Assassinato
      Quem derramar o sangue do homem, pelo homem terá o seu sangue derramado.

1 — Pôr em risco a comunidade judaica
      Não te porás de lado diante do sangue do teu próximo.]==],
				},
				["Path of the Prophet/Islam"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 121


Path of the Prophet/Islam


Aura: Santidade. Os Fiéis recebem bônus sempre que estiverem em situações nas quais ser visto como sagrado lhes dê vantagem social.


A TRILHA DO PROFETA (ISLAMISMO)

10 — Deixar de honrar seus mais velhos
      Não lhes dirijas palavra de desprezo, mas fala-lhes com honra.

9 — Deixar de cuidar dos indefesos
      Todo poder é dádiva de Deus.

8 — Ser desonesto ou injusto no trato com os outros
      Dá a medida cheia e pesa com balança justa.

7 — Quebrar uma promessa
      Todo pacto será inquirido no Dia do Ajuste de Contas.

6 — Jactância ou arrogância
      Bem-aventurados os que se humilham nas preces.

5 — Alimentar-se de um não-muçulmano
      Ele proibiu aquilo que foi imolado a qualquer outro deus.

4 — Matar injustamente
      Nem tires a vida — que Allah fez sagrada — por causa injusta.

3 — Reconhecer qualquer deus além de Allah (e Maomé é Seu Profeta)
      Não tomes junto a Allah outro objeto de adoração.

2 — Romper a unidade do Islã
      Vós, muçulmanos, sois a melhor nação surgida para a Humanidade.

1 — Deixar de submeter-se à vontade de Allah tal como revelada por seu Profeta e pela revelação
      Só Deus possui todo poder e toda glória.]==],
				},
				["Path of Breath"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 123


Path of Breath


Aura: Normalidade. O Cainita que trilha o Caminho da Humanidade se esforça para emular seu estado passado sempre que possível. Em questões de empatia e entendimento mútuo com mortais, sua Aura influenciará o resultado.


HIERARQUIA DE PECADOS CONTRA O SOPRO

10 — Permitir-se pensar ou agir como um vampiro

9 — Pequenos atos egoístas
      Pôr-se em primeiro lugar deixa a Besta entrar.

8 — Ferir outra pessoa
      Acidental ou não, ainda há sangue em suas mãos.

7 — Deixar conscientemente um humano sofrer

6 — Violação acidental de outrem
      A humanidade é uma condição partilhada; o sofrimento dele é o seu.

5 — Destruição gratuita
      Você é uma pessoa ou um animal?

4 — Violação passional de outrem
      A paixão por trás da violência é o sussurro da Besta.

3 — Violação premeditada de outrem
      Ser tão frio é rejeitar o calor da humanidade.

2 — Violação casual de outrem
      Até animais selvagens sabem melhor.

1 — Passar uma noite sem contato humano]==],
				},
				["Path of Community"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 124


Path of Community


Aura: Normalidade. O Cainita que trilha o Caminho da Humanidade se esforça para emular seu estado passado sempre que possível. Em questões de empatia e entendimento mútuo com mortais, sua Aura influenciará o resultado.


HIERARQUIA DE PECADOS CONTRA A COMUNIDADE

10 — Pensamentos egoístas
      Se pode ser pensado, pode ser feito.

9 — Pequenos atos egoístas
      Pôr-se em primeiro lugar deixa a Besta entrar.

8 — Ferir outra pessoa
      Acidental ou não, ainda há sangue em suas mãos.

7 — Destruição acidental de propriedade pública

6 — Violação acidental de outrem
      A humanidade é uma condição partilhada; o sofrimento dele é o seu.

5 — Destruição gratuita
      Você é uma pessoa ou um animal?

4 — Furto

3 — Violação premeditada de outrem
      Ser tão frio é rejeitar o calor da humanidade.

2 — Violação casual de outrem
      Até animais selvagens sabem melhor.

1 — Genocídio ou qualquer ação que acabe com a capacidade de uma comunidade crescer e prosperar]==],
				},
				["Path of Illumination"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 124


Path of Illumination


Aura: Normalidade. O Cainita que trilha o Caminho da Humanidade se esforça para emular seu estado passado sempre que possível. Em questões de empatia e entendimento mútuo com mortais, sua Aura influenciará o resultado.


HIERARQUIA DE PECADOS CONTRA A ILUMINAÇÃO

10 — Permanecer em qualquer lugar que não o faça avançar em sua jornada

9 — Pequenos atos egoístas
      Pôr-se em primeiro lugar deixa a Besta entrar.

8 — Ferir outra pessoa
      Acidental ou não, ainda há sangue em suas mãos.

7 — Qualquer ato que impeça um Cainita de seguir a jornada que você começou.

6 — Violação acidental de outrem
      A humanidade é uma condição partilhada; o sofrimento dele é o seu.

5 — Destruição gratuita
      Você é uma pessoa ou um animal?

4 — Violação passional de outrem
      A paixão por trás da violência é o sussurro da Besta.

3 — Violação premeditada de outrem
      Ser tão frio é rejeitar o calor da humanidade.

2 — Violação casual de outrem
      Até animais selvagens sabem melhor.

1 — Deixar a verdadeira escuridão entrar, para sufocar a luz. Aceitar o Mal.]==],
				},
				["Path of Chivalry"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 126


Path of Chivalry


Aura: Comando. Os Luminares são senhores de si e confiantes em seu direito de governar. Os outros sentem sua presença imperiosa como uma corrente posta em volta do pescoço.


HIERARQUIA DE PECADOS CONTRA A CAVALARIA

10 — Negligenciar seu dever por qualquer motivo
      O dever vem primeiro.

9 — Atos desonrosos (engano, assassinato etc.)
      Sua honra é a coisa mais importante.

8 — Tratar outrem com desrespeito
      É preciso dar respeito para recebê-lo dos outros.

7 — Comportar-se de maneira injusta
      É seu dever sustentar a justiça.

6 — Deixar de socorrer alguém
      É seu dever proteger os fracos.

5 — Tratar seu superior com desrespeito
      Aos superiores deve ser dado o respeito que lhes é devido.

4 — Colocar desejos pessoais acima do dever
      Pensamentos egoístas não têm lugar no coração de um Paladino.

3 — Deixar de responder a um desafio à sua honra
      Honra e reputação são tudo.

2 — Quebrar sua palavra
      Sua palavra é sua honra. Sem honra, você não tem valor.

1 — Quebrar um juramento solene
      Juramentos de fidelidade são o que faz a sociedade civilizada.]==],
				},
				["Path of Devaraja"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 126


Path of Devaraja


Aura: Comando. Os Luminares são senhores de si e confiantes em seu direito de governar. Os outros sentem sua presença imperiosa como uma corrente posta em volta do pescoço.


HIERARQUIA DE PECADOS CONTRA DEVARAJA

10 — Deixar de reconhecer o divino
      Seu poder vem da vontade divina.

9 — Abrir mão do seu dever
      Quem não mantém suas responsabilidades costuma perdê-las.

8 — Tratar outrem com desrespeito
      É preciso dar respeito para recebê-lo dos outros.

7 — Tratar um inferior como igual
      Você é um deus; não se esqueça disso.

6 — Colocar desejos pessoais acima do dever
      Um líder deve fazer o melhor para muitos, não para um só.

5 — Deixar de tomar o poder quando a chance surge
      Você precisa provar ao divino que merece sua bênção.

4 — Deixar de responder a um desafio à sua honra.
      Deuses de verdade ferem seus detratores.

3 — Matar sem propósito
      É seu dever divino proteger seus adoradores, não matá-los.

2 — Quebrar sua palavra ou seu juramento
      Sua palavra é sua honra. Sem honra, você não tem valor.

1 — Ceder à sua Besta, como no frenesi
      Se você não controla a si mesmo, como aceitaria o divino?]==],
				},
				["Path of Daena"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 128


Path of Daena


Aura: Comando. Os Luminares são senhores de si e confiantes em seu direito de governar. Os outros sentem sua presença imperiosa como uma corrente posta em volta do pescoço.


HIERARQUIA DE PECADOS CONTRA DAENA

10 — Negligenciar seu dever por qualquer motivo
      O dever vem primeiro.

9 — Infringir a lei
      Você precisa sustentar a lei a todo custo.

8 — Tratar outrem com desrespeito
      É preciso dar respeito para recebê-lo dos outros.

7 — Comportar-se de maneira injusta
      É seu dever sustentar a justiça.

6 — Matar sem propósito
      Demonstrações de poder devem inspirar medo ou respeito.

5 — Deixar de socorrer alguém
      Para obter poder, primeiro é preciso reunir boa vontade.

4 — Tratar seu superior com desrespeito
      Aos superiores deve ser dado o respeito que lhes é devido.

3 — Deixar de sustentar a lei
      É seu dever sustentar a lei, custe o que custar.

2 — Quebrar sua palavra ou seu juramento
      Sua palavra é sua honra. Sem honra, você não tem valor.

1 — Ceder à sua Besta, como no frenesi
      Se você não controla a si mesmo, como controlaria os outros?]==],
				},
				["Path of Thorns"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 130


Path of Thorns


Aura: Talhado e sangrando. A aura de um Bahari se manifesta como a de qualquer outro vampiro, embora possam surgir pedaços e espirais como que talhados no conjunto. Se alguém se concentra, pode julgar ver símbolos nesses entalhes movediços, mas não consegue apreender nenhum deles. Além disso, a aura parece sangrar ou gotejar, fazendo os "entalhes" parecerem mais feridas. Atos de criação e de ensino recebem o modificador de aura do personagem.


HIERARQUIA DE PECADOS CONTRA OS ESPINHOS

10 — Alimentar-se assim que sente fome
      Há uma lição em cada negação, e há controle na autonegação.

9 — Entrar em qualquer comunidade de tolos.

8 — Ignorar uma das faces de Lilith
      Aonde quer que você vá, a Mãe Sombria deixou mensagens para você. Leia os mitos deles e mostre-lhes onde Lilith vive.

7 — Rejeitar o sofrimento alheio ou desprezá-lo
      Ensine sempre que a oportunidade se apresentar, mesmo que você julgue as lições aprendidas abaixo de você.

6 — Crueldade por si mesma
      Como mestre, você precisa lapidar suas lições. Abusos mesquinhos estão abaixo de você. A dor que você inflige precisa ser divina.

5 — Aceitar um aluno (formal ou informal) na primeira vez em que ele o procura.

4 — Destruir um ser pensante
      Eles não podem aprender com você nem lhe ensinar se forem destruídos.

3 — Não buscar os ensinamentos de Lilith
      Vire a folha, rache a madeira e encontre os segredos dela onde quer que se escondam.

2 — Colocar o aprendizado de outro acima do seu.

1 — Fugir da dor
      Quanto mais difícil, mais recompensador o crescimento.]==],
				},
				["Path of Veils"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 131


Path of Veils


Aura: Talhado e sangrando. A aura de um Bahari se manifesta como a de qualquer outro vampiro, embora possam surgir pedaços e espirais como que talhados no conjunto. Se alguém se concentra, pode julgar ver símbolos nesses entalhes movediços, mas não consegue apreender nenhum deles. Além disso, a aura parece sangrar ou gotejar, fazendo os "entalhes" parecerem mais feridas. Atos de criação e de ensino recebem o modificador de aura do personagem.


HIERARQUIA DE PECADOS CONTRA OS VÉUS

10 — Alimentar-se assim que sente fome
      Há uma lição em cada negação, e há controle na autonegação.

9 — Aceitar e obedecer a qualquer lei de Caim ou de Deus.

8 — Deixar de destruir as obras dos noditas mentirosos.

7 — Rejeitar o sofrimento alheio ou desprezá-lo
      Ensine sempre que a oportunidade se apresentar, mesmo que você julgue as lições aprendidas abaixo de você.

6 — Crueldade por si mesma
      Como mestre, você precisa lapidar suas lições. Abusos mesquinhos estão abaixo de você. A dor que você inflige precisa ser divina.

5 — Roubar um grande aprendizado e reivindicá-lo como seu
      Se não foi você quem descobriu a sabedoria, não tem direito de reivindicá-la nem autoridade baseada nela.

4 — Apagar a chama de uma vela que deseja arder mais forte.

3 — Não buscar os ensinamentos de Lilith
      Vire a folha, rache a madeira e encontre os segredos dela onde quer que se escondam.

2 — Interpor-se entre alguém e uma lição valiosa
      Melhor arrancar as estrelas do céu do que roubar de alguém momentos de verdadeira gnose.

1 — Fugir da dor
      Quanto mais difícil, mais recompensador o crescimento.]==],
				},
				["Path of Making"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 131


Path of Making


Aura: Talhado e sangrando. A aura de um Bahari se manifesta como a de qualquer outro vampiro, embora possam surgir pedaços e espirais como que talhados no conjunto. Se alguém se concentra, pode julgar ver símbolos nesses entalhes movediços, mas não consegue apreender nenhum deles. Além disso, a aura parece sangrar ou gotejar, fazendo os "entalhes" parecerem mais feridas. Atos de criação e de ensino recebem o modificador de aura do personagem.


HIERARQUIA DE PECADOS CONTRA A CRIAÇÃO

10 — Rejeitar as investidas de demônios com semente em punho.

9 — Entrar num sistema criado por quem não tem sabedoria
      Viva fora das mentiras deles.

8 — Ignorar uma das faces de Lilith
      Aonde quer que você vá, a Mãe Sombria deixou mensagens para você. Leia os mitos deles e mostre-lhes onde Lilith vive.

7 — Abandonar uma coisa porque ela é feia ou assustadora.

6 — Crueldade por si mesma
      Como mestre, você precisa lapidar suas lições. Abusos mesquinhos estão abaixo de você. A dor que você inflige precisa ser divina.

5 — Não tomar um segredo de fazer e criar de selvagens que não conhecem o propósito divino por trás dele.

4 — Destruir um ser pensante
      Eles não podem aprender com você nem lhe ensinar se forem destruídos.

3 — Não buscar os ensinamentos de Lilith
      Vire a folha, rache a madeira e encontre os segredos dela onde quer que se escondam.

2 — Interpor-se entre alguém e uma lição valiosa
      Melhor arrancar as estrelas do céu do que roubar de alguém momentos de verdadeira gnose.

1 — Rejeitar as investidas de anjos com semente em punho.]==],
				},
				["Path of Pleasure"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 135


Path of Pleasure


Aura: Tentação. Os Pecadores são livres e seu Caminho é cheio de promessas, e eles são hábeis em reconhecer os desejos alheios. O modificador de aura deles afeta testes para persuadir e atrair.


HIERARQUIA DE PECADOS CONTRA O PRAZER

10 — Envergonhar-se dos próprios atos
      A vergonha é a desaprovação nos olhos alheios; seus atos só precisam agradar a você.

9 — Deixar de satisfazer seus desejos
      A saciedade mantém a Besta a distância.

8 — Deixar de cavalgar a onda do frenesi
      As fúrias vermelhas são apenas mais um prazer a experimentar.

7 — Qualquer demonstração de modéstia
      A modéstia é moral imposta de fora. Nunca se submeta a ela.

6 — Colocar as necessidades alheias à frente dos seus interesses
      Seus desejos vêm antes da necessidade deles.

5 — Fazer um juramento
      Um coração selvagem nunca deve ser acorrentado.

4 — Conviver com quem não lhe traz prazer
      A Besta se enfurece quando negada; nunca dê licença à fúria dela.

3 — Recusar-se a alimentar ou matar quando necessário
      Estas são suas alegrias maiores e mais puras.

2 — Incentivar a virtude ou os agentes da virtude
      Por que gastar esforço em ajudar quem o acorrentaria?

1 — Recusar-se a agir no seu próprio interesse
      Seus desejos são tudo o que realmente importa.]==],
				},
				["Path of the Devil"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 135


Path of the Devil


Aura: Tentação. Os Pecadores são livres e seu Caminho é cheio de promessas, e eles são hábeis em reconhecer os desejos alheios. O modificador de aura deles afeta testes para persuadir e atrair.


HIERARQUIA DE PECADOS CONTRA A REBELIÃO

10 — Reconhecer as leis de Deus ou do Homem
      Nunca dê crédito a quem escravizaria os outros.

9 — Deixar de satisfazer um desejo novo
      A paixão é o fogo da alma.

8 — Deixar de cavalgar a onda do frenesi
      A Besta só pode ser compreendida depois da luta.

7 — Recusar ajuda a uma alma perdida em necessidade
      Os fracos não compreendem a própria natureza e precisam ser ensinados pelos fortes.

6 — Recusar um prazer que não fere ninguém
      Buscar o próprio prazer é a mais cara das buscas.

5 — Fazer um juramento
      A servidão forçada não tem remédio e merece pena; a servidão que se impõe é hedionda e deve ser combatida.

4 — Recusar-se a agir contra quem escolhe prendê-lo
      Puna quem tenta controlá-lo.

3 — Recusar-se a alimentar ou matar quando necessário
      Nunca sinta vergonha de fazer o que precisa ser feito.

2 — Buscar ganho material às custas de questões mais altas
      Enriqueça sua alma antes de encher seus cofres.

1 — Incentivar a falsa virtude ou os agentes da falsa virtude
      As amarras das leis escravizam a mente e estrangulam a alma.]==],
				},
				["Path of Screams"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 136


Path of Screams


Aura: Tentação. Os Pecadores são livres e seu Caminho é cheio de promessas, e eles são hábeis em reconhecer os desejos alheios. O modificador de aura deles afeta testes para persuadir e atrair.


HIERARQUIA DE PECADOS CONTRA A CONDENAÇÃO

10 — Reconhecer quaisquer leis que não as do Inferno
      Divindade e mundanidade nada significam para os Condenados.

9 — Deixar de satisfazer seus desejos
      O prazer o fortalece, e isso fortalece seus senhores.

8 — Deixar de cavalgar a onda do frenesi
      A Besta é o clarim da sua alma.

7 — Recusar-se a alimentar ou matar quando necessário
      Belo é o sangue que escurece a terra.

6 — Evitar ferir os outros por qualquer motivo
      Sangue derramado é seu presente ao mundo, seu maior prazer.

5 — Qualquer demonstração de misericórdia ou piedade
      A misericórdia é para os fracos, e a Condenação o torna forte.

4 — Deixar de agir em nome do Inferno
      Você serve ao Inferno, mesmo quando ele não serve a você.

3 — Qualquer comportamento altruísta
      Você não deve nada aos outros.

2 — Agir contra os servos do Inferno
      Somos todos zangões na colmeia do Poço.

1 — Incentivar a virtude ou os agentes da virtude
      Nada de puro pode resistir a você, nem mesmo a pureza do Pecado.]==],
				},
				["Path of Watchful Gods"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 137


Path of Watchful Gods


Aura: Tentação. Os Pecadores são livres e seu Caminho é cheio de promessas, e eles são hábeis em reconhecer os desejos alheios. O modificador de aura deles afeta testes para persuadir e atrair.


HIERARQUIA DE PECADOS CONTRA OS DEUSES VIGILANTES

10 — Deixar de fazer sacrifícios regulares
      Sacrifícios regulares dão força aos deuses.

9 — Mentir
      Não se desonre aos olhos dos deuses com palavras falsas.

8 — Ofender os deuses ou os espíritos com violência
      Não desrespeite os espíritos com violência, pois eles se ofendem depressa e sua memória é longa.

7 — Deixar de agir com honra
      Os deuses recompensam a honra e punem a desonra.

6 — Roubar de oferendas ou sacrifícios
      Dê aos deuses os primeiros frutos do seu trabalho e não lhes negue a parte deles.

5 — Não honrar os sacerdotes
      Sacerdotes são servos da ordem e do equilíbrio, favorecidos pelos deuses.

4 — Matar um animal sagrado
      Honre aquilo que os deuses decretaram sagrado.

3 — Profanar lugares sagrados
      Profanar um templo é como amaldiçoar os próprios deuses.

2 — Danificar a imagem dos deuses
      Deve-se buscar sempre honrar os deuses em pensamento e em ato.

1 — Injuriar um deus ou os deuses
      Os deuses são a fonte de toda vida e de todo bem.]==],
				},
				-- <<< ROAD_DESC_END
};
