-- Weapon descriptions, the [pt] half (SPEC I157h, I21, V210 / T1004).
--
-- One entry per item of PICKER_LIST["weapon"], keyed in ENGLISH because that is what the sheet
-- saves (SPEC V24). Three blocks, exactly as the twelve description modules already do:
-- "<Book>, p. <n>" - blank - blank - <Name> - blank - blank - <text>. The book title does
-- not translate; only p./pag. does (SPEC I100e).
--
-- One module PER LANGUAGE and never both halves in one file (SPEC V210): half of every
-- module was the language the session never opens, and require pulled both in to read one.
-- The renderer builds the name by concatenation - require("desc<Kind>_" .. half .. ".lua")
-- and never a constant name (SPEC V210b).
--
-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24).
-- Generated by research/gen_combat_data.ps1 from research/weapon.tsv and
-- research/armor.tsv. Do not hand-edit.

return {
				-- >>> WEAPON_DESC_BEGIN (generated - SPEC T1004)
				[".30 Caliber Machine Gun"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


.30 Caliber Machine Gun


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 12
Alcance: 800
Cadência: 5
Pente: 100
Ocultação: N

Notas: Arma militar: especialização de Armas de Fogo em Armas Pesadas. Pode disparar fogo automático, rajadas e varredura.]==],
				},
				[".50 Caliber Machine Gun"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


.50 Caliber Machine Gun


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 16
Alcance: 1000
Cadência: 5
Pente: 200
Ocultação: N

Notas: Arma militar; não portátil, montada em veículo. Pode disparar fogo automático, rajadas e varredura.]==],
				},
				["30 mm Cannon"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


30 mm Cannon


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 15
Alcance: 1200
Cadência: 8
Pente: 100
Ocultação: N

Notas: Canhão rotativo militar levado por HIT Marks e ciborgues pesados; reduz a proteção de armadura à metade.]==],
				},
				["3-Round Burst"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


3-Round Burst


Parada: Des + Armas de Fogo
Dificuldade: 7
Dano: Arma
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Precisão +2. Gasta três balas do pente.]==],
				},
				["Aiming"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Aiming


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: Arma
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: +2 dados para acertar por turno gasto mirando.]==],
				},
				["Aiming (Dark Ages)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Aiming (Dark Ages)


Parada: Des + Arquearia
Dificuldade: 6
Dano: Arma
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: +1 dado por turno gasto mirando.]==],
				},
				["Assault Rifle"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 281


Assault Rifle


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 7
Alcance: 150
Cadência: 3
Pente: 30+1
Ocultação: N

Notas: Exemplo: FN SCAR (5.56mm). Capaz de rajadas de 3 tiros, fogo automático e varredura.]==],
				},
				["Assault Rifle (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Assault Rifle (Mage)


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 7
Alcance: 150
Cadência: 3
Pente: 42+1
Ocultação: N

Notas: Exemplo: AK-47 (7.62x39mm). Pode disparar fogo automático, rajadas de 3 tiros e varredura.]==],
				},
				["Automatic Fire"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Automatic Fire


Parada: Des + Armas de Fogo
Dificuldade: 8
Dano: Especial
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Precisão +10. Esvazia o pente. Só armas capazes de fogo automático.]==],
				},
				["Axe"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 280


Axe


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 3 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N]==],
				},
				["Axe (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Axe (Mage)


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 3 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N]==],
				},
				["Axe (Werewolf)"] = {
					pt = [==[Werewolf: The Apocalypse 20th Anniversary Edition, pág. 302


Axe (Werewolf)


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 3 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: M]==],
				},
				["Barbed Cat"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 451


Barbed Cat


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R

Notas: Pode enredar um membro a dificuldade +1.]==],
				},
				["Baseball Bat"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Baseball Bat


Parada: Des + Armas Brancas
Dificuldade: 5
Dano: For + 2 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: M]==],
				},
				["Battle-Ax"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Battle-Ax


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 4 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 4. Duas mãos.]==],
				},
				["Bear Mace"] = {
					pt = [==[Werewolf: The Apocalypse 20th Anniversary Edition, pág. 303


Bear Mace


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 4 (C)
Alcance: 3
Cadência: 1
Pente: 3
Ocultação: B

Notas: Contusão; sem dano extra por sucessos. O alvo perde dois dados por um turno por sucesso.]==],
				},
				["Biggs Mjollner Mk. IV"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Biggs Mjollner Mk. IV


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 10
Alcance: 100
Cadência: 1
Pente: 10
Ocultação: M

Notas: Arma de mão da Tecnocracia. Tende a travar numa falha em mãos não Iluminadas.]==],
				},
				["Biggs X-5 Model A Protector"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Biggs X-5 Model A Protector


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 5
Alcance: 40
Cadência: 4
Pente: 12+1
Ocultação: R

Notas: Arma de mão da Tecnocracia. Pode disparar fogo automático, rajadas e varredura; compósito, invisível a detectores de metal.]==],
				},
				["Biggs X-5 Model R Protector"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Biggs X-5 Model R Protector


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 5
Alcance: 40
Cadência: 4
Pente: 12
Ocultação: R

Notas: Arma de mão da Tecnocracia. Revólver que aceita qualquer munição carregada ao toque de um botão; compósito, invisível a detectores de metal.]==],
				},
				["Bite"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Bite


Parada: Des + Briga
Dificuldade: 6
Dano: For + 1 (A)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Precisão +1. Exige agarrão, imobilização ou investida bem-sucedida antes. (A) dano agravado.]==],
				},
				["Bite (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 448


Bite (Mage)


Parada: Des + Briga
Dificuldade: 5
Dano: For + 1 a + 3 (C ou L)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Bônus e tipo de dano dependem da mandíbula de quem morde.]==],
				},
				["Blinding"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Blinding


Parada: Des + Lábia
Dificuldade: 9
Dano: Especial
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Luta suja (mín. Briga 3). Inimigo cego por um turno por sucesso e perde dois dados até se recuperar.]==],
				},
				["Block"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Block


Parada: Des + Briga
Dificuldade: 6
Dano: Nenhum (R)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Precisão: especial. (R) reduz os sucessos de ataque do oponente.]==],
				},
				["Body Slam"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Body Slam


Parada: Des + Briga
Dificuldade: 6
Dano: For + 2 (C ou L)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Luta suja (mín. Briga 3).]==],
				},
				["Bolan Mk.13 Weapons System"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Bolan Mk.13 Weapons System


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: -
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Arma da Tecnocracia: submetralhadora (como AK-47, pente de 50) mais escopeta automática (como MPS AA-12, pente de 20) mais lança-granadas (como M-79, carregador de seis). Mira laser; exige Força 3.]==],
				},
				["Brass Knuckles"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Brass Knuckles


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: B]==],
				},
				["Broadsword"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Broadsword


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 3. Pode ser usada com as duas mãos com Força mínima 2: For + 3 (L).]==],
				},
				["Broken Bottle"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Broken Bottle


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: B

Notas: Quebra depois de três usos.]==],
				},
				["Bullwhip"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 451


Bullwhip


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R

Notas: Pode enredar um membro a dificuldade +1.]==],
				},
				["Castle-Graves WW-3"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Castle-Graves WW-3


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 8
Alcance: 200
Cadência: 3
Pente: 50+1
Ocultação: N

Notas: Arma da Tecnocracia. Pode disparar fogo automático, rajadas e varredura.]==],
				},
				["Chain"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 451


Chain


Parada: Des + Armas Brancas
Dificuldade: 5
Dano: For (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: R

Notas: Pode enredar um membro a dificuldade +1.]==],
				},
				["Chain Whip"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 451


Chain Whip


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R

Notas: Pode enredar um membro a dificuldade +1.]==],
				},
				["Chainsaw"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Chainsaw


Parada: Des + Armas Brancas
Dificuldade: 8
Dano: For + 7 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Numa falha crítica o usuário se fere.]==],
				},
				["Chair"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Chair


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 2 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: N]==],
				},
				["Claw"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Claw


Parada: Des + Briga
Dificuldade: 6
Dano: For + 1 (A)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Vampiros com garras (Metamorfose, Vicissitude). (A) dano agravado.]==],
				},
				["Claw (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 448


Claw (Mage)


Parada: Des + Briga
Dificuldade: 6
Dano: For + 1 a + 3 (L ou A)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Bônus e tipo de dano dependem das garras.]==],
				},
				["Clinch"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Clinch


Parada: For + Briga
Dificuldade: 6
Dano: For (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Precisão: especial. (C) continua nos turnos seguintes.]==],
				},
				["Clinch (Dark Ages)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Clinch (Dark Ages)


Parada: Des + Briga
Dificuldade: 6
Dano: For (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: (C) continua nos turnos seguintes.]==],
				},
				["Club"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 280


Club


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: M

Notas: Contundente: dano de contusão, salvo mira na cabeça (letal).]==],
				},
				["Club (Dark Ages)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Club (Dark Ages)


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: R

Notas: Força mínima 2.]==],
				},
				["Counter Throw"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Counter Throw


Parada: Des + Artes Marciais
Dificuldade: 6
Dano: Especial
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Jogada resistida de Des + Artes Marciais contra Des + Briga, Armas Brancas ou Artes Marciais do atacante; sucesso desvia o ataque e pode Arremessar o atacante.]==],
				},
				["Crossbow"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 281


Crossbow


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 5
Alcance: 20
Cadência: 1
Pente: 1
Ocultação: M

Notas: Cinco turnos para recarregar. Contusão contra Membros, salvo mira na cabeça ou no coração; letal contra mortais. Incluída para estacar.]==],
				},
				["Crossbow (Dark Ages)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Crossbow (Dark Ages)


Parada: Des + Arquearia
Dificuldade: 6
Dano: 3 (L)
Alcance: 90
Cadência: -
Pente: -
Ocultação: M

Notas: Força mínima 3. Perfuração de armadura 2.]==],
				},
				["Crossbow (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Crossbow (Mage)


Parada: Des + Arquearia
Dificuldade: 6
Dano: 5
Alcance: 90
Cadência: 1
Pente: 1
Ocultação: M

Notas: Bestas levam duas ações automáticas para recarregar.]==],
				},
				["Crossbow, Commando"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Crossbow, Commando


Parada: Des + Arquearia
Dificuldade: 6
Dano: 3
Alcance: 20
Cadência: 1
Pente: 1
Ocultação: R

Notas: Dobrável: um turno para abrir mais uma ação para carregar. Bestas levam duas ações automáticas para recarregar.]==],
				},
				["Crossbow, Hvy."] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Crossbow, Hvy.


Parada: Des + Arquearia
Dificuldade: 6
Dano: 6
Alcance: 100
Cadência: 1
Pente: 1
Ocultação: N

Notas: Bestas levam duas ações automáticas para recarregar.]==],
				},
				["Crowbar"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Crowbar


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R]==],
				},
				["Curbstomp"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Curbstomp


Parada: For + Briga
Dificuldade: 6
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Luta suja (mín. Briga 3). Contra oponente caído.]==],
				},
				["Dagger"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Dagger


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (L)
Alcance: 20
Cadência: -
Pente: -
Ocultação: R

Notas: Força mínima 2. Perfuração de armadura 2. Pode ser arremessada (alcance 20).]==],
				},
				["Death Strike"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Death Strike


Parada: Des + Artes Marciais
Dificuldade: 5
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Deflecting Block"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Deflecting Block


Parada: Des + Artes Marciais
Dificuldade: 6
Dano: For do Atacante (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Cada sucesso subtrai um sucesso da jogada do atacante; se o defensor vencer, o atacante rola Des (dificuldade 8) ou sofre a própria Força em dano de contusão.]==],
				},
				["Disarm"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Disarm


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: Especial
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Sucessos acima da Força do oponente arrancam a arma.]==],
				},
				["Disarm (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 448


Disarm (Mage)


Parada: Des + Armas Brancas
Dificuldade: 7/8
Dano: Especial
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Dificuldade +1 com arma; 8 com as mãos nuas (um dado a menos). Sucessos acima da Força do oponente derrubam a arma; falha crítica derruba a sua.]==],
				},
				["Dodge"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Dodge


Parada: Des + Esportes
Dificuldade: 6
Dano: Nenhum (R)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Precisão: especial. (R) reduz os sucessos de ataque do oponente.]==],
				},
				["Dragon Tail Sweep"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Dragon Tail Sweep


Parada: Des + Artes Marciais
Dificuldade: 8
Dano: For do Oponente (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Elbow/Knee Strike"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Elbow/Knee Strike


Parada: Des + Artes Marciais
Dificuldade: 5
Dano: For + 1 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Flamethrower"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


Flamethrower


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 3 níveis/turno (fogo)
Alcance: 60
Cadência: 1
Pente: 5
Ocultação: N

Notas: Arma militar; ver a tabela de Explosivos.]==],
				},
				["Flank/Rear Attack"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 448


Flank/Rear Attack


Parada: Des + Habilidade
Dificuldade: 5/4
Dano: Como o Ataque
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Dificuldade -1 pelo flanco, -2 pelas costas.]==],
				},
				["Flogger"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 451


Flogger


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Pode enredar um membro a dificuldade +1.]==],
				},
				["Flying Kick"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Flying Kick


Parada: Des + Artes Marciais
Dificuldade: 7
Dano: For + 2 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Full-Auto"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Full-Auto


Parada: Des + Armas de Fogo
Dificuldade: 8
Dano: Arma + 10 dados
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: +10 dados; esvazia o pente. Só armas capazes de fogo automático.]==],
				},
				["Grand Klaive"] = {
					pt = [==[Werewolf: The Apocalypse 20th Anniversary Edition, pág. 302


Grand Klaive


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 3 (A)
Alcance: -
Cadência: -
Pente: -
Ocultação: M

Notas: Fetiche de prata: lobisomens não absorvem o dano, salvo na forma natal.]==],
				},
				["Grapple"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 448


Grapple


Parada: For + Briga
Dificuldade: 6
Dano: For ou Nenhum
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Great Axe"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Great Axe


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 6 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Duas mãos; muito pesado, exige Força 3.]==],
				},
				["Great Blow"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Great Blow


Parada: Des + Briga/Armas Brancas
Dificuldade: 7
Dano: Normal + 2
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Dois dados de dano a mais que o ataque básico.]==],
				},
				["Great Sword"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Great Sword


Parada: Des + Armas Brancas
Dificuldade: 5
Dano: For + 6 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Duas mãos; muito pesado, exige Força 3.]==],
				},
				["Greatsword"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Greatsword


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 4 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 4. Duas mãos.]==],
				},
				["Hail of Arrows"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Hail of Arrows


Parada: Des + Arquearia
Dificuldade: 6
Dano: Arma
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Exige Arquearia 3; só a longo ou médio alcance; não faz parte de ação múltipla.]==],
				},
				["Halberd"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Halberd


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 4 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 3. Duas mãos. Dificuldade +1.]==],
				},
				["Hand Ax"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Hand Ax


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: M

Notas: Força mínima 3.]==],
				},
				["Hand Claws (large)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Hand Claws (large)


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: B]==],
				},
				["Hand Claws (small)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Hand Claws (small)


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: B]==],
				},
				["Hard/Soft Strike"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Hard/Soft Strike


Parada: Des + Artes Marciais
Dificuldade: 5/6
Dano: For + 1 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Dificuldade 5 no estilo duro / 6 no estilo suave.]==],
				},
				["Hatchet"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Hatchet


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R]==],
				},
				["Hatchet (Dark Ages)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Hatchet (Dark Ages)


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (L)
Alcance: 20
Cadência: -
Pente: -
Ocultação: R

Notas: Força mínima 2. Pode ser arremessada (alcance 20, dificuldade +1).]==],
				},
				["Haymaker"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Haymaker


Parada: Des + Briga
Dificuldade: 7
Dano: For + 2 (C) + Derrubada
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Luta suja (mín. Briga 3).]==],
				},
				["Head Butt"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Head Butt


Parada: Des + Briga
Dificuldade: 6
Dano: For + 1 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Luta suja (mín. Briga 3).]==],
				},
				["Heavy Crossbow"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Heavy Crossbow


Parada: Des + Arquearia
Dificuldade: 6
Dano: 4 (L)
Alcance: 90
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 4. Perfuração de armadura 3.]==],
				},
				["HIT Mark Chain-Gun"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


HIT Mark Chain-Gun


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 8
Alcance: 150
Cadência: 3
Pente: 200
Ocultação: N

Notas: Arma da Tecnocracia. Pode disparar fogo automático, rajadas e varredura.]==],
				},
				["Hold"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Hold


Parada: For + Briga
Dificuldade: 6
Dano: Nenhum (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: (C) continua nos turnos seguintes.]==],
				},
				["Hook Sword(s)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Hook Sword(s)


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 3 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: M

Notas: Usadas em par; exigem as duas mãos; +1 dado para bloquear; +2 dados para desarmar.]==],
				},
				["Huge Spiked Club"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Huge Spiked Club


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 4 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Duas mãos; muito pesado, exige Força 3.]==],
				},
				["Hunting Bow"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Hunting Bow


Parada: Des + Arquearia
Dificuldade: 6
Dano: 5
Alcance: 100
Cadência: 1
Pente: 1
Ocultação: N

Notas: Encaixar e retesar é ação automática; Arquearia 3 dispara numa única ação.]==],
				},
				["Impale"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Impale


Parada: Des + Arquearia
Dificuldade: 9
Dano: Especial
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Prender o alvo com uma flecha ou virote.]==],
				},
				["Iron Staff"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Iron Staff


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 3 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Duas mãos; muito pesado, exige Força 3.]==],
				},
				["Jab Pistol"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Jab Pistol


Parada: Des + Briga
Dificuldade: 6
Dano: Como a Arma de Fogo + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Luta suja (mín. Briga 3). Arma encostada no alvo.]==],
				},
				["Javelin"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Javelin


Parada: Des + Esportes
Dificuldade: 6
Dano: For + 2 (L)
Alcance: 50
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 2. Perfuração de armadura 2. Em combate corpo a corpo: For (L), Força mínima 2.]==],
				},
				["Joint Lock"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Joint Lock


Parada: Des + Artes Marciais
Dificuldade: 5
Dano: Agarrão + Sucessos (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Katana"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Katana


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 3 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: M

Notas: Com as duas mãos soma um dado de dano.]==],
				},
				["Katar"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Katar


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2
Alcance: -
Cadência: -
Pente: -
Ocultação: R

Notas: Penetra até três pontos de armadura; +1 dado para bloquear.]==],
				},
				["Kick"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Kick


Parada: Des + Briga
Dificuldade: 7
Dano: For + 1
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Kick (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 448


Kick (Mage)


Parada: Des + Briga
Dificuldade: 7
Dano: For + 1 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Klaive"] = {
					pt = [==[Werewolf: The Apocalypse 20th Anniversary Edition, pág. 302


Klaive


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (A)
Alcance: -
Cadência: -
Pente: -
Ocultação: R

Notas: Fetiche de prata: lobisomens não absorvem o dano, salvo na forma natal.]==],
				},
				["Knife"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 280


Knife


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R]==],
				},
				["Knife (Dark Ages)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Knife (Dark Ages)


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For (L)
Alcance: 15
Cadência: -
Pente: -
Ocultação: B

Notas: Força mínima 1. Pode ser arremessada (alcance 15, dificuldade +1).]==],
				},
				["Knife (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Knife (Mage)


Parada: Des + Armas Brancas
Dificuldade: 4
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: B]==],
				},
				["Knife, Thrown"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


Knife, Thrown


Parada: Des + Esportes
Dificuldade: 6
Dano: For (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: B]==],
				},
				["Kusarigama"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 451


Kusarigama


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 3 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: M

Notas: Exige as duas mãos; +2 dados para desarmar; pode enredar a dificuldade +1.]==],
				},
				["Lance (Mounted)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Lance (Mounted)


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 3 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 3. Perfuração de armadura 3.]==],
				},
				["Long Bow"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Long Bow


Parada: Des + Arquearia
Dificuldade: 6
Dano: 5
Alcance: 120
Cadência: 1
Pente: 1
Ocultação: N

Notas: Encaixar e retesar é ação automática; Arquearia 3 dispara numa única ação.]==],
				},
				["Longbow"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Longbow


Parada: Des + Arquearia
Dificuldade: 6
Dano: 4 (L)
Alcance: 120
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 4. Perfuração de armadura 4.]==],
				},
				["Low Blow"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Low Blow


Parada: Des + Briga
Dificuldade: 7
Dano: For + Atordoamento (C ou L)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Luta suja (mín. Briga 3).]==],
				},
				["M-19 Grenade Launcher"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


M-19 Grenade Launcher


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 8
Alcance: 600
Cadência: 2
Pente: 1
Ocultação: N

Notas: Arma militar; não portátil, montada em veículo; ver a tabela de Explosivos.]==],
				},
				["M-79 Grenade Launcher"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


M-79 Grenade Launcher


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 6
Alcance: 400
Cadência: 1
Pente: 1
Ocultação: N

Notas: Arma militar; ver a tabela de Explosivos.]==],
				},
				["Mace"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Mace


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N]==],
				},
				["Mace (Dark Ages)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Mace (Dark Ages)


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: M

Notas: Força mínima 3.]==],
				},
				["Manriki-Gusari"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 451


Manriki-Gusari


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: M

Notas: Exige as duas mãos; +2 dados para desarmar; pode enredar a dificuldade +1.]==],
				},
				["Martial Arts Disarm"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Martial Arts Disarm


Parada: Des + Artes Marciais
Dificuldade: 7
Dano: 3
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Desarme com as mãos nuas; mínimo de três pontos em Artes Marciais.]==],
				},
				["Morning Star"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Morning Star


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 3 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: M

Notas: Força mínima 3.]==],
				},
				["Multiple Shots"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Multiple Shots


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: Arma
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Precisão: especial (a parada é dividida entre os tiros).]==],
				},
				["Nerve Strike"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Nerve Strike


Parada: Des + Artes Marciais
Dificuldade: 7
Dano: For + 3 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Com três ou mais sucessos, o alvo rola Vigor (dificuldade 8) ou fica atordoado no turno seguinte.]==],
				},
				["Nunchaku"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Nunchaku


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 2 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: M

Notas: +1 dado para bloquear; dificuldade +1 para o bloqueio do oponente.]==],
				},
				["Pacification Spray"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


Pacification Spray


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 5 (C)
Alcance: 3
Cadência: 1
Pente: 5
Ocultação: B

Notas: Tecnocrático. Contusão; sem dano extra por sucessos. O alvo perde dois dados por um turno por sucesso.]==],
				},
				["Parry"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Parry


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: Nenhum (R)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Precisão: especial. (R) reduz os sucessos de ataque do oponente.]==],
				},
				["Pick Ax"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Pick Ax


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 4. Perfuração de armadura 3.]==],
				},
				["Pistol Whip"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Pistol Whip


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Luta suja (mín. Briga 3).]==],
				},
				["Pistol, Hvy."] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 281


Pistol, Hvy.


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 5
Alcance: 25
Cadência: 3
Pente: 13+1
Ocultação: R

Notas: Exemplo: Springfield XDM (.45 ACP). Letal contra mortais; contusão contra Membros, salvo mira na cabeça.]==],
				},
				["Pistol, Lt."] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 281


Pistol, Lt.


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 4
Alcance: 20
Cadência: 4
Pente: 15+1
Ocultação: B

Notas: Exemplo: HK USP (9mm). Letal contra mortais; contusão contra Membros, salvo mira na cabeça.]==],
				},
				["Pitchfork"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Pitchfork


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 2. Perfuração de armadura 1. Duas mãos.]==],
				},
				["Point Blank"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Point Blank


Parada: Des + Armas de Fogo
Dificuldade: 4
Dano: Arma
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: A até dois metros.]==],
				},
				["Polearm"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Polearm


Parada: Des + Armas Brancas
Dificuldade: 7
Dano: For + 3 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Exige as duas mãos; dificuldade +2 com uma mão.]==],
				},
				["Punch"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 448


Punch


Parada: Des + Briga
Dificuldade: 6
Dano: For (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Quarterstaff"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Quarterstaff


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 3 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 2. +2 dados para Rasteira.]==],
				},
				["Reading Opponent"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 448


Reading Opponent


Parada: Per + Traço
Dificuldade: 6
Dano: Especial
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Jogada resistida, Percepção + Traço de combate contra Raciocínio + Traço de combate do oponente; cada sucesso soma um dado à próxima ação.]==],
				},
				["Revolver, Hvy."] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 281


Revolver, Hvy.


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 6
Alcance: 35
Cadência: 2
Pente: 6
Ocultação: R

Notas: Exemplo: Ruger Redhawk (.44 Magnum). Letal contra mortais; contusão contra Membros, salvo mira na cabeça.]==],
				},
				["Revolver, Lt."] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 281


Revolver, Lt.


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 4
Alcance: 12
Cadência: 3
Pente: 6
Ocultação: B

Notas: Exemplo: SW Bodyguard (.38 Special). Letal contra mortais; contusão contra Membros, salvo mira na cabeça.]==],
				},
				["Rifle"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 281


Rifle


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 8
Alcance: 200
Cadência: 1
Pente: 3+1
Ocultação: N

Notas: Exemplo: Beretta Tikka T3 (30.06). Letal contra mortais; contusão contra Membros, salvo mira na cabeça.]==],
				},
				["Rifle (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Rifle (Mage)


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 8
Alcance: 200
Cadência: 1
Pente: 5+1
Ocultação: N

Notas: Exemplo: Remington M-700 (30.06).]==],
				},
				["Riot Baton"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Riot Baton


Parada: Des + Armas Brancas
Dificuldade: 5
Dano: For + 1 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: M]==],
				},
				["Riposte"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Riposte


Parada: Des + Briga/Armas Brancas
Dificuldade: 7
Dano: Normal + 1
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Contra-ataque depois de aparar ou bloquear com sucesso.]==],
				},
				["Rock"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Rock


Parada: Des + Esportes
Dificuldade: 7
Dano: For (C)
Alcance: 40
Cadência: -
Pente: -
Ocultação: B

Notas: Força mínima 2. Dificuldade +1.]==],
				},
				["Rocket Launcher"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


Rocket Launcher


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 12-16
Alcance: 500+
Cadência: 1
Pente: 1
Ocultação: N

Notas: Arma militar; ver a tabela de Explosivos.]==],
				},
				["Saber"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Saber


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: M

Notas: Força mínima 3.]==],
				},
				["Sai"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Sai


Parada: Des + Armas Brancas
Dificuldade: 5
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R

Notas: +1 dado para bloquear; +2 dados para desarmar.]==],
				},
				["Sap"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 280


Sap


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: B

Notas: Contundente: dano de contusão, salvo mira na cabeça (letal).]==],
				},
				["Sap (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Sap (Mage)


Parada: Des + Armas Brancas
Dificuldade: 4
Dano: For + 1 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: B]==],
				},
				["Sap (Werewolf)"] = {
					pt = [==[Werewolf: The Apocalypse 20th Anniversary Edition, pág. 302


Sap (Werewolf)


Parada: Des + Armas Brancas
Dificuldade: 4
Dano: For (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: B]==],
				},
				["Semi-Automatic Pistol, Hvy."] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Semi-Automatic Pistol, Hvy.


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 5
Alcance: 30
Cadência: 3
Pente: 7+1
Ocultação: R

Notas: Exemplo: IMI Desert Eagle (.50 AE).]==],
				},
				["Semi-Automatic Pistol, Lt."] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Semi-Automatic Pistol, Lt.


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 4
Alcance: 20
Cadência: 4
Pente: 17+1
Ocultação: B

Notas: Exemplo: Glock 17 (9mm). Todo dano de arma de fogo é letal.]==],
				},
				["Short Bow"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Short Bow


Parada: Des + Arquearia
Dificuldade: 6
Dano: 4
Alcance: 60
Cadência: 1
Pente: 1
Ocultação: N

Notas: Encaixar e retesar é ação automática; Arquearia 3 dispara numa única ação.]==],
				},
				["Short Sword"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Short Sword


Parada: Des + Armas Brancas
Dificuldade: 5
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R]==],
				},
				["Shortbow"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Shortbow


Parada: Des + Arquearia
Dificuldade: 6
Dano: 2 (L)
Alcance: 60
Cadência: -
Pente: -
Ocultação: M

Notas: Força mínima 3. Perfuração de armadura 2.]==],
				},
				["Shotgun"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 281


Shotgun


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 8
Alcance: 20
Cadência: 1
Pente: 5+1
Ocultação: M

Notas: Exemplo: Remington 870 (calibre 12). Letal contra mortais; contusão contra Membros, salvo mira na cabeça.]==],
				},
				["Shotgun, Assault"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Shotgun, Assault


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 8
Alcance: 50
Cadência: 3
Pente: 32+1
Ocultação: N

Notas: Exemplo: MPS AA-12 (calibre 12). Pode disparar fogo automático, rajadas de 3 tiros e varredura.]==],
				},
				["Shotgun, Sawed Off"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Shotgun, Sawed Off


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 8
Alcance: 10
Cadência: 2
Pente: 2
Ocultação: R

Notas: Exemplo: Winchester Model 24 de cano duplo (calibre 12).]==],
				},
				["Shotgun, Semi-auto"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 281


Shotgun, Semi-auto


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 8
Alcance: 20
Cadência: 3
Pente: 6+1
Ocultação: M

Notas: Exemplo: Benelli M4 Super 90 (calibre 12). Letal contra mortais; contusão contra Membros, salvo mira na cabeça.]==],
				},
				["Shotgun, Semi-Automatic"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


Shotgun, Semi-Automatic


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 8
Alcance: 25
Cadência: 3
Pente: 6+1
Ocultação: M

Notas: Exemplo: Benelli M4 (calibre 12).]==],
				},
				["Shuriken"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


Shuriken


Parada: Des + Esportes
Dificuldade: 7
Dano: 3 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: B]==],
				},
				["Sling"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Sling


Parada: Des + Arquearia
Dificuldade: 6
Dano: 3 (C)
Alcance: 40
Cadência: -
Pente: -
Ocultação: B

Notas: Força mínima 2.]==],
				},
				["SMG, Large"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 281


SMG, Large


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 4
Alcance: 50
Cadência: 3
Pente: 30+1
Ocultação: M

Notas: Exemplo: HK MP5 (9mm). Capaz de rajadas de 3 tiros, fogo automático e varredura.]==],
				},
				["SMG, Small"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 281


SMG, Small


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 4
Alcance: 20
Cadência: 3
Pente: 17+1
Ocultação: R

Notas: Exemplo: Glock 18 (9mm). Capaz de rajadas de 3 tiros, fogo automático e varredura.]==],
				},
				["SMG, Small (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 452


SMG, Small (Mage)


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 4
Alcance: 25
Cadência: 3
Pente: 30+1
Ocultação: R

Notas: Exemplo: Ingram Mac-10 (9mm). Pode disparar fogo automático, rajadas de 3 tiros e varredura.]==],
				},
				["Snake Step"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Snake Step


Parada: Des + Artes Marciais
Dificuldade: 6/5
Dano: Esquiva + 3 dados
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Dificuldade 6 no estilo duro / 5 no estilo suave.]==],
				},
				["Snap Kick"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Snap Kick


Parada: Des + Artes Marciais
Dificuldade: 5
Dano: For + 1 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Spear"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


Spear


Parada: Des + Esportes
Dificuldade: 6
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N]==],
				},
				["Spear (Dark Ages)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Spear (Dark Ages)


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (L)
Alcance: 40
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 2. Perfuração de armadura 2. Com as duas mãos e Força mínima 3: For + 3 (L). Pode ser arremessada (alcance 40).]==],
				},
				["Spiked Club"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Spiked Club


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: M]==],
				},
				["Spiked Gauntlet"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Spiked Gauntlet


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R]==],
				},
				["Spinning Kick"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Spinning Kick


Parada: Des + Artes Marciais
Dificuldade: 6
Dano: For + 3 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Staff"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Staff


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: N]==],
				},
				["Stake"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 280


Stake


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: M

Notas: Pode paralisar um vampiro se cravada no coração: mirar o coração (dificuldade 9) e obter três sucessos de dano.]==],
				},
				["Stake (Dark Ages)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Stake (Dark Ages)


Parada: Des + Armas Brancas
Dificuldade: 9
Dano: Especial
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Cravar uma estaca no coração de um vampiro: dano conforme a arma ou For + 1 (L).]==],
				},
				["Stiletto"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Stiletto


Parada: Des + Armas Brancas
Dificuldade: 4
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: B

Notas: Penetra até três pontos de armadura.]==],
				},
				["Stone"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


Stone


Parada: Des + Esportes
Dificuldade: 5
Dano: For (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: varia]==],
				},
				["Stone, Large"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


Stone, Large


Parada: Des + Esportes
Dificuldade: 5
Dano: For + 3 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: N]==],
				},
				["Strafing"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Strafing


Parada: Des + Armas de Fogo
Dificuldade: 8
Dano: Especial
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Precisão +10. Esvazia o pente numa área (máx. três metros).]==],
				},
				["Strike"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Strike


Parada: Des + Briga
Dificuldade: 6
Dano: For
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Suppressive Fire"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Suppressive Fire


Parada: Des + Arquearia
Dificuldade: 4
Dano: Arma
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Segura um oponente que avança; cada sucesso pode dar -1 de dificuldade a um aliado.]==],
				},
				["Sweep"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Sweep


Parada: Des + Briga/Armas Brancas
Dificuldade: 7
Dano: For (K)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: (K) causa derrubada.]==],
				},
				["Sweep (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 448


Sweep (Mage)


Parada: Des + Briga
Dificuldade: 8
Dano: Especial
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Derrubada: o oponente vai ao chão.]==],
				},
				["Sword"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 280


Sword


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: M]==],
				},
				["Table"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Table


Parada: Des + Armas Brancas
Dificuldade: 8
Dano: For + 3 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Duas mãos; muito pesado, exige Força 3.]==],
				},
				["Tackle"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Tackle


Parada: For + Briga
Dificuldade: 7
Dano: For + 1 (K)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: (K) causa derrubada. O atacante rola Des + Esportes (dificuldade 8) ou cai também.]==],
				},
				["Tackle (Mage)"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 448


Tackle (Mage)


Parada: Des + Briga
Dificuldade: 7
Dano: For + Especial (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Exige dois metros de impulso; ambos rolam Des + Esportes ou vão ao chão. Pode ferir o atacante.]==],
				},
				["Taser"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


Taser


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 5 (C)
Alcance: 5
Cadência: 1
Pente: 1
Ocultação: B

Notas: Dano de contusão; sem dano extra por sucessos.]==],
				},
				["Tear Gas"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


Tear Gas


Parada: Des + Armas de Fogo
Dificuldade: 6
Dano: 3 (C)
Alcance: 3
Cadência: 1
Pente: 5
Ocultação: B

Notas: Contusão; sem dano extra por sucessos. O alvo perde dois dados por um turno por sucesso.]==],
				},
				["Throw"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Throw


Parada: Des + Artes Marciais
Dificuldade: 7/6
Dano: For + Movimento (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Dificuldade 7 no estilo duro / 6 no estilo suave. Parada igual ou maior que a Destreza do oponente o arremessa um metro por sucesso.]==],
				},
				["Thunder Kick"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Thunder Kick


Parada: Des + Artes Marciais
Dificuldade: 7
Dano: For + 3 + Sucessos (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Tomahawk"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Tomahawk


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R]==],
				},
				["Tomahawk, Thrown"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 453


Tomahawk, Thrown


Parada: Des + Esportes
Dificuldade: 6
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R]==],
				},
				["Two Weapons"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Two Weapons


Parada: Des + Armas de Fogo
Dificuldade: 6/7
Dano: Arma
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Dificuldade +1 para a arma da mão inábil. Duas jogadas, como ação múltipla.]==],
				},
				["Vital Strike"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Vital Strike


Parada: Des + Artes Marciais
Dificuldade: 7
Dano: For (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["War Fan"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


War Fan


Parada: Des + Armas Brancas
Dificuldade: 5
Dano: For + 2 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R

Notas: +1 dado para bloquear; dificuldade +1 para o bloqueio do oponente.]==],
				},
				["Warhammer"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 349


Warhammer


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 4 (C)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: Força mínima 4. Duas mãos.]==],
				},
				["Weapon Strike"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 279


Weapon Strike


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: Arma
Alcance: -
Cadência: -
Pente: -
Ocultação: -

Notas: Dano conforme a arma (Tabela de Armas Brancas).]==],
				},
				["Whip"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 451


Whip


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R

Notas: Pode enredar um membro a dificuldade +1.]==],
				},
				["Whip (Werewolf)"] = {
					pt = [==[Werewolf: The Apocalypse 20th Anniversary Edition, pág. 302


Whip (Werewolf)


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 1 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: R

Notas: Pode enredar um membro a dificuldade +1.]==],
				},
				["Wind and Fire Wheel"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 450


Wind and Fire Wheel


Parada: Des + Armas Brancas
Dificuldade: 6
Dano: For + 3 (L)
Alcance: -
Cadência: -
Pente: -
Ocultação: N

Notas: +2 dados para desarmar.]==],
				},
				["Withering Grasp"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 449


Withering Grasp


Parada: Des + Artes Marciais
Dificuldade: 7
Dano: For (C) + Desarme
Alcance: -
Cadência: -
Pente: -
Ocultação: -]==],
				},
				["Conceal"] = {
					pt = [==[Vampire: The Classical Age 20th Anniversary Edition, pág. 330


Conceal


B = Bolsa · R = Roupa Solta · M = Manto Longo · N = Não Pode Ser Escondido. varia = depende do item.]==],
				},
				-- <<< WEAPON_DESC_END
};
