-- Weapon descriptions, the [en] half (SPEC I157h, I21, V210 / T1004).
--
-- One entry per item of PICKER_LIST["weapon"], keyed in ENGLISH because that is what the sheet
-- saves (SPEC V24). Three blocks, exactly as the twelve description modules already do:
-- "<Book>, p. <n>" - blank - blank - <Name> - blank - blank - <text>. The book title does
-- not translate; only p./pag. does (SPEC I100e).
--
-- One module PER LANGUAGE and never both halves in one file (SPEC V210): half of every
-- module was the language the session never opens, and require pulled both in to read one.
-- The renderer builds the name by concatenation - require("desc<Kind>_" .. half .. ".lua")
-- and never a constant name (SPEC V210b).
--
-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24).
-- Generated by research/gen_combat_data.ps1 from research/weapon.tsv and
-- research/armor.tsv. Do not hand-edit.

return {
				-- >>> WEAPON_DESC_BEGIN (generated - SPEC T1004)
				[".30 Caliber Machine Gun"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


.30 Caliber Machine Gun


Roll: Dex + Firearms
Difficulty: 6
Damage: 12
Range: 800
Rate: 5
Clip: 100
Conceal: N

Notes: Military weapon: Firearms specialty in Heavy Weapons. May fire full-auto, bursts and sprays.]==],
				},
				[".50 Caliber Machine Gun"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


.50 Caliber Machine Gun


Roll: Dex + Firearms
Difficulty: 6
Damage: 16
Range: 1000
Rate: 5
Clip: 200
Conceal: N

Notes: Military weapon; not man-portable, vehicle-mounted. May fire full-auto, bursts and sprays.]==],
				},
				["30 mm Cannon"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


30 mm Cannon


Roll: Dex + Firearms
Difficulty: 6
Damage: 15
Range: 1200
Rate: 8
Clip: 100
Conceal: N

Notes: Military chain-gun carried by HIT Marks and heavy cyborgs; halves armor protection.]==],
				},
				["3-Round Burst"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


3-Round Burst


Roll: Dex + Firearms
Difficulty: 7
Damage: Weapon
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Accuracy +2. Uses three bullets from the clip.]==],
				},
				["Aiming"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Aiming


Roll: Dex + Firearms
Difficulty: 6
Damage: Weapon
Range: -
Rate: -
Clip: -
Conceal: -

Notes: +2 dice to hit per turn spent aiming.]==],
				},
				["Aiming (Dark Ages)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Aiming (Dark Ages)


Roll: Dex + Archery
Difficulty: 6
Damage: Weapon
Range: -
Rate: -
Clip: -
Conceal: -

Notes: +1 die per turn spent aiming.]==],
				},
				["Assault Rifle"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 281


Assault Rifle


Roll: Dex + Firearms
Difficulty: 6
Damage: 7
Range: 150
Rate: 3
Clip: 30+1
Conceal: N

Notes: Example: FN SCAR (5.56mm). Capable of three-round bursts, full auto and sprays.]==],
				},
				["Assault Rifle (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Assault Rifle (Mage)


Roll: Dex + Firearms
Difficulty: 6
Damage: 7
Range: 150
Rate: 3
Clip: 42+1
Conceal: N

Notes: Example: AK-47 (7.62x39mm). May fire full-auto, three-round bursts and strafing sprays.]==],
				},
				["Automatic Fire"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Automatic Fire


Roll: Dex + Firearms
Difficulty: 8
Damage: Special
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Accuracy +10. Empties the clip. Only weapons marked for full auto.]==],
				},
				["Axe"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 280


Axe


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 3 (L)
Range: -
Rate: -
Clip: -
Conceal: N]==],
				},
				["Axe (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Axe (Mage)


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 3 (L)
Range: -
Rate: -
Clip: -
Conceal: N]==],
				},
				["Axe (Werewolf)"] = {
					en = [==[Werewolf: The Apocalypse 20th Anniversary Edition, p. 302


Axe (Werewolf)


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 3 (L)
Range: -
Rate: -
Clip: -
Conceal: T]==],
				},
				["Barbed Cat"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 451


Barbed Cat


Roll: Dex + Melee
Difficulty: 6
Damage: Str (L)
Range: -
Rate: -
Clip: -
Conceal: J

Notes: May entangle a limb at +1 difficulty.]==],
				},
				["Baseball Bat"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Baseball Bat


Roll: Dex + Melee
Difficulty: 5
Damage: Str + 2 (B)
Range: -
Rate: -
Clip: -
Conceal: T]==],
				},
				["Battle-Ax"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Battle-Ax


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 4 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 4. Two-handed.]==],
				},
				["Bear Mace"] = {
					en = [==[Werewolf: The Apocalypse 20th Anniversary Edition, p. 303


Bear Mace


Roll: Dex + Firearms
Difficulty: 6
Damage: 4 (B)
Range: 3
Rate: 1
Clip: 3
Conceal: P

Notes: Bashing; no extra damage from successes. Target loses two dice for one turn per success.]==],
				},
				["Biggs Mjollner Mk. IV"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Biggs Mjollner Mk. IV


Roll: Dex + Firearms
Difficulty: 6
Damage: 10
Range: 100
Rate: 1
Clip: 10
Conceal: T

Notes: Technocracy sidearm. Tends to jam on a failed roll in unEnlightened hands.]==],
				},
				["Biggs X-5 Model A Protector"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Biggs X-5 Model A Protector


Roll: Dex + Firearms
Difficulty: 6
Damage: 5
Range: 40
Rate: 4
Clip: 12+1
Conceal: J

Notes: Technocracy sidearm. May fire full-auto, bursts and sprays; composite, invisible to metal detectors.]==],
				},
				["Biggs X-5 Model R Protector"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Biggs X-5 Model R Protector


Roll: Dex + Firearms
Difficulty: 6
Damage: 5
Range: 40
Rate: 4
Clip: 12
Conceal: J

Notes: Technocracy sidearm. Revolver that chambers any loaded ammunition type at a button press; composite, invisible to metal detectors.]==],
				},
				["Bite"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Bite


Roll: Dex + Brawl
Difficulty: 6
Damage: Str + 1 (A)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Accuracy +1. Needs a successful clinch, hold or tackle first. (A) aggravated damage.]==],
				},
				["Bite (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 448


Bite (Mage)


Roll: Dex + Brawl
Difficulty: 5
Damage: Str + 1 to + 3 (B or L)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Damage bonus and type depend on the biter's jaws.]==],
				},
				["Blinding"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Blinding


Roll: Dex + Subterfuge
Difficulty: 9
Damage: Special
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Dirty fighting (min. Brawl 3). Enemy blinded one turn per success and loses two dice until he recovers.]==],
				},
				["Block"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Block


Roll: Dex + Brawl
Difficulty: 6
Damage: None (R)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Accuracy: special. (R) reduces an opponent's attack successes.]==],
				},
				["Body Slam"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Body Slam


Roll: Dex + Brawl
Difficulty: 6
Damage: Str + 2 (B or L)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Dirty fighting (min. Brawl 3).]==],
				},
				["Bolan Mk.13 Weapons System"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Bolan Mk.13 Weapons System


Roll: Dex + Firearms
Difficulty: 6
Damage: -
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Technocracy weapon: SMG (as AK-47, 50-shot clip) plus auto-shotgun (as MPS AA-12, 20-shot clip) plus grenade launcher (as M-79, six-shot magazine). Laser sights; requires Strength 3.]==],
				},
				["Brass Knuckles"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Brass Knuckles


Roll: Dex + Melee
Difficulty: 6
Damage: Str (L)
Range: -
Rate: -
Clip: -
Conceal: P]==],
				},
				["Broadsword"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Broadsword


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 3. May be used two-handed with min. Strength 2: Str + 3 (L).]==],
				},
				["Broken Bottle"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Broken Bottle


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: P

Notes: Breaks after three uses.]==],
				},
				["Bullwhip"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 451


Bullwhip


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: J

Notes: May entangle a limb at +1 difficulty.]==],
				},
				["Castle-Graves WW-3"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Castle-Graves WW-3


Roll: Dex + Firearms
Difficulty: 6
Damage: 8
Range: 200
Rate: 3
Clip: 50+1
Conceal: N

Notes: Technocracy weapon. May fire full-auto, bursts and sprays.]==],
				},
				["Chain"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 451


Chain


Roll: Dex + Melee
Difficulty: 5
Damage: Str (B)
Range: -
Rate: -
Clip: -
Conceal: J

Notes: May entangle a limb at +1 difficulty.]==],
				},
				["Chain Whip"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 451


Chain Whip


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: J

Notes: May entangle a limb at +1 difficulty.]==],
				},
				["Chainsaw"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Chainsaw


Roll: Dex + Melee
Difficulty: 8
Damage: Str + 7 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: On a botch the user hurts himself.]==],
				},
				["Chair"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Chair


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 2 (B)
Range: -
Rate: -
Clip: -
Conceal: N]==],
				},
				["Claw"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Claw


Roll: Dex + Brawl
Difficulty: 6
Damage: Str + 1 (A)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Vampires with claws (Protean, Vicissitude). (A) aggravated damage.]==],
				},
				["Claw (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 448


Claw (Mage)


Roll: Dex + Brawl
Difficulty: 6
Damage: Str + 1 to + 3 (L or A)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Damage bonus and type depend on the claws.]==],
				},
				["Clinch"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Clinch


Roll: Str + Brawl
Difficulty: 6
Damage: Str (C)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Accuracy: special. (C) carries over on successive turns.]==],
				},
				["Clinch (Dark Ages)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Clinch (Dark Ages)


Roll: Dex + Brawl
Difficulty: 6
Damage: Str (C)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: (C) continues into further turns.]==],
				},
				["Club"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 280


Club


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (B)
Range: -
Rate: -
Clip: -
Conceal: T

Notes: Blunt: bashing damage unless targeted at the head (lethal).]==],
				},
				["Club (Dark Ages)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Club (Dark Ages)


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (B)
Range: -
Rate: -
Clip: -
Conceal: C

Notes: Min. Strength 2.]==],
				},
				["Counter Throw"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Counter Throw


Roll: Dex + Martial Arts
Difficulty: 6
Damage: Special
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Resisted roll of Dex + Martial Arts against the attacker's Dex + Brawl, Melee or Martial Arts; success deflects the attack and may Throw the attacker.]==],
				},
				["Crossbow"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 281


Crossbow


Roll: Dex + Firearms
Difficulty: 6
Damage: 5
Range: 20
Rate: 1
Clip: 1
Conceal: T

Notes: Five turns to reload. Bashing vs. Kindred unless aimed at the head or heart; lethal vs. mortals. Included for staking.]==],
				},
				["Crossbow (Dark Ages)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Crossbow (Dark Ages)


Roll: Dex + Archery
Difficulty: 6
Damage: 3 (L)
Range: 90
Rate: -
Clip: -
Conceal: L

Notes: Min. Strength 3. Armor piercing 2.]==],
				},
				["Crossbow (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Crossbow (Mage)


Roll: Dex + Archery
Difficulty: 6
Damage: 5
Range: 90
Rate: 1
Clip: 1
Conceal: T

Notes: Crossbows take two automatic actions to reload.]==],
				},
				["Crossbow, Commando"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Crossbow, Commando


Roll: Dex + Archery
Difficulty: 6
Damage: 3
Range: 20
Rate: 1
Clip: 1
Conceal: J

Notes: Collapsible: one turn to unfold plus one action to load. Crossbows take two automatic actions to reload.]==],
				},
				["Crossbow, Hvy."] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Crossbow, Hvy.


Roll: Dex + Archery
Difficulty: 6
Damage: 6
Range: 100
Rate: 1
Clip: 1
Conceal: N

Notes: Crossbows take two automatic actions to reload.]==],
				},
				["Crowbar"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Crowbar


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: J]==],
				},
				["Curbstomp"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Curbstomp


Roll: Str + Brawl
Difficulty: 6
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Dirty fighting (min. Brawl 3). Against a downed opponent.]==],
				},
				["Dagger"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Dagger


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (L)
Range: 20
Rate: -
Clip: -
Conceal: C

Notes: Min. Strength 2. Armor piercing 2. Can be thrown (range 20).]==],
				},
				["Death Strike"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Death Strike


Roll: Dex + Martial Arts
Difficulty: 5
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Deflecting Block"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Deflecting Block


Roll: Dex + Martial Arts
Difficulty: 6
Damage: Attacker's Str (B)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Each success subtracts one success from the attacker's roll; if the defender wins, the attacker rolls Dex (difficulty 8) or takes own Strength in bashing damage.]==],
				},
				["Disarm"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Disarm


Roll: Dex + Melee
Difficulty: 7
Damage: Special
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Successes exceeding the opponent's Strength knock the weapon away.]==],
				},
				["Disarm (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 448


Disarm (Mage)


Roll: Dex + Melee
Difficulty: 7/8
Damage: Special
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Difficulty +1 with a weapon; 8 bare-handed (one die less). Successes above the opponent's Strength drop the weapon; a botch drops your own.]==],
				},
				["Dodge"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Dodge


Roll: Dex + Athletics
Difficulty: 6
Damage: None (R)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Accuracy: special. (R) reduces an opponent's attack successes.]==],
				},
				["Dragon Tail Sweep"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Dragon Tail Sweep


Roll: Dex + Martial Arts
Difficulty: 8
Damage: Opponent's Str (B)
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Elbow/Knee Strike"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Elbow/Knee Strike


Roll: Dex + Martial Arts
Difficulty: 5
Damage: Str + 1 (B)
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Flamethrower"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


Flamethrower


Roll: Dex + Firearms
Difficulty: 6
Damage: 3 levels/turn (fire)
Range: 60
Rate: 1
Clip: 5
Conceal: N

Notes: Military weapon; see the Explosives chart.]==],
				},
				["Flank/Rear Attack"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 448


Flank/Rear Attack


Roll: Dex + Ability
Difficulty: 5/4
Damage: As Attack
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Difficulty -1 from the flank, -2 from the rear.]==],
				},
				["Flogger"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 451


Flogger


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (B)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: May entangle a limb at +1 difficulty.]==],
				},
				["Flying Kick"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Flying Kick


Roll: Dex + Martial Arts
Difficulty: 7
Damage: Str + 2 (B)
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Full-Auto"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Full-Auto


Roll: Dex + Firearms
Difficulty: 8
Damage: Weapon + 10 dice
Range: -
Rate: -
Clip: -
Conceal: -

Notes: +10 dice; empties the clip. Only weapons marked for full auto.]==],
				},
				["Grand Klaive"] = {
					en = [==[Werewolf: The Apocalypse 20th Anniversary Edition, p. 302


Grand Klaive


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 3 (A)
Range: -
Rate: -
Clip: -
Conceal: T

Notes: Silver fetish weapon: werewolves cannot soak the damage except in breed form.]==],
				},
				["Grapple"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 448


Grapple


Roll: Str + Brawl
Difficulty: 6
Damage: Str or None
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Great Axe"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Great Axe


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 6 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Two-handed; very heavy, requires Strength 3.]==],
				},
				["Great Blow"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Great Blow


Roll: Dex + Brawl/Melee
Difficulty: 7
Damage: Normal + 2
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Two more damage dice than the base attack.]==],
				},
				["Great Sword"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Great Sword


Roll: Dex + Melee
Difficulty: 5
Damage: Str + 6 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Two-handed; very heavy, requires Strength 3.]==],
				},
				["Greatsword"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Greatsword


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 4 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 4. Two-handed.]==],
				},
				["Hail of Arrows"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Hail of Arrows


Roll: Dex + Archery
Difficulty: 6
Damage: Weapon
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Requires Archery 3; long or medium range only; not part of a multiple action.]==],
				},
				["Halberd"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Halberd


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 4 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 3. Two-handed. Difficulty +1.]==],
				},
				["Hand Ax"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Hand Ax


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: L

Notes: Min. Strength 3.]==],
				},
				["Hand Claws (large)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Hand Claws (large)


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: P]==],
				},
				["Hand Claws (small)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Hand Claws (small)


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: P]==],
				},
				["Hard/Soft Strike"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Hard/Soft Strike


Roll: Dex + Martial Arts
Difficulty: 5/6
Damage: Str + 1 (B)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Difficulty 5 hard style / 6 soft style.]==],
				},
				["Hatchet"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Hatchet


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: J]==],
				},
				["Hatchet (Dark Ages)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Hatchet (Dark Ages)


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (L)
Range: 20
Rate: -
Clip: -
Conceal: C

Notes: Min. Strength 2. Can be thrown (range 20, +1 difficulty).]==],
				},
				["Haymaker"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Haymaker


Roll: Dex + Brawl
Difficulty: 7
Damage: Str + 2 (B) + Knockdown
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Dirty fighting (min. Brawl 3).]==],
				},
				["Head Butt"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Head Butt


Roll: Dex + Brawl
Difficulty: 6
Damage: Str + 1 (B)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Dirty fighting (min. Brawl 3).]==],
				},
				["Heavy Crossbow"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Heavy Crossbow


Roll: Dex + Archery
Difficulty: 6
Damage: 4 (L)
Range: 90
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 4. Armor piercing 3.]==],
				},
				["HIT Mark Chain-Gun"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


HIT Mark Chain-Gun


Roll: Dex + Firearms
Difficulty: 6
Damage: 8
Range: 150
Rate: 3
Clip: 200
Conceal: N

Notes: Technocracy weapon. May fire full-auto, bursts and sprays.]==],
				},
				["Hold"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Hold


Roll: Str + Brawl
Difficulty: 6
Damage: None (C)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: (C) carries over on successive turns.]==],
				},
				["Hook Sword(s)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Hook Sword(s)


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 3 (L)
Range: -
Rate: -
Clip: -
Conceal: T

Notes: Used as a pair; requires two hands; +1 die to block; +2 dice to disarm.]==],
				},
				["Huge Spiked Club"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Huge Spiked Club


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 4 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Two-handed; very heavy, requires Strength 3.]==],
				},
				["Hunting Bow"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Hunting Bow


Roll: Dex + Archery
Difficulty: 6
Damage: 5
Range: 100
Rate: 1
Clip: 1
Conceal: N

Notes: Nocking and drawing is an automatic action; Archery 3 fires in a single action.]==],
				},
				["Impale"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Impale


Roll: Dex + Archery
Difficulty: 9
Damage: Special
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Pin the target with an arrow or bolt.]==],
				},
				["Iron Staff"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Iron Staff


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 3 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Two-handed; very heavy, requires Strength 3.]==],
				},
				["Jab Pistol"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Jab Pistol


Roll: Dex + Brawl
Difficulty: 6
Damage: As Firearm + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Dirty fighting (min. Brawl 3). Gun pressed against the target.]==],
				},
				["Javelin"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Javelin


Roll: Dex + Athletics
Difficulty: 6
Damage: Str + 2 (L)
Range: 50
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 2. Armor piercing 2. In melee: Str (L), min. Strength 2.]==],
				},
				["Joint Lock"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Joint Lock


Roll: Dex + Martial Arts
Difficulty: 5
Damage: Grapple + Successes (L)
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Katana"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Katana


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 3 (L)
Range: -
Rate: -
Clip: -
Conceal: T

Notes: Two-handed use adds one damage die.]==],
				},
				["Katar"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Katar


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2
Range: -
Rate: -
Clip: -
Conceal: J

Notes: Penetrates up to three points of armor; +1 die to block.]==],
				},
				["Kick"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Kick


Roll: Dex + Brawl
Difficulty: 7
Damage: Str + 1
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Kick (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 448


Kick (Mage)


Roll: Dex + Brawl
Difficulty: 7
Damage: Str + 1 (B)
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Klaive"] = {
					en = [==[Werewolf: The Apocalypse 20th Anniversary Edition, p. 302


Klaive


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (A)
Range: -
Rate: -
Clip: -
Conceal: J

Notes: Silver fetish weapon: werewolves cannot soak the damage except in breed form.]==],
				},
				["Knife"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 280


Knife


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: J]==],
				},
				["Knife (Dark Ages)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Knife (Dark Ages)


Roll: Dex + Melee
Difficulty: 6
Damage: Str (L)
Range: 15
Rate: -
Clip: -
Conceal: P

Notes: Min. Strength 1. Can be thrown (range 15, +1 difficulty).]==],
				},
				["Knife (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Knife (Mage)


Roll: Dex + Melee
Difficulty: 4
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: P]==],
				},
				["Knife, Thrown"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


Knife, Thrown


Roll: Dex + Athletics
Difficulty: 6
Damage: Str (L)
Range: -
Rate: -
Clip: -
Conceal: P]==],
				},
				["Kusarigama"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 451


Kusarigama


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 3 (B)
Range: -
Rate: -
Clip: -
Conceal: T

Notes: Requires two hands; +2 dice to disarm; may entangle at +1 difficulty.]==],
				},
				["Lance (Mounted)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Lance (Mounted)


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 3 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 3. Armor piercing 3.]==],
				},
				["Long Bow"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Long Bow


Roll: Dex + Archery
Difficulty: 6
Damage: 5
Range: 120
Rate: 1
Clip: 1
Conceal: N

Notes: Nocking and drawing is an automatic action; Archery 3 fires in a single action.]==],
				},
				["Longbow"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Longbow


Roll: Dex + Archery
Difficulty: 6
Damage: 4 (L)
Range: 120
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 4. Armor piercing 4.]==],
				},
				["Low Blow"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Low Blow


Roll: Dex + Brawl
Difficulty: 7
Damage: Str + Stun (B or L)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Dirty fighting (min. Brawl 3).]==],
				},
				["M-19 Grenade Launcher"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


M-19 Grenade Launcher


Roll: Dex + Firearms
Difficulty: 6
Damage: 8
Range: 600
Rate: 2
Clip: 1
Conceal: N

Notes: Military weapon; not man-portable, vehicle-mounted; see the Explosives chart.]==],
				},
				["M-79 Grenade Launcher"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


M-79 Grenade Launcher


Roll: Dex + Firearms
Difficulty: 6
Damage: 6
Range: 400
Rate: 1
Clip: 1
Conceal: N

Notes: Military weapon; see the Explosives chart.]==],
				},
				["Mace"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Mace


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: N]==],
				},
				["Mace (Dark Ages)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Mace (Dark Ages)


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: L

Notes: Min. Strength 3.]==],
				},
				["Manriki-Gusari"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 451


Manriki-Gusari


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: T

Notes: Requires two hands; +2 dice to disarm; may entangle at +1 difficulty.]==],
				},
				["Martial Arts Disarm"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Martial Arts Disarm


Roll: Dex + Martial Arts
Difficulty: 7
Damage: 3
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Bare-handed disarm; minimum three dots in Martial Arts.]==],
				},
				["Morning Star"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Morning Star


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 3 (L)
Range: -
Rate: -
Clip: -
Conceal: L

Notes: Min. Strength 3.]==],
				},
				["Multiple Shots"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Multiple Shots


Roll: Dex + Firearms
Difficulty: 6
Damage: Weapon
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Accuracy: special (the dice pool is split between shots).]==],
				},
				["Nerve Strike"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Nerve Strike


Roll: Dex + Martial Arts
Difficulty: 7
Damage: Str + 3 (B)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: With three or more successes the target rolls Stamina (difficulty 8) or is stunned next turn.]==],
				},
				["Nunchaku"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Nunchaku


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 2 (B)
Range: -
Rate: -
Clip: -
Conceal: T

Notes: +1 die to block; +1 difficulty to the opponent's block.]==],
				},
				["Pacification Spray"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


Pacification Spray


Roll: Dex + Firearms
Difficulty: 6
Damage: 5 (B)
Range: 3
Rate: 1
Clip: 5
Conceal: P

Notes: Technocratic. Bashing; no extra damage from successes. Target loses two dice for one turn per success.]==],
				},
				["Parry"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Parry


Roll: Dex + Melee
Difficulty: 6
Damage: None (R)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Accuracy: special. (R) reduces an opponent's attack successes.]==],
				},
				["Pick Ax"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Pick Ax


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 4. Armor piercing 3.]==],
				},
				["Pistol Whip"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Pistol Whip


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Dirty fighting (min. Brawl 3).]==],
				},
				["Pistol, Hvy."] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 281


Pistol, Hvy.


Roll: Dex + Firearms
Difficulty: 6
Damage: 5
Range: 25
Rate: 3
Clip: 13+1
Conceal: J

Notes: Example: Springfield XDM (.45 ACP). Lethal vs. mortals; bashing vs. Kindred unless the head is targeted.]==],
				},
				["Pistol, Lt."] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 281


Pistol, Lt.


Roll: Dex + Firearms
Difficulty: 6
Damage: 4
Range: 20
Rate: 4
Clip: 15+1
Conceal: P

Notes: Example: HK USP (9mm). Lethal vs. mortals; bashing vs. Kindred unless the head is targeted.]==],
				},
				["Pitchfork"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Pitchfork


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 2. Armor piercing 1. Two-handed.]==],
				},
				["Point Blank"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 447


Point Blank


Roll: Dex + Firearms
Difficulty: 4
Damage: Weapon
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Within two yards.]==],
				},
				["Polearm"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Polearm


Roll: Dex + Melee
Difficulty: 7
Damage: Str + 3 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Requires two hands; +2 difficulty one-handed.]==],
				},
				["Punch"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 448


Punch


Roll: Dex + Brawl
Difficulty: 6
Damage: Str (B)
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Quarterstaff"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Quarterstaff


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 3 (B)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 2. +2 dice to Sweep.]==],
				},
				["Reading Opponent"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 448


Reading Opponent


Roll: Per + Trait
Difficulty: 6
Damage: Special
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Resisted roll, Perception + combat Trait against the opponent's Wits + combat Trait; each success adds one die to the next action.]==],
				},
				["Revolver, Hvy."] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 281


Revolver, Hvy.


Roll: Dex + Firearms
Difficulty: 6
Damage: 6
Range: 35
Rate: 2
Clip: 6
Conceal: J

Notes: Example: Ruger Redhawk (.44 Magnum). Lethal vs. mortals; bashing vs. Kindred unless the head is targeted.]==],
				},
				["Revolver, Lt."] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 281


Revolver, Lt.


Roll: Dex + Firearms
Difficulty: 6
Damage: 4
Range: 12
Rate: 3
Clip: 6
Conceal: P

Notes: Example: SW Bodyguard (.38 Special). Lethal vs. mortals; bashing vs. Kindred unless the head is targeted.]==],
				},
				["Rifle"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 281


Rifle


Roll: Dex + Firearms
Difficulty: 6
Damage: 8
Range: 200
Rate: 1
Clip: 3+1
Conceal: N

Notes: Example: Beretta Tikka T3 (30.06). Lethal vs. mortals; bashing vs. Kindred unless the head is targeted.]==],
				},
				["Rifle (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Rifle (Mage)


Roll: Dex + Firearms
Difficulty: 6
Damage: 8
Range: 200
Rate: 1
Clip: 5+1
Conceal: N

Notes: Example: Remington M-700 (30.06).]==],
				},
				["Riot Baton"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Riot Baton


Roll: Dex + Melee
Difficulty: 5
Damage: Str + 1 (B)
Range: -
Rate: -
Clip: -
Conceal: T]==],
				},
				["Riposte"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Riposte


Roll: Dex + Brawl/Melee
Difficulty: 7
Damage: Normal + 1
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Counterattack after a successful parry or block.]==],
				},
				["Rock"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Rock


Roll: Dex + Athletics
Difficulty: 7
Damage: Str (B)
Range: 40
Rate: -
Clip: -
Conceal: P

Notes: Min. Strength 2. +1 difficulty.]==],
				},
				["Rocket Launcher"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


Rocket Launcher


Roll: Dex + Firearms
Difficulty: 6
Damage: 12-16
Range: 500+
Rate: 1
Clip: 1
Conceal: N

Notes: Military weapon; see the Explosives chart.]==],
				},
				["Saber"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Saber


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: L

Notes: Min. Strength 3.]==],
				},
				["Sai"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Sai


Roll: Dex + Melee
Difficulty: 5
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: J

Notes: +1 die to block; +2 dice to disarm.]==],
				},
				["Sap"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 280


Sap


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (B)
Range: -
Rate: -
Clip: -
Conceal: P

Notes: Blunt: bashing damage unless targeted at the head (lethal).]==],
				},
				["Sap (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Sap (Mage)


Roll: Dex + Melee
Difficulty: 4
Damage: Str + 1 (B)
Range: -
Rate: -
Clip: -
Conceal: P]==],
				},
				["Sap (Werewolf)"] = {
					en = [==[Werewolf: The Apocalypse 20th Anniversary Edition, p. 302


Sap (Werewolf)


Roll: Dex + Melee
Difficulty: 4
Damage: Str (B)
Range: -
Rate: -
Clip: -
Conceal: P]==],
				},
				["Semi-Automatic Pistol, Hvy."] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Semi-Automatic Pistol, Hvy.


Roll: Dex + Firearms
Difficulty: 6
Damage: 5
Range: 30
Rate: 3
Clip: 7+1
Conceal: J

Notes: Example: IMI Desert Eagle (.50 AE).]==],
				},
				["Semi-Automatic Pistol, Lt."] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Semi-Automatic Pistol, Lt.


Roll: Dex + Firearms
Difficulty: 6
Damage: 4
Range: 20
Rate: 4
Clip: 17+1
Conceal: P

Notes: Example: Glock 17 (9mm). All firearm damage is lethal.]==],
				},
				["Short Bow"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Short Bow


Roll: Dex + Archery
Difficulty: 6
Damage: 4
Range: 60
Rate: 1
Clip: 1
Conceal: N

Notes: Nocking and drawing is an automatic action; Archery 3 fires in a single action.]==],
				},
				["Short Sword"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Short Sword


Roll: Dex + Melee
Difficulty: 5
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: J]==],
				},
				["Shortbow"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Shortbow


Roll: Dex + Archery
Difficulty: 6
Damage: 2 (L)
Range: 60
Rate: -
Clip: -
Conceal: L

Notes: Min. Strength 3. Armor piercing 2.]==],
				},
				["Shotgun"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 281


Shotgun


Roll: Dex + Firearms
Difficulty: 6
Damage: 8
Range: 20
Rate: 1
Clip: 5+1
Conceal: T

Notes: Example: Remington 870 (12-Gauge). Lethal vs. mortals; bashing vs. Kindred unless the head is targeted.]==],
				},
				["Shotgun, Assault"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Shotgun, Assault


Roll: Dex + Firearms
Difficulty: 6
Damage: 8
Range: 50
Rate: 3
Clip: 32+1
Conceal: N

Notes: Example: MPS AA-12 (12 Gauge). May fire full-auto, three-round bursts and strafing sprays.]==],
				},
				["Shotgun, Sawed Off"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Shotgun, Sawed Off


Roll: Dex + Firearms
Difficulty: 6
Damage: 8
Range: 10
Rate: 2
Clip: 2
Conceal: J

Notes: Example: Winchester Model 24 double barrel (12 Gauge).]==],
				},
				["Shotgun, Semi-auto"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 281


Shotgun, Semi-auto


Roll: Dex + Firearms
Difficulty: 6
Damage: 8
Range: 20
Rate: 3
Clip: 6+1
Conceal: T

Notes: Example: Benelli M4 Super 90 (12-Gauge). Lethal vs. mortals; bashing vs. Kindred unless the head is targeted.]==],
				},
				["Shotgun, Semi-Automatic"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


Shotgun, Semi-Automatic


Roll: Dex + Firearms
Difficulty: 6
Damage: 8
Range: 25
Rate: 3
Clip: 6+1
Conceal: T

Notes: Example: Benelli M4 (12 Gauge).]==],
				},
				["Shuriken"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


Shuriken


Roll: Dex + Athletics
Difficulty: 7
Damage: 3 (L)
Range: -
Rate: -
Clip: -
Conceal: P]==],
				},
				["Sling"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Sling


Roll: Dex + Archery
Difficulty: 6
Damage: 3 (B)
Range: 40
Rate: -
Clip: -
Conceal: P

Notes: Min. Strength 2.]==],
				},
				["SMG, Large"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 281


SMG, Large


Roll: Dex + Firearms
Difficulty: 6
Damage: 4
Range: 50
Rate: 3
Clip: 30+1
Conceal: T

Notes: Example: HK MP5 (9mm). Capable of three-round bursts, full auto and sprays.]==],
				},
				["SMG, Small"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 281


SMG, Small


Roll: Dex + Firearms
Difficulty: 6
Damage: 4
Range: 20
Rate: 3
Clip: 17+1
Conceal: J

Notes: Example: Glock 18 (9mm). Capable of three-round bursts, full auto and sprays.]==],
				},
				["SMG, Small (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 452


SMG, Small (Mage)


Roll: Dex + Firearms
Difficulty: 6
Damage: 4
Range: 25
Rate: 3
Clip: 30+1
Conceal: J

Notes: Example: Ingram Mac-10 (9mm). May fire full-auto, three-round bursts and strafing sprays.]==],
				},
				["Snake Step"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Snake Step


Roll: Dex + Martial Arts
Difficulty: 6/5
Damage: Dodge + 3 dice
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Difficulty 6 hard style / 5 soft style.]==],
				},
				["Snap Kick"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Snap Kick


Roll: Dex + Martial Arts
Difficulty: 5
Damage: Str + 1 (B)
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Spear"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


Spear


Roll: Dex + Athletics
Difficulty: 6
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: N]==],
				},
				["Spear (Dark Ages)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Spear (Dark Ages)


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (L)
Range: 40
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 2. Armor piercing 2. Two-handed with min. Strength 3: Str + 3 (L). Can be thrown (range 40).]==],
				},
				["Spiked Club"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Spiked Club


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: T]==],
				},
				["Spiked Gauntlet"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Spiked Gauntlet


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: J]==],
				},
				["Spinning Kick"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Spinning Kick


Roll: Dex + Martial Arts
Difficulty: 6
Damage: Str + 3 (B)
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Staff"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Staff


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (B)
Range: -
Rate: -
Clip: -
Conceal: N]==],
				},
				["Stake"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 280


Stake


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: T

Notes: May paralyze a vampire driven through the heart: target the heart (difficulty 9) and score three damage successes.]==],
				},
				["Stake (Dark Ages)"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Stake (Dark Ages)


Roll: Dex + Melee
Difficulty: 9
Damage: Special
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Plunge a stake through a vampire's heart: damage per weapon or Str + 1 (L).]==],
				},
				["Stiletto"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Stiletto


Roll: Dex + Melee
Difficulty: 4
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: P

Notes: Penetrates up to three points of armor.]==],
				},
				["Stone"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


Stone


Roll: Dex + Athletics
Difficulty: 5
Damage: Str (B)
Range: -
Rate: -
Clip: -
Conceal: varies]==],
				},
				["Stone, Large"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


Stone, Large


Roll: Dex + Athletics
Difficulty: 5
Damage: Str + 3 (B)
Range: -
Rate: -
Clip: -
Conceal: N]==],
				},
				["Strafing"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Strafing


Roll: Dex + Firearms
Difficulty: 8
Damage: Special
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Accuracy +10. Empties the clip across an area (max. three yards).]==],
				},
				["Strike"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Strike


Roll: Dex + Brawl
Difficulty: 6
Damage: Str
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Suppressive Fire"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 350


Suppressive Fire


Roll: Dex + Archery
Difficulty: 4
Damage: Weapon
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Keeps an advancing opponent back; each success may give an ally -1 difficulty.]==],
				},
				["Sweep"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Sweep


Roll: Dex + Brawl/Melee
Difficulty: 7
Damage: Str (K)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: (K) causes knockdown.]==],
				},
				["Sweep (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 448


Sweep (Mage)


Roll: Dex + Brawl
Difficulty: 8
Damage: Special
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Knockdown: the opponent ends up on the ground.]==],
				},
				["Sword"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 280


Sword


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: T]==],
				},
				["Table"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Table


Roll: Dex + Melee
Difficulty: 8
Damage: Str + 3 (B)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Two-handed; very heavy, requires Strength 3.]==],
				},
				["Tackle"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Tackle


Roll: Str + Brawl
Difficulty: 7
Damage: Str + 1 (K)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: (K) causes knockdown. Attacker rolls Dex + Athletics (difficulty 8) or falls too.]==],
				},
				["Tackle (Mage)"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 448


Tackle (Mage)


Roll: Dex + Brawl
Difficulty: 7
Damage: Str + Special (B)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Needs two yards of momentum; both roll Dex + Athletics or end up on the ground. May hurt the attacker.]==],
				},
				["Taser"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


Taser


Roll: Dex + Firearms
Difficulty: 6
Damage: 5 (B)
Range: 5
Rate: 1
Clip: 1
Conceal: P

Notes: Bashing damage; no extra damage from successes.]==],
				},
				["Tear Gas"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


Tear Gas


Roll: Dex + Firearms
Difficulty: 6
Damage: 3 (B)
Range: 3
Rate: 1
Clip: 5
Conceal: P

Notes: Bashing; no extra damage from successes. Target loses two dice for one turn per success.]==],
				},
				["Throw"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Throw


Roll: Dex + Martial Arts
Difficulty: 7/6
Damage: Str + Movement (B)
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Difficulty 7 hard style / 6 soft style. A pool equal to or above the opponent's Dexterity throws him one yard per success.]==],
				},
				["Thunder Kick"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Thunder Kick


Roll: Dex + Martial Arts
Difficulty: 7
Damage: Str + 3 + Successes (B)
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Tomahawk"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Tomahawk


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: J]==],
				},
				["Tomahawk, Thrown"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 453


Tomahawk, Thrown


Roll: Dex + Athletics
Difficulty: 6
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: J]==],
				},
				["Two Weapons"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Two Weapons


Roll: Dex + Firearms
Difficulty: 6/7
Damage: Weapon
Range: -
Rate: -
Clip: -
Conceal: -

Notes: +1 difficulty for the off-hand weapon. Two rolls, as a multiple action.]==],
				},
				["Vital Strike"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Vital Strike


Roll: Dex + Martial Arts
Difficulty: 7
Damage: Str (L)
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["War Fan"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


War Fan


Roll: Dex + Melee
Difficulty: 5
Damage: Str + 2 (L)
Range: -
Rate: -
Clip: -
Conceal: J

Notes: +1 die to block; +1 difficulty to the opponent's block.]==],
				},
				["Warhammer"] = {
					en = [==[Vampire: The Dark Ages 20th Anniversary Edition, p. 349


Warhammer


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 4 (B)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: Min. Strength 4. Two-handed.]==],
				},
				["Weapon Strike"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 279


Weapon Strike


Roll: Dex + Melee
Difficulty: 6
Damage: Weapon
Range: -
Rate: -
Clip: -
Conceal: -

Notes: Damage by weapon type (Melee Weapons Chart).]==],
				},
				["Whip"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 451


Whip


Roll: Dex + Melee
Difficulty: 6
Damage: Str (L)
Range: -
Rate: -
Clip: -
Conceal: J

Notes: May entangle a limb at +1 difficulty.]==],
				},
				["Whip (Werewolf)"] = {
					en = [==[Werewolf: The Apocalypse 20th Anniversary Edition, p. 302


Whip (Werewolf)


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 1 (L)
Range: -
Rate: -
Clip: -
Conceal: J

Notes: May entangle a limb at +1 difficulty.]==],
				},
				["Wind and Fire Wheel"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 450


Wind and Fire Wheel


Roll: Dex + Melee
Difficulty: 6
Damage: Str + 3 (L)
Range: -
Rate: -
Clip: -
Conceal: N

Notes: +2 dice to disarm.]==],
				},
				["Withering Grasp"] = {
					en = [==[Mage: The Ascension 20th Anniversary Edition, p. 449


Withering Grasp


Roll: Dex + Martial Arts
Difficulty: 7
Damage: Str (B) + Disarm
Range: -
Rate: -
Clip: -
Conceal: -]==],
				},
				["Conceal"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 281


Conceal


P = Pocket · J = Jacket · T = Trenchcoat · N = Cannot be concealed. Dark Ages: C = loose Clothing · L = Long cloak. varies = depends on the item.]==],
				},
				-- <<< WEAPON_DESC_END
};
