-- Revenant family traits, the pt half (SPEC I21, I148d, V432, V210, V24 / T850).
--
-- One entry per item of PICKER_LIST["family"], keyed by the value the sheet SAVES, byte for
-- byte (SPEC V24). Block 3 is MECHANICS and nothing else - the Disciplines and the Weakness -
-- because that is what the owner asked the ? to say (SPEC I148d). The trio is read off CLANS
-- on the root form; the weakness sentence comes off FAMILY_WEAKNESS (family, root form) or
-- research/clan_weakness.tsv (clan, T970): the module is DERIVED from them and V432 reads it
-- back against them, so a drift shows up as a red gate and not as a pane that disagrees
-- with the slots (SPEC V135).
--
-- Three blocks separated by two blank lines (SPEC I21): source, name, body. The book title
-- does not translate and neither does the name in block 2 - it is the key; only p./pag. does.
--
-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24).
-- GENERATED by research/gen_traits_desc.ps1. Do not hand-edit: fix the table or the .tsv
-- it reads and run it again.

return {
				-- >>> FAMILY_DESC_BEGIN (generated - SPEC T850)
				["Basarab"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 454


Basarab


Disciplinas: Animalismo, Dominação, Presença

Fraqueza: Repelidos por alho e por símbolos sagrados: diante de qualquer um dos dois, um teste de Força de Vontade ou têm de se afastar.]==],
				},
				["Bratovich (Dark Ages)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 454


Bratovich (Dark Ages)


Disciplinas: Animalismo, Potência, Vicissitude

Fraqueza: Entregues à própria selvageria, sofrem os mesmos efeitos de frenesi que os Brujah.]==],
				},
				["Bratovitch (Modern)"] = {
					pt = [==[Ghouls & Revenants, pág. 90-91


Bratovitch (Modern)


Disciplinas: Animalismo, Fortitude, Vicissitude

Fraqueza: +2 de dificuldade em todo teste para resistir ao frenesi. Não podem gastar Força de Vontade para evitar um frenesi, apenas para encerrá-lo.]==],
				},
				["D'Habi"] = {
					pt = [==[Ghouls & Revenants, pág. 92-93


D'Habi


Disciplinas: Presença, Ofuscação, Daimonion

Fraqueza: Quebrados por séculos de servidão infernal, são extraordinariamente sugestionáveis: +2 de dificuldade em todo teste de Força de Vontade.]==],
				},
				["Danislav"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 455


Danislav


Disciplinas: Auspícios, Metamorfose, Vicissitude

Fraqueza: Sofrem dano agravado por prata.]==],
				},
				["Ducheski"] = {
					pt = [==[Ghouls & Revenants, pág. 94-95


Ducheski


Disciplinas: Auspícios, Dominação, Taumaturgia

Fraqueza: Séculos sob os Tremere os afastaram do lado humano: nenhum Ducheski pode ter um Atributo Social acima de 2.]==],
				},
				["Enrathi"] = {
					pt = [==[Ghouls & Revenants, pág. 96-97


Enrathi


Disciplinas: Dominação, Ofuscação, Potência

Fraqueza: Séculos de decadência moral: não podem ter Humanidade acima de 3, nem Consciência acima de 2.]==],
				},
				["Grimaldi (Dark Ages)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 455


Grimaldi (Dark Ages)


Disciplinas: Rapidez, Dominação, Fortitude

Fraqueza: O sangue Tzimisce é fraco nesta família, que não tem laços nativos com o Voivodato: têm apenas oito pontos de sangue.]==],
				},
				["Grimaldi (Modern)"] = {
					pt = [==[Ghouls & Revenants, pág. 98-99


Grimaldi (Modern)


Disciplinas: Rapidez, Dominação, Fortitude

Fraqueza: Arrogância de família: sempre que houver ocasião de gabar-se da família, um teste de Força de Vontade a dificuldade 7 para conter o desprezo.]==],
				},
				["Kairouan Brotherhood"] = {
					pt = [==[Ghouls & Revenants, pág. 100-101


Kairouan Brotherhood


Disciplinas: Auspícios, Rapidez, Ofuscação

Fraqueza: Anos de manipulação genética: todo membro sofre o Defeito Cura Lenta (V20 p. 483).]==],
				},
				["Keskinen"] = {
					pt = [==[Ghouls & Revenants, pág. 114


Keskinen


Disciplinas: Taumaturgia, mais duas entre Auspícios, Dominação ou Ofuscação

Fraqueza: Todos os Keskinen compartilham a obsessão de sua patrona por apagar o sol, que se manifesta como uma Perturbação.]==],
				},
				["Khavi"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 455


Khavi


Disciplinas: Animalismo, Ofuscação, Vicissitude

Fraqueza: Vulneráveis à luz do sol: sofrem dano solar como um Cainita, mas contundente em vez de agravado, e podem absorvê-lo com Vigor e Fortitude.]==],
				},
				["Krevcheski"] = {
					pt = [==[Ghouls & Revenants, pág. 94


Krevcheski


Disciplinas: Auspícios, Dominação

Fraqueza: Os Krevcheski são vistos com desconfiança pelos Tzimisce e, por isso, aprenderam apenas duas Disciplinas de família em vez das três normais.]==],
				},
				["Marijava"] = {
					pt = [==[Ghouls & Revenants, pág. 114


Marijava


Disciplinas: Rapidez, Ofuscação, Presença

Fraqueza: Bastante suscetíveis ao laço de sangue: ficam presos a um vampiro após um único gole.]==],
				},
				["Obertus"] = {
					pt = [==[Ghouls & Revenants, pág. 102-103


Obertus


Disciplinas: Auspícios, Ofuscação, Vicissitude

Fraqueza: Criados para o intelecto e propensos a distúrbios psicológicos: a grande maioria sofre da Perturbação Obsessivo-Compulsiva (V20 p. 291-292).]==],
				},
				["Obertus (Narov)"] = {
					pt = [==[Ghouls & Revenants, pág. 102-103


Obertus (Narov)


Disciplinas: Auspícios, Dominação, Vicissitude

Fraqueza: Os membros da linhagem Narov ressurgente são afligidos pela Perturbação Megalomania (V20 p. 291-292).]==],
				},
				["Oprichniki"] = {
					pt = [==[Ghouls & Revenants, pág. 104-105


Oprichniki


Disciplinas: Animalismo, Ofuscação, Potência

Fraqueza: Amaldiçoados pelos crimes dos fundadores: sofrem o Defeito Assombrado (V20 p. 495) em definitivo, e banir um fantasma só traz outro.]==],
				},
				["Rafastio"] = {
					pt = [==[Ghouls & Revenants, pág. 106-107


Rafastio


Disciplinas: Animalismo, Auspícios, Taumaturgia

Fraqueza: Amaldiçoados pela lua: +2 de dificuldade para usar Disciplinas na lua nova, +1 na crescente e na minguante, -1 na cheia. O sangue deles rejeita o Abraço, que sempre os matou.]==],
				},
				["Rossellini"] = {
					pt = [==[Ghouls & Revenants, pág. 108-109


Rossellini


Disciplinas: Dominação, Fortitude, Necromancia

Fraqueza: Todos sofrem o Defeito Visão da Morte (V20 p. 494): -2 de dificuldade para resistir a testes de Aparência, +2 de dificuldade em testes de Percepção e +1 em testes Sociais.]==],
				},
				["Servants of Anushin-Rawan"] = {
					pt = [==[Ghouls & Revenants, pág. 110-111


Servants of Anushin-Rawan


Disciplinas: Auspícios, Ofuscação, Presença

Fraqueza: Na presença de um vampiro descendente de Anushin-Rawan, são compelidos a proteger aquele Ventrue como se estivessem sob laço de sangue, por 10 noites menos a Força de Vontade.]==],
				},
				["Szantovich"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 455


Szantovich


Disciplinas: Auspícios, Presença, Vicissitude

Fraqueza: Personalidades viciantes: expostos a uma experiência sensual que os enfraqueceu, faça um teste de Força de Vontade para fazer qualquer outra coisa, e não podem gastar Força de Vontade para resistir ao vício.]==],
				},
				["Vlaszy"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 455


Vlaszy


Disciplinas: Animalismo, Potência, Presença

Fraqueza: Todo Vlaszy jura um Juramento de Sangue a um Demônio ao atingir a maioridade.]==],
				},
				["Zantosa"] = {
					pt = [==[Ghouls & Revenants, pág. 112-113


Zantosa


Disciplinas: Auspícios, Presença, Vicissitude

Fraqueza: Diante de uma experiência prazerosa, um teste de Força de Vontade ou ficam obcecados por ela. Não podem gastar Força de Vontade para resistir a um poder sobrenatural que os atraia a um novo prazer.]==],
				},
				-- <<< FAMILY_DESC_END
};
