-- Armor descriptions, the [pt] half (SPEC I157h, I21, V210 / T1004).
--
-- One entry per item of PICKER_LIST["armor"], keyed in ENGLISH because that is what the sheet
-- saves (SPEC V24). Three blocks, exactly as the twelve description modules already do:
-- "<Book>, p. <n>" - blank - blank - <Name> - blank - blank - <text>. The book title does
-- not translate; only p./pag. does (SPEC I100e).
--
-- One module PER LANGUAGE and never both halves in one file (SPEC V210): half of every
-- module was the language the session never opens, and require pulled both in to read one.
-- The renderer builds the name by concatenation - require("desc<Kind>_" .. half .. ".lua")
-- and never a constant name (SPEC V210b).
--
-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24).
-- Generated by research/gen_combat_data.ps1 from research/weapon.tsv and
-- research/armor.tsv. Do not hand-edit.

return {
				-- >>> ARMOR_DESC_BEGIN (generated - SPEC T1004)
				["Alanson Hardsuit"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Alanson Hardsuit


Valor: 7
Penalidade: -2]==],
				},
				["Bearskin Coat"] = {
					pt = [==[Werewolf: The Apocalypse 20th Anniversary Edition, pág. 292


Bearskin Coat


Valor: 3
Penalidade: 3]==],
				},
				["Biker Jacket"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Biker Jacket


Valor: 1
Penalidade: -1]==],
				},
				["Chainmail"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Chainmail


Valor: 4
Penalidade: -2]==],
				},
				["Class Five (Full Riot Gear)"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 280


Class Five (Full Riot Gear)


Valor: 5
Penalidade: 3

Notas: Soma o valor à absorção contra dano de contusão, letal e agravado de presas e garras; não contra fogo ou luz do sol. A penalidade sai das paradas baseadas em Destreza.]==],
				},
				["Class Five (Knight's Armor)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Class Five (Knight's Armor)


Valor: 5
Penalidade: 3]==],
				},
				["Class Four (Flak Jacket)"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 280


Class Four (Flak Jacket)


Valor: 4
Penalidade: 2

Notas: Soma o valor à absorção contra dano de contusão, letal e agravado de presas e garras; não contra fogo ou luz do sol. A penalidade sai das paradas baseadas em Destreza.]==],
				},
				["Class Four (Heavy Armor)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Class Four (Heavy Armor)


Valor: 4
Penalidade: 2]==],
				},
				["Class One (Heavy Clothing)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Class One (Heavy Clothing)


Valor: 1
Penalidade: -]==],
				},
				["Class One (Reinforced Clothing)"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 280


Class One (Reinforced Clothing)


Valor: 1
Penalidade: 0

Notas: Soma o valor à absorção contra dano de contusão, letal e agravado de presas e garras; não contra fogo ou luz do sol. A penalidade sai das paradas baseadas em Destreza.]==],
				},
				["Class Three (Composite Armor)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Class Three (Composite Armor)


Valor: 3
Penalidade: 1]==],
				},
				["Class Three (Kevlar Vest)"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 280


Class Three (Kevlar Vest)


Valor: 3
Penalidade: 1

Notas: Soma o valor à absorção contra dano de contusão, letal e agravado de presas e garras; não contra fogo ou luz do sol. A penalidade sai das paradas baseadas em Destreza.]==],
				},
				["Class Two (Armor T-Shirt)"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 280


Class Two (Armor T-Shirt)


Valor: 2
Penalidade: 1

Notas: Soma o valor à absorção contra dano de contusão, letal e agravado de presas e garras; não contra fogo ou luz do sol. A penalidade sai das paradas baseadas em Destreza.]==],
				},
				["Class Two (Cloth/Textile Armor)"] = {
					pt = [==[Vampire: The Dark Ages 20th Anniversary Edition, pág. 350


Class Two (Cloth/Textile Armor)


Valor: 2
Penalidade: 1]==],
				},
				["Cosplay Mail"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Cosplay Mail


Valor: 2
Penalidade: -1]==],
				},
				["Cybernetic Armor"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Cybernetic Armor


Valor: 1-4
Penalidade: 0

Notas: Embutida no portador; ver o Antecedente: Aprimoramento.]==],
				},
				["Enhanced Clothing"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Enhanced Clothing


Valor: 1-5
Penalidade: 0

Notas: Roupa tecida com materiais avançados ou Iluminados.]==],
				},
				["Flak Vest"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Flak Vest


Valor: 4
Penalidade: -2]==],
				},
				["Full Plate"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Full Plate


Valor: 5
Penalidade: -2]==],
				},
				["Kevlar Vest"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Kevlar Vest


Valor: 3
Penalidade: -1]==],
				},
				["Leather Duster"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Leather Duster


Valor: 2
Penalidade: -2]==],
				},
				["Metal Shield"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Metal Shield


Valor: 4/+2
Penalidade: -2

Notas: Escudo: bônus de absorção / bônus de dificuldade contra ataques.]==],
				},
				["Military Armor"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Military Armor


Valor: 5
Penalidade: -2]==],
				},
				["Reinforced Clothing"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Reinforced Clothing


Valor: 1-2
Penalidade: 0

Notas: Roupa enrijecida, acolchoada ou em camadas contra ferimentos.]==],
				},
				["Reinforced Clothing (Werewolf)"] = {
					pt = [==[Werewolf: The Apocalypse 20th Anniversary Edition, pág. 292


Reinforced Clothing (Werewolf)


Valor: 1
Penalidade: 0]==],
				},
				["Riot Shield"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Riot Shield


Valor: 5/+2
Penalidade: -1

Notas: Escudo: bônus de absorção / bônus de dificuldade contra ataques.]==],
				},
				["Riot Suit"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Riot Suit


Valor: 4
Penalidade: -2]==],
				},
				["Riot Suit (Werewolf)"] = {
					pt = [==[Werewolf: The Apocalypse 20th Anniversary Edition, pág. 292


Riot Suit (Werewolf)


Valor: 5
Penalidade: 3]==],
				},
				["Steel Breastplate"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Steel Breastplate


Valor: 3
Penalidade: -2]==],
				},
				["Tough Hide"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Tough Hide


Valor: 1-3
Penalidade: 0

Notas: Animais, Relíquias, constructos ou magos transformados com pele especialmente grossa ou blindada.]==],
				},
				["Trash Can Lid"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Trash Can Lid


Valor: 3/+1
Penalidade: 0

Notas: Escudo: bônus de absorção / bônus de dificuldade contra ataques.]==],
				},
				["Trashcan Lid"] = {
					pt = [==[Werewolf: The Apocalypse 20th Anniversary Edition, pág. 292


Trashcan Lid


Valor: 2
Penalidade: 0

Notas: Sem penalidade de Destreza, mas exige jogada de Destreza + Armas Brancas, dificuldade 6, para usar.]==],
				},
				["Wooden Shield"] = {
					pt = [==[Mage: The Ascension 20th Anniversary Edition, pág. 447


Wooden Shield


Valor: 2/+2
Penalidade: -1

Notas: Escudo: bônus de absorção / bônus de dificuldade contra ataques.]==],
				},
				-- <<< ARMOR_DESC_END
};
