-- Clan traits, the pt half (SPEC I21, I148d, V432, V210, V24 / T971).
--
-- One entry per item of PICKER_LIST["clan"], keyed by the value the sheet SAVES, byte for
-- byte (SPEC V24). Block 3 is MECHANICS and nothing else - the Disciplines and the Weakness -
-- because that is what the owner asked the ? to say (SPEC I148d). The trio is read off CLANS
-- on the root form; the weakness sentence comes off FAMILY_WEAKNESS (family, root form) or
-- research/clan_weakness.tsv (clan, T970): the module is DERIVED from them and V432 reads it
-- back against them, so a drift shows up as a red gate and not as a pane that disagrees
-- with the slots (SPEC V135).
--
-- Three blocks separated by two blank lines (SPEC I21): source, name, body. The book title
-- does not translate and neither does the name in block 2 - it is the key; only p./pag. does.
--
-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24).
-- GENERATED by research/gen_traits_desc.ps1. Do not hand-edit: fix the table or the .tsv
-- it reads and run it again.

return {
				-- >>> CLAN_DESC_BEGIN (generated - SPEC T971)
				["Assamite"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 48


Assamite


Disciplinas: Rapidez, Ofuscação, Quietus

Fraqueza: Por causa da maldição de sangue dos Tremere, se um Assamita consome o sangue de outro Membro, sofre um nível automático de dano letal não absorvível por ponto de sangue bebido. Tentativas de diablerie resultam em dano agravado automático, um nível de vitalidade por ponto de Força de Vontade permanente da vítima; o pretenso diablerista não ganha benefício algum (incluindo redução de Geração) se sobrevive ao processo. Além disso, os Assamitas devem entregar parte dos lucros de seus contratos aos seus senhores ou superiores (em geral cerca de 10 por cento de todos esses ganhos).]==],
				},
				["Brujah"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 50


Brujah


Disciplinas: Rapidez, Potência, Presença

Fraqueza: As mesmas paixões que levam os Brujah à grandeza ou à depravação, quando não contidas, podem lançá-los em fúrias incandescentes: as dificuldades dos testes para resistir ao frenesi ou guiá-lo (p. 298) são duas acima do normal. Além disso, um Brujah nunca pode gastar Força de Vontade para evitar o frenesi, embora possa gastar um ponto de Força de Vontade para encerrar um frenesi já iniciado.]==],
				},
				["Followers of Set"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 52


Followers of Set


Disciplinas: Ofuscação, Presença, Serpentis

Fraqueza: Dadas suas origens nas trevas, as Serpentes reagem mal à luz forte: acrescente dois níveis de vitalidade ao dano causado pela exposição à luz do sol. Os Setitas também perdem um dado das paradas de dados em ações realizadas sob luz intensa (holofotes da polícia, luzes de palco, sinalizadores etc.).]==],
				},
				["Gangrel"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 54


Gangrel


Disciplinas: Animalismo, Fortitude, Metamorfose

Fraqueza: Toda vez que uma Gangrel entra em frenesi, ela adquire uma característica animal temporária (que pode substituir uma temporária já existente). Um tufo de pelos, um breve torpor depois de se alimentar ou nervosismo perto de multidões: tudo isso pode marcar uma Forasteira após o frenesi. As características adquiridas nos frenesis Gangrel não precisam ser só físicas; podem ser comportamentais. Os jogadores devem definir com o Narrador que novo traço animal foi adquirido (se o frenesi envolveu o impulso de lutar ou fugir pode ser relevante). Com o tempo, ou numa situação excepcional, um traço animal pode se tornar permanente, e o frenesi seguinte acrescenta outro. Uma boa diretriz é exigir que cada traço ganho em frenesi tenha algum efeito em termos de sistema (como a redução temporária de pontos de Atributo Social ou a perda permanente de Humanidade), embora alguns Narradores possam permitir traços apenas narrativos que moldem a história.]==],
				},
				["Giovanni"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 56


Giovanni


Disciplinas: Dominação, Necromancia, Potência

Fraqueza: O Beijo de um vampiro Giovanni causa dor excruciante nos recipientes mortais que o recebem. Se a Giovanni não tomar cuidado, seu recipiente pode morrer de choque e agonia antes de ser totalmente exangue. Quando uma Giovanni se alimenta de um mortal, causa o dobro do dano que o Beijo de outro vampiro causaria. Por exemplo, se uma Giovanni toma um ponto de sangue de um recipiente mortal, a vítima sofre dois níveis de vitalidade de dano. Por isso, eles tendem a usar bancos de sangue e outros meios de alimentação que não resistem tanto.]==],
				},
				["Lasombra"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 58


Lasombra


Disciplinas: Dominação, Tenebrosidade, Potência

Fraqueza: Os vampiros Lasombra não têm reflexo. Seja num espelho, numa superfície d’água, numa superfície polida ou no retrovisor de um táxi, a imagem do Guardião não se reflete.]==],
				},
				["Malkavian"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 60


Malkavian


Disciplinas: Auspícios, Demência, Ofuscação

Fraqueza: Todos os membros do Clã Malkavian sofrem de uma Perturbação permanente e incurável. Podem adquirir outras Perturbações e recuperar-se delas, e podem gastar Força de Vontade para amenizar os efeitos da Perturbação por uma cena, mas nunca se recuperam da Perturbação original.]==],
				},
				["Nosferatu"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 62


Nosferatu


Disciplinas: Animalismo, Ofuscação, Potência

Fraqueza: Todos os Nosferatu têm Aparência zero e nunca podem melhorá-la. Risque-a da ficha de personagem. Paradas de dados que usam a Característica Aparência são inerentemente difíceis para esses Membros hediondos.]==],
				},
				["Ravnos"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 64


Ravnos


Disciplinas: Animalismo, Quimerismo, Fortitude

Fraqueza: Uma história turbulenta faz dos Ravnos escravos de seus vícios. Cada Ravnos tem uma queda por algum tipo de vício: mentir, crueldade ou roubo, por exemplo. Diante da oportunidade de se entregar a esse vício, o Ravnos deve ceder, a menos que seu jogador tenha sucesso num teste de Autocontrole ou Instintos (dificuldade 6).]==],
				},
				["Toreador"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 66


Toreador


Disciplinas: Auspícios, Rapidez, Presença

Fraqueza: Quando um Toreador vivencia algo verdadeiramente notável (uma pessoa, um objeto de arte, um belo nascer do sol), o jogador deve fazer um teste de Autocontrole ou Instintos (dificuldade 6). Falha significa que o Membro fica enfeitiçado pela experiência. O Toreador deslumbrado não pode agir durante a cena, exceto para comentar ou continuar envolvido com aquilo que capturou sua atenção. Se a experiência deixa de afetá-lo (por se mover, ser destruída ou o que for adequado à situação), o encantamento termina. Toreador extasiados podem nem mesmo se defender se atacados, embora ser ferido permita um novo teste de Autocontrole ou Instintos.]==],
				},
				["Tremere"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 68


Tremere


Disciplinas: Auspícios, Dominação, Taumaturgia

Fraqueza: A dependência de sangue dos Tremere é ainda mais pronunciada que a dos outros Membros. Bastam dois goles do sangue de outro vampiro para um Tremere ficar sob laço de sangue, em vez dos três normais: o primeiro gole conta como se o Tremere tivesse tomado dois. (Para mais informações sobre o laço de sangue, veja a p. 286.) Os anciões do Clã sabem disso muito bem e buscam incutir lealdade ao Clã obrigando todos os Feiticeiros neófitos a beber o sangue (transubstanciado) dos sete anciões Tremere logo após o Abraço.]==],
				},
				["Tzimisce"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 70


Tzimisce


Disciplinas: Animalismo, Auspícios, Vicissitude

Fraqueza: Os Tzimisce estão inextricavelmente ligados a seus domínios de origem e devem descansar próximos de pelo menos dois punhados de “terra natal”: terra de um lugar importante para ela quando mortal, como o solo de seu local de nascimento ou do cemitério onde recebeu o Abraço. Cada noite passada sem essa conexão física com sua terra limita todas as paradas de dados da Tzimisce à metade, cumulativamente, até que lhe reste um único dado. A penalidade permanece até que ela descanse um dia inteiro em meio à sua terra.]==],
				},
				["Ventrue"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 72


Ventrue


Disciplinas: Dominação, Fortitude, Presença

Fraqueza: Os Ventrue têm gostos refinados e só consideram palatável e vital um tipo específico de sangue mortal. Ao criar um personagem Ventrue, o jogador deve decidir com o Narrador que tipo de sangue serve ao personagem, e essa escolha é permanente. Sangue de outros tipos (até de animais) simplesmente não aumenta a reserva de sangue do vampiro, não importa quanto ele consuma: ele apenas o vomita de volta. Esse paladar refinado pode ser muito estreito ou muito amplo, digamos, o sangue de irmãs mais novas ou o sangue de crianças nuas. Sangue vampírico está isento dessa restrição.]==],
				},
				["Baali"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 394


Baali


Disciplinas: Daimonion, Ofuscação, Presença

Fraqueza: Os Baali não suportam olhar para objetos de qualquer fé nem manuseá-los. Os Demônios devem desviar o olhar de tais objetos, e tocá-los queima sua carne. Além disso, se um Baali se depara com Fé Verdadeira, quaisquer efeitos de impedimento ou dano são dobrados.]==],
				},
				["Blood Brothers"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 396


Blood Brothers


Disciplinas: Fortitude, Potência, Sanguinus

Fraqueza: Os Irmãos de Sangue não podem Abraçar. Se tentam, o mortal simplesmente morre. Além disso, os Frankensteins literalmente sentem a dor uns dos outros. Quando um Irmão de Sangue sofre uma penalidade de ferimento, todos os membros do círculo sofrem a mesma penalidade no turno seguinte. Se dois Irmãos de Sangue estão feridos, aplica-se apenas a maior penalidade. Os Irmãos de Sangue não sofrem essas penalidades continuamente, a menos que um deles sofra um novo ferimento.]==],
				},
				["Daughters of Cacophony"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 398


Daughters of Cacophony


Disciplinas: Fortitude, Melpominee, Presença

Fraqueza: As Filhas da Cacofonia ouvem música constantemente. Pode ser uma forma de sinestesia ou uma alucinação. Essa canção constante distrai as Filhas tanto quanto as guia. As dificuldades de todos os seus testes de Percepção aumentam em dois. Nenhuma Filha da Cacofonia pode ter Prontidão acima de 3 pontos.]==],
				},
				["Harbingers of Skulls"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 402


Harbingers of Skulls


Disciplinas: Auspícios, Fortitude, Necromancia

Fraqueza: Não importa quanto sangue uma Arauto consuma, sua pele permanece de uma palidez mortal. Além disso, todos os Arautos parecem cadáveres ressequidos. Têm Aparência 0 e falham automaticamente em testes de Aparência.]==],
				},
				["Kiasyd"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 404


Kiasyd


Disciplinas: Dominação, Mytherceria, Tenebrosidade

Fraqueza: Além da aparência um tanto bizarra, os Kiasyd também têm alergia a ferro. Tocar ferro exige um teste imediato para evitar o frenesi, e armas feitas de ferro frio causam dano agravado aos Kiasyd.]==],
				},
				["Nagaraja"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 406


Nagaraja


Disciplinas: Auspícios, Dominação, Necromancia

Fraqueza: Os Nagaraja precisam de carne crua além de sangue para sobreviver. A cada noite que um Nagaraja passa sem consumir carne, perde um dado cumulativo de todas as suas paradas de dados Físicas. Comer um ponto de carne devolve um dado a essas paradas até que o vampiro tenha “se recuperado”. Um corpo humano tem 10 “pontos de carne”, que funcionam exatamente como pontos de sangue: um Nagaraja que consome um ponto de carne aumenta sua reserva de sangue em um. Ao contrário dos pontos de sangue, porém, tirar um “ponto de carne” de um recipiente causa a ele um nível de vitalidade de dano letal não absorvível. A carne consumida pelos Nagaraja deve ser relativamente fresca, embora não necessariamente “viva”. De fato, alguns Nagaraja mantêm estoques de cadáveres ritualmente preservados em seus refúgios. Essa fraqueza não lhes permite comer alimentos nem consumir outros líquidos.]==],
				},
				["Salubri"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 408


Salubri


Disciplinas: Auspícios, Fortitude, Obeah

Fraqueza: Os Salubri têm dificuldade em se alimentar de recipientes que não consentem. Se um Ciclope tenta fazê-lo, perde um ponto de Força de Vontade.]==],
				},
				["Samedi"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 410


Samedi


Disciplinas: Fortitude, Ofuscação, Tanatose

Fraqueza: Os Samedi, como dito, são pútridos além das palavras. Personagens Samedi têm Aparência 0 e falham automaticamente em testes de Aparência.]==],
				},
				["True Brujah"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 412


True Brujah


Disciplinas: Potência, Presença, Temporis

Fraqueza: Os Brujah Verdadeiros perdem grande parte de sua capacidade emocional ao serem Abraçados, e sua capacidade de empatia continua a se deteriorar à medida que envelhecem. Todos os testes de Consciência e Convicção são feitos com dificuldade +2 (máximo 10), e os valores de Consciência, Convicção, Humanidade e Trilhas de Iluminação custam o dobro dos pontos de experiência normais.]==],
				},
				["Ahrimanes"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 414


Ahrimanes


Disciplinas: Animalismo, Presença, Spiritus

Fraqueza: O sangue de uma Ahrimane era inerte. Elas eram incapazes de criar crias ou laços de sangue, e uma pessoa que consumisse sangue Ahrimane não se tornava carniçal.]==],
				},
				["Anda"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 416


Anda


Disciplinas: Animalismo, Fortitude, Metamorfose

Fraqueza: Como os Gangrel de que descendiam, os Anda ganhavam traços animais ao entrar em frenesi. Ao contrário dos Gangrel, porém, os Anda ganhavam esse traço a cada dois frenesis. No entanto, os Anda sofriam uma fraqueza adicional: a cada dia, após o terceiro, que um Anda dormisse na mesma área de uma milha, todas as paradas de dados eram reduzidas à metade (até um mínimo de um dado).]==],
				},
				["Cappadocians"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 418


Cappadocians


Disciplinas: Auspícios, Fortitude, Necromancia

Fraqueza: Como mencionado, os Capadócios exibiam uma palidez mortal, e isso só piorava conforme o vampiro envelhecia. Capadócios jovens conseguiam passar por humanos (embora mortais que soubessem o que procurar os identificassem com facilidade), mas os anciões Capadócios mostravam pele ressequida e um semblante muito mais murcho.]==],
				},
				["Lamia"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 422


Lamia


Disciplinas: Fortitude, Necromancia, Potência

Fraqueza: As Lamia carregavam a “Semente de Lilith”, uma doença debilitante transmitida por sua mordida. Qualquer um de quem a Lamia se alimentasse precisava fazer um teste de Vigor (dificuldade 6 para mulheres, 8 para homens). Se o teste falhasse, a vítima contraía uma peste semelhante à Peste Negra, fatal em poucos dias. Qualquer vampiro que consumisse sangue Lamia tornava-se portador da doença até que toda a vitae Lamia fosse purgada de seu corpo.]==],
				},
				["Lhiannan"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 424


Lhiannan


Disciplinas: Animalismo, Ogham, Presença

Fraqueza: As Lhiannan eram em parte espíritos da natureza, e a marca de sua desumanidade era forte nelas. Todas as dificuldades para detectar sua natureza via Auspícios eram reduzidas em dois, e até humanos comuns sentiam-se vagamente desconfortáveis em sua presença. Além disso, qualquer Lhiannan que deixasse seu território ficava agitada: todas as paradas de dados eram reduzidas em um dado por semana de ausência (até um mínimo igual ao Vigor da personagem). Ao reentrar em seu território, suas paradas de dados voltavam ao normal em poucas horas.]==],
				},
				["Noiad"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 426


Noiad


Disciplinas: Animalismo, Auspícios, Metamorfose

Fraqueza: Os Noiad estavam tão intrinsecamente ligados aos Samí e ao seu papel de protetores divinos da tribo que uma das lendas sobre eles se tornou verdade. Dizia-se que os protetores dos Samí não podiam beber de animais, mas só se sustentar com o sangue dos escolhidos (isto é, os Samí). Os Noiad, de fato, não podiam beber de animais, embora pudessem beber de qualquer mortal ou Cainita, independentemente de nacionalidade ou etnia.]==],
				},
				["Assamite Antitribu"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 428


Assamite Antitribu


Disciplinas: Rapidez, Ofuscação, Quietus

Fraqueza: Os Assamitas antitribu têm a fraqueza anterior à maldição, mencionada no quadro da página anterior. Na verdade, sua fraqueza nunca mudou, enquanto o resto do Clã foi acorrentado pela maldição de sangue dos Tremere. Sempre que um Assamita antitribu bebe sangue de vampiro, o jogador deve testar Autocontrole ou Instintos (dificuldade 3 + o número de pontos de sangue consumidos). Se o teste falha, o personagem fica viciado. Uma vez viciado, o personagem se entrega a beber sangue de Membros sempre que possível. Quando tem a oportunidade de fazê-lo, o jogador deve testar Autocontrole ou Instintos (dificuldade 6). Se o teste falha, o personagem entra em frenesi, ataca o alvo e bebe todo o sangue que consegue.]==],
				},
				["Brujah Antitribu"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 429


Brujah Antitribu


Disciplinas: Rapidez, Potência, Presença

Fraqueza: A linhagem tem a mesma fraqueza que o corpo principal do Clã (p. 51): todas as dificuldades de frenesi aumentam em dois, até o máximo de 10. Ao contrário dos Brujah da Camarilla, porém, os Brutos não são nem um pouco sensíveis quanto ao seu temperamento. Na verdade, deleitam-se com sua fúria.]==],
				},
				["City Gangrel"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 429


City Gangrel


Disciplinas: Rapidez, Ofuscação, Metamorfose

Fraqueza: Os Gangrel Urbanos sofrem a mesma fraqueza que a linha principal do Clã (p. 55). Sempre que um Gangrel Urbano entra em frenesi, ganha um traço animalesco temporário de algum tipo (que pode substituir um temporário já existente). O impacto mecânico desse traço fica a critério do Narrador. Os Gangrel Urbanos tendem a desenvolver traços que lembram animais comuns em ambientes urbanos: ratos, cães, gatos, pombos e até insetos.]==],
				},
				["Country Gangrel"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 430


Country Gangrel


Disciplinas: Animalismo, Fortitude, Metamorfose

Fraqueza: Os Caçadores têm a mesma fraqueza que seus equivalentes fora do Sabá (p. 55). Cada vez que um Gangrel Rural entra em frenesi, ganha um traço animalesco temporário, que pode substituir um temporário já existente. O impacto mecânico desse traço fica a critério do Narrador.]==],
				},
				["Malkavian Antitribu"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 430


Malkavian Antitribu


Disciplinas: Auspícios, Demência, Ofuscação

Fraqueza: Como todos os Malkavianos (p. 61), os Aberrações são completamente insanos. Na criação do personagem, o jogador deve escolher uma Perturbação que o personagem nunca poderá superar.]==],
				},
				["Nosferatu Antitribu"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 430


Nosferatu Antitribu


Disciplinas: Animalismo, Ofuscação, Potência

Fraqueza: Os Nosferatu do Sabá são tão hediondos quanto seus equivalentes da Camarilla e sofrem a mesma fraqueza (p. 63): todos têm Aparência zero e nunca podem melhorá-la.]==],
				},
				["Ravnos Antitribu"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 431


Ravnos Antitribu


Disciplinas: Animalismo, Quimerismo, Fortitude

Fraqueza: Cada Ravnos antitribu, assim como seu Clã de origem (p. 65), tem uma queda por algum tipo de vício: quebrar tabus está gravado nos Trapaceiros tanto quanto nos Ravnos propriamente ditos. Diante da oportunidade de se entregar a esse vício, o Trapaceiro deve ceder, a menos que seu jogador tenha sucesso num teste de Autocontrole ou Instintos (dificuldade 6).]==],
				},
				["Salubri Antitribu"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 431


Salubri Antitribu


Disciplinas: Auspícios, Fortitude, Valeren

Fraqueza: Ao contrário de seus irmãos pacíficos, os Salubri do Sabá devem consumir sangue tomado à força, de preferência no calor da batalha. A menos que o vampiro se alimente do sangue de um inimigo caído ou lute com o alvo antes de se alimentar, a Vitae não o nutre. Além disso, os Salubri antitribu não podem começar abaixo da Décima Geração nem acima da Décima Segunda, pois seu sangue ainda não se espalhou por um espectro mais amplo.]==],
				},
				["Serpents of the Light"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 432


Serpents of the Light


Disciplinas: Presença, Ofuscação, Serpentis

Fraqueza: As Serpentes da Luz, apesar do nome, são tão vulneráveis à iluminação intensa quanto seu Clã de origem (p. 53). Sofrem dois níveis de vitalidade adicionais de dano da luz do sol e uma penalidade de um dado em todos os testes quando sujeitas a luz forte de qualquer tipo.]==],
				},
				["Toreador Antitribu"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 432


Toreador Antitribu


Disciplinas: Auspícios, Rapidez, Presença

Fraqueza: Com o tempo, a propensão dos Toreador a se fascinar pela beleza distorceu-se numa necessidade perversa de crueldade. Diante de uma oportunidade de infligir dor emocional ou física (um cativo que possa ser torturado ou um protegido cujas ambições possam ser esmagadas), o jogador do Toreador antitribu deve fazer um teste de Autocontrole ou Instintos (dificuldade 6) ou gastar um ponto de Força de Vontade. Se o teste falha, o personagem deve se entregar aos seus desejos selvagens.]==],
				},
				["Tremere Antitribu"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 432


Tremere Antitribu


Disciplinas: Auspícios, Dominação, Taumaturgia

Fraqueza: Os Tremere antitribu eram todos imediatamente reconhecíveis como traidores pelos Feiticeiros da Camarilla. A marca não era uma desfiguração física, mas uma mudança na própria presença do personagem. Não era uma fraqueza com desvantagem mecânica imediata, mas, uma vez identificado, o Tremere antitribu podia esperar ser caçado e queimado assim que os Tremere conseguissem. Também continuavam suscetíveis ao poder do sangue, recebendo +1 em todos os testes de Vinculum. Além disso, os Tremere antitribu eram proibidos de assumir cargos de liderança no Sabá.]==],
				},
				["Assamite Sorcerers"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 433


Assamite Sorcerers


Disciplinas: Feitiçaria Assamita, Ofuscação, Quietus

Fraqueza: A linhagem como um todo pratica a arte há tanto tempo que ela permeia seu sangue, fazendo cada feiticeiro se destacar como um farol para qualquer um com percepção sobrenatural. Qualquer uso de um poder sobrenatural sobre um feiticeiro com o propósito de percepção tem dificuldade -2. Além disso, tentativas de penetrar a ocultação sobrenatural de um feiticeiro com um poder oposto são consideradas um nível acima do normal (assim, um personagem com Auspícios 2 tentando penetrar a Ofuscação de um feiticeiro tem Auspícios efetivo 3).]==],
				},
				["Assamite Viziers"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 434


Assamite Viziers


Disciplinas: Auspícios, Rapidez, Quietus

Fraqueza: Os vizires são loucos. Cada vizir se vê preso à continuidade de suas atividades escolhidas, excluindo preocupações triviais como abrigo diário ou alimento noturno. Cada vizir tem uma Perturbação Obsessivo-Compulsiva (p. 292) associada à sua Habilidade intelectual ou criativa mais alta. Se o foco de esforço do personagem muda, o foco da Perturbação muda junto.]==],
				},
				["Daitya"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 434


Daitya


Disciplinas: Presença, Ofuscação, Serpentis

Fraqueza: Os Daitya sofrem a mesma fraqueza que os Seguidores de Set (p. 53): sofrem dois níveis de vitalidade adicionais de dano da luz do sol e uma penalidade de um dado em todos os testes quando sujeitos a luz forte de qualquer tipo.]==],
				},
				["Tlacique"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 435


Tlacique


Disciplinas: Ofuscação, Presença, Metamorfose

Fraqueza: A fraqueza dos Tlacique é uma das únicas maneiras de traçar a linhagem até os Setitas. Eles, como os Seguidores de Set (p. 53), sofrem dois níveis de vitalidade adicionais de dano da luz do sol e uma penalidade de um dado em todos os testes quando sujeitos a luz forte de qualquer tipo.]==],
				},
				["Warrior Setites"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 435


Warrior Setites


Disciplinas: Potência, Presença, Serpentis

Fraqueza: Os guerreiros sofrem a mesma fraqueza que os Seguidores de Set (p. 53): sofrem dois níveis de vitalidade adicionais de dano da luz do sol e uma penalidade de um dado em todos os testes quando sujeitos a luz forte de qualquer tipo.]==],
				},
				["Gangrel (Marine)"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 435


Gangrel (Marine)


Disciplinas: Animalismo, Fortitude, Metamorfose

Fraqueza: Como a maioria dos Gangrel (p. 55), os Marinheiros ganham um traço animalesco cada vez que entram em frenesi. Esses traços, porém, lembram peixes, vermes aquáticos, cefalópodes e outras criaturas marinhas (o raro Gangrel desenvolve um traço de cetáceo ou de foca). A natureza alienígena desses traços deve ser levada em conta pelos Narradores ao determinar seu impacto mecânico.]==],
				},
				["Lasombra Antitribu"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 436


Lasombra Antitribu


Disciplinas: Dominação, Tenebrosidade, Potência

Fraqueza: Além do problema habitual do Clã com reflexos (p. 59), os Lasombra antitribu também têm a “fraqueza” de serem caçados implacavelmente pelo Sabá e marcados para destruição sempre que sua existência se torna pública.]==],
				},
				["Dominate Malkavians"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 436


Dominate Malkavians


Disciplinas: Auspícios, Dominação, Ofuscação

Fraqueza: Como todos os Malkavianos (p. 61), os Portadores são irremediavelmente insanos. Em regra, sua insanidade tende a ser mais “silenciosa” que a do Lunático médio, mas os Malkavianos de Dominação ainda têm pelo menos uma Perturbação que não pode ser curada.]==],
				},
				["Brahman"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 437


Brahman


Disciplinas: Animalismo, Auspícios, Quimerismo

Fraqueza: Os Brahman sofrem a mesma fraqueza que o corpo principal do Clã Ravnos (p. 65). Cada um tem uma forma preferida de vício (embora os Brahman tenham um gosto especial por trapacear com leituras psíquicas e sessões espíritas). Sempre que o Brahman tem a chance de se entregar ao seu vício favorito, o jogador deve testar Autocontrole ou Instintos (dificuldade 6) para resistir à tentação.]==],
				},
				["Telyavelic Tremere"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 438


Telyavelic Tremere


Disciplinas: Auspícios, Presença, Taumaturgia

Fraqueza: Os Telyavs ataram seus destinos tão firmemente aos seus rebanhos pagãos que assumiram alguns dos mesmos medos e inimigos. São fracos contra símbolos e fé cristãos. As dificuldades para resistir ao frenesi são duas acima do normal quando confrontados por um inimigo que usa Fé Verdadeira como defesa. Recuam diante da cruz ou de outros símbolos da fé cristã.]==],
				},
				["Old Clan Tzimisce"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 439


Old Clan Tzimisce


Disciplinas: Animalismo, Auspícios, Dominação

Fraqueza: Como o resto do Clã (p. 71), os do Antigo Clã Tzimisce devem dormir sobre pelo menos dois punhados de terra de sua terra natal. Não cumprir essa exigência reduz à metade as paradas de dados do Tzimisce a cada 24 horas, até que todas caiam a um dado. A penalidade permanece até que consigam descansar um dia inteiro em sua terra.]==],
				},
				["Gargoyles (Modern)"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 400


Gargoyles (Modern)


Disciplinas: Voo, Fortitude, Potência, Visceratika

Fraqueza: Os Escravos são hediondos. Essa grotesquice assume formas diferentes, mas sempre resulta em Aparência zero. Também são altamente suscetíveis a controle mental de qualquer fonte. A Força de Vontade de um Gárgula (atual ou permanente) é considerada dois pontos mais baixa ao resistir a esses poderes.]==],
				},
				["Gargoyles (Scout)"] = {
					pt = [==[Lore of the Bloodlines, pág. 36


Gargoyles (Scout)


Disciplinas: Auspícios, Ofuscação, Voo

Fraqueza: Todas as penalidades de Vitalidade por ferimentos dobram, pois o corpo danificado do Gárgula volta a virar pedra. Essas penalidades só desaparecem quando o Gárgula desperta numa noite sem nenhum quadrado de vitalidade marcado.]==],
				},
				["Gargoyles (Sentinel)"] = {
					pt = [==[Lore of the Bloodlines, pág. 36


Gargoyles (Sentinel)


Disciplinas: Voo, Potência, Fortitude

Fraqueza: Se um Gárgula Sentinela se vê verdadeiramente só, sem alguém a quem chamar de mestre, parceiro, aliado ou amigo, todas as paradas de dados são reduzidas à metade até que o Gárgula encontre alguém em quem confiar e a quem servir no mundo.]==],
				},
				["Gargoyles (Warrior)"] = {
					pt = [==[Lore of the Bloodlines, pág. 36


Gargoyles (Warrior)


Disciplinas: Voo, Fortitude, Metamorfose

Fraqueza: Sempre que um Gárgula Guerreiro entra em frenesi, uma parte de seu corpo vira pedra. Escolha uma parte do corpo e um Atributo que a reflita (como olhos para Percepção ou pernas para Destreza). Até o próximo nascer do sol, qualquer teste que exija o atributo é considerado falha automática. Na noite seguinte, a parte do corpo volta ao normal.]==],
				},
				["Ventrue Antitribu"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 433


Ventrue Antitribu


Disciplinas: Dominação, Fortitude, mais Auspícios ou Presença

Fraqueza: Os Ventrue do Sabá têm a mesma fraqueza que seus irmãos da Camarilla (veja p. 73). O jogador decide com o Narrador que tipo específico de sangue serve ao Cruzado, e essa escolha é permanente. Sangue de outros tipos (até de animais) simplesmente não aumenta a reserva de sangue do vampiro, não importa quanto ele consuma.]==],
				},
				["Salubri (Wu Zao / Watchers)"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 438


Salubri (Wu Zao / Watchers)


Disciplinas: Auspícios, Fortitude, mais Obeah ou Valeren (escolhida na criação)

Fraqueza: Os Wu Zao são eruditos por natureza, e cada um tem um foco especial. Na criação do personagem, o jogador deve escolher uma área de estudo arcano: os Wan Kuei, a cultura de um grupo mortal específico, um conjunto de tomos místicos perdidos etc. Sempre que surge a oportunidade de aprender algo sobre esse assunto, o jogador deve fazer um teste de Força de Vontade (dificuldade 6) para não seguir essa pista, deixando tudo o mais de lado.]==],
				},
				["Angellis Ater"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 436


Angellis Ater


Disciplinas: Daimoinon, Dominação, mais uma entre Potência, Presença ou Ofuscação

Fraqueza: Os Angellis Ater têm a mesma fraqueza que os outros Lasombra (p. 59): não têm reflexo.]==],
				},
				["Maeghar"] = {
					pt = [==[The Black Hand: A Guide to the Tal’Mahe’Ra, pág. 167


Maeghar


Disciplinas: Mytherceria ou Necromancia (escolhida na criação), mais duas do Clã do senhor

Fraqueza: Por causa de seu físico marcado pelos fae, testes para reconhecer a Maeghar como sobrenatural têm dificuldade -1. Em segundo lugar, sua herança fae a torna vulnerável ao ferro frio: armas de ferro frio não só causam dano agravado, como esse dano provoca um teste imediato para evitar o frenesi ou o Rötschreck, conforme o contexto. Por fim, uma Maeghar sente tamanha repulsa em se alimentar de um humano quente, fedorento e suado que precisa drenar o sangue da vítima num recipiente limpo antes de consumi-lo. Essa restrição não se aplica ao se alimentar de vampiros.]==],
				},
				["Panders"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 431


Panders


Disciplinas: Sem Disciplinas de Clã: três quaisquer, escolhidas na criação com aprovação do Narrador

Fraqueza: Os Panders não têm uma fraqueza específica. Personagens Pander não podem começar abaixo da Nona Geração, embora possam depois reduzir sua Geração por diablerie.]==],
				},
				["Caitiff"] = {
					pt = [==[Anarchs Unbound, pág. 39


Caitiff


Disciplinas: Sem Disciplinas de Clã: três quaisquer, escolhidas na criação; aumentar qualquer Disciplina custa o valor atual x 6

Fraqueza: Os Caitiff não têm Disciplinas de Clã, assim como não têm Clã. Para eles, o custo de aumentar qualquer Disciplina é o valor atual x 6. Essa é ao mesmo tempo a maldição e a bênção de ser Sem-Clã.]==],
				},
				["Children of Osiris"] = {
					pt = [==[Vampire: The Masquerade 20th Anniversary Edition, pág. 420


Children of Osiris


Disciplinas: Conforme o Clã original do personagem; Bardo também conta como Disciplina de Clã

Fraqueza: Conforme apropriado ao Clã original do personagem.]==],
				},
				-- <<< CLAN_DESC_END
};
