-- Clan traits, the en half (SPEC I21, I148d, V432, V210, V24 / T971).
--
-- One entry per item of PICKER_LIST["clan"], keyed by the value the sheet SAVES, byte for
-- byte (SPEC V24). Block 3 is MECHANICS and nothing else - the Disciplines and the Weakness -
-- because that is what the owner asked the ? to say (SPEC I148d). The trio is read off CLANS
-- on the root form; the weakness sentence comes off FAMILY_WEAKNESS (family, root form) or
-- research/clan_weakness.tsv (clan, T970): the module is DERIVED from them and V432 reads it
-- back against them, so a drift shows up as a red gate and not as a pane that disagrees
-- with the slots (SPEC V135).
--
-- Three blocks separated by two blank lines (SPEC I21): source, name, body. The book title
-- does not translate and neither does the name in block 2 - it is the key; only p./pag. does.
--
-- Data only: no function, no state, no require of gui/ndb/locale (SPEC I24).
-- GENERATED by research/gen_traits_desc.ps1. Do not hand-edit: fix the table or the .tsv
-- it reads and run it again.

return {
				-- >>> CLAN_DESC_BEGIN (generated - SPEC T971)
				["Assamite"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 48


Assamite


Disciplines: Celerity, Obfuscate, Quietus

Weakness: Due to the Tremere blood-curse, should an Assamite consume the blood of another Kindred, she suffers one automatic level of unsoakable lethal damage per blood point imbibed. Diablerie attempts result in automatic aggravated damage, one health level per point of permanent Willpower the victim possesses; the would-be diablerist gains no benefits (including Generation reduction) if he survives the process. In addition, Assamites must tithe some of the profits from their contracts to their sires or superiors (generally around 10 percent of all such earnings).]==],
				},
				["Brujah"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 50


Brujah


Disciplines: Celerity, Potence, Presence

Weakness: The same passions that inspire Brujah to greatness or depravity, left unchecked, can send them into incandescent rages: The difficulties of rolls to resist or guide frenzy (p. 298) are two higher than normal. Additionally, a Brujah may never spend Willpower to avoid frenzy, though he may spend a point of Willpower to end a frenzy that has already begun.]==],
				},
				["Followers of Set"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 52


Followers of Set


Disciplines: Obfuscate, Presence, Serpentis

Weakness: Given their origins in darkness, the Serpents react negatively to bright light: Add two health levels to damage caused by exposure to sunlight. Setites also lose one die from dice pools for actions taken in bright light (police spotlights, stage lights, flares, etc.).]==],
				},
				["Gangrel"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 54


Gangrel


Disciplines: Animalism, Fortitude, Protean

Weakness: Every time a Gangrel frenzies, she acquires a temporary animal characteristic (which may replace an existing temporary one). A patch of fur, a brief torpor after feeding, or skittishness around crowds — all of these may mar an Outlander after frenzy. Characteristics acquired in Gangrel frenzies need not only be physical – they can be behavioral as well. Players should work with the Storyteller to determine what new animal trait is acquired (whether the frenzy involved the fight-or-flight impulse may be relevant). Over time, or in an exceptional situation, a particular animal feature may become permanent, with the next frenzy adding a new feature. A good guideline is to require each frenzy-gained trait to have some effect grounded in system terms (such as the temporary reduction of Social Attribute dots or a permanent loss of Humanity), though some Storytellers may allow narrative-only traits that can shape the story.]==],
				},
				["Giovanni"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 56


Giovanni


Disciplines: Dominate, Necromancy, Potence

Weakness: The Kiss of a Giovanni vampire causes excruciating pain in mortal vessels who receive it. If the Giovanni isn’t careful, her vessel may die of shock and agony before being wholly exsanguinated. When a Giovanni feeds upon a mortal, she does twice as much damage as the Kiss of another vampire would inflict. For example, if a Giovanni takes one point of blood from a mortal vessel, that victim would suffer two health levels of damage. As a result, they tend to use blood banks and other means of feeding that don’t fight as much.]==],
				},
				["Lasombra"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 58


Lasombra


Disciplines: Dominate, Obtenebration, Potence

Weakness: Lasombra vampires cast no reflections. Whether in a mirror, in a body of water, on a polished surface, or in the rear-view of a taxicab, the image of the Keeper does not reflect.]==],
				},
				["Malkavian"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 60


Malkavian


Disciplines: Auspex, Dementation, Obfuscate

Weakness: All members of Clan Malkavian suffer from a permanent, incurable derangement. They may acquire and recover from other derangements, and may spend Willpower to ameliorate the effects of the derangement for a scene, but they can never recover from their original derangement.]==],
				},
				["Nosferatu"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 62


Nosferatu


Disciplines: Animalism, Obfuscate, Potence

Weakness: All Nosferatu have an Appearance score of zero, and they may never improve it. Cross it off the character sheet. Dice pools that use the Appearance Trait are inherently difficult for these hideous Kindred.]==],
				},
				["Ravnos"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 64


Ravnos


Disciplines: Animalism, Chimerstry, Fortitude

Weakness: A turbulent history makes the Ravnos slaves to their vices. Each Ravnos has a penchant for some sort of vice — lying, cruelty, or theft, for example. When presented with the opportunity to engage in that vice, the Ravnos must indulge it unless her player succeeds on a Self-Control or Instincts roll (difficulty 6).]==],
				},
				["Toreador"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 66


Toreador


Disciplines: Auspex, Celerity, Presence

Weakness: When a Toreador experiences something truly remarkable — a person, an objet d’art, a lovely sunrise — the player must make a Self-Control or Instincts roll (difficulty 6). Failure means that the Kindred finds herself enthralled by the experience. The dazzled Toreador cannot act for the duration of the scene aside from commenting on or continuing their involvement with whatever has captured their attention. If the experience no longer affects her (whether by moving, being destroyed, or whatever is appropriate to the situation), the captivation ends. Enraptured Toreador may not even defend themselves if attacked, though being wounded allows them to make another Self-Control or Instincts roll.]==],
				},
				["Tremere"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 68


Tremere


Disciplines: Auspex, Dominate, Thaumaturgy

Weakness: Tremere dependency on blood is even more pronounced than that of other Kindred. It takes only two draughts of another vampire’s blood for a Tremere to become blood bound instead of the normal three — the first drink counts as if the Tremere had taken two drinks. (For more information on the blood bond, see p. 286). The elders of the Clan are well aware of this, and seek to impart loyalty to the Clan by forcing all neonate Warlocks to drink of the (transubstantiated) blood of the seven Tremere elders soon after their Embrace.]==],
				},
				["Tzimisce"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 70


Tzimisce


Disciplines: Animalism, Auspex, Vicissitude

Weakness: The Tzimisce are inextricably tied to their domains of origin, and must rest in the proximity of at least two handfuls of “native soil” — earth from a place important to her as a mortal, such as the soil from her birthplace or the graveyard where she underwent her Embrace. Each night spent without this physical connection to her land limits all of the Tzimisce’s dice pools to one-half, cumulatively, until she has only a single die in her pool. The penalty remains until she rests for a full day amid her earth once more.]==],
				},
				["Ventrue"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 72


Ventrue


Disciplines: Dominate, Fortitude, Presence

Weakness: The Ventrue have rarified tastes, and they find only one specific type of mortal blood palatable and vital for them. When a player creates a Ventrue character, he should decide with the Storyteller what specific type of blood suits the character, and this choice is permanent. Blood of other types (even animals) simply offers the vampire no blood pool increase, no matter how much he consumes — he simply vomits it back up. This refined palate may be very narrow or very broad — say, the blood of younger sisters, or the blood of nude children. Vampiric blood is exempt from this restriction.]==],
				},
				["Baali"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 394


Baali


Disciplines: Daimonion, Obfuscate, Presence

Weakness: Baali cannot bear to look upon or handle objects of any faith. Demons must avert their gazes from such objects, and touching them burns their flesh. In addition, should a Baali run afoul of True Faith, any hindering or damage effects are doubled.]==],
				},
				["Blood Brothers"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 396


Blood Brothers


Disciplines: Fortitude, Potence, Sanguinus

Weakness: Blood Brothers cannot Embrace. If they attempt it, the mortal simply dies. In addition, the Frankensteins literally feel each other’s pain. When a Blood Brother suffers a wound penalty, all members of the circle suffer the same penalty for the next turn. If two Blood Brothers are wounded, only the greater wound penalty applies. Blood Brothers do not continually suffer these penalties unless one of them suffers a new wound.]==],
				},
				["Daughters of Cacophony"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 398


Daughters of Cacophony


Disciplines: Fortitude, Melpominee, Presence

Weakness: The Daughters of Cacophony hear music constantly. This might be a form of synesthesia, or it might be a hallucination. This constant song distracts the Daughters as much as it guides them. The difficulties of all their Perception rolls increase by two. No Daughter of Cacophony may have Alertness above 3 dots.]==],
				},
				["Harbingers of Skulls"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 402


Harbingers of Skulls


Disciplines: Auspex, Fortitude, Necromancy

Weakness: No matter how much blood a Harbinger consumes, her skin remains deathly pale. Moreover, all Harbingers look like shriveled corpses. They have Appearance ratings of 0 and automatically fail Appearance rolls.]==],
				},
				["Kiasyd"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 404


Kiasyd


Disciplines: Dominate, Mytherceria, Obtenebration

Weakness: Besides their somewhat freakish appearance, Kiasyd also have an allergy to iron. Touching iron requires an immediate roll to avoid frenzy, and any weapons made from cold iron inflict aggravated damage to Kiasyd.]==],
				},
				["Nagaraja"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 406


Nagaraja


Disciplines: Auspex, Dominate, Necromancy

Weakness: The Nagaraja require raw flesh in addition to blood to survive. For every night a Nagaraja goes without consuming flesh, he loses one cumulative die from all his Physical dice pools. Eating one point worth of flesh restores one die to these pools until the vampire has “caught up.” A human body has 10 “flesh points,” which work just like blood points: A Nagaraja consuming one flesh point increases his blood pool by one. Unlike blood points, however, taking a “flesh point” from a vessel does one health level of unsoakable lethal damage to that vessel. The flesh the Nagaraja consume must be relatively fresh, though not necessarily “alive.” Indeed, some Nagaraja keep stores of ritually preserved corpses in their havens. This weakness does not allow them to eat food or consume other liquids.]==],
				},
				["Salubri"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 408


Salubri


Disciplines: Auspex, Fortitude, Obeah

Weakness: Salubri have difficulty feeding on unwilling vessels. If a Cyclops attempts it, she loses a point of Willpower.]==],
				},
				["Samedi"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 410


Samedi


Disciplines: Fortitude, Obfuscate, Thanatosis

Weakness: The Samedi, as mentioned, are putrid beyond words. Samedi characters have Appearance ratings of 0, and automatically fail Appearance rolls.]==],
				},
				["True Brujah"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 412


True Brujah


Disciplines: Potence, Presence, Temporis

Weakness: True Brujah lose much of their emotional capacity when they are Embraced, and their ability for sympathy continues to deteriorate as they grow older. All Conscience and Conviction rolls are made at +2 difficulty (maximum 10), and ratings in Conscience, Conviction, Humanity, and Paths of Enlightenment cost double the normal experience costs.]==],
				},
				["Ahrimanes"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 414


Ahrimanes


Disciplines: Animalism, Presence, Spiritus

Weakness: An Ahrimanes’ blood was inert. They were unable to create childer or blood bonds, and a person consuming Ahrimane blood did not become a ghoul.]==],
				},
				["Anda"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 416


Anda


Disciplines: Animalism, Fortitude, Protean

Weakness: Like the Gangrel from which they were descended, Anda gained animal features from frenzying. Unlike the Gangrel, though, Anda gained such a feature once every other frenzy. However, the Anda suffered a further weakness — for each day after the third that an Anda slept within the same one-mile area, all dice pools were halved (to a minimum pool of one).]==],
				},
				["Cappadocians"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 418


Cappadocians


Disciplines: Auspex, Fortitude, Necromancy

Weakness: As mentioned, the Cappadocians exhibited a deathly pallor, and this only worsened as the vampire grew older. Young Cappadocians were able to pass for human (though mortals that knew what to look for could pick them out easily), but elder Cappadocians showed shriveled skin and a much more withered countenance.]==],
				},
				["Lamia"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 422


Lamia


Disciplines: Fortitude, Necromancy, Potence

Weakness: The Lamia carried the “Seed of Lilith,” a wasting disease spread by their bite. Anyone the Lamia fed upon was required to make a Stamina roll (difficulty 6 for women, 8 for men). If the roll failed, the victim contracted a Black Plague-like pox that was fatal within several days. Any vampire that consumed Lamia blood became a carrier of the disease until all of the Lamia vitae had been purged from his body.]==],
				},
				["Lhiannan"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 424


Lhiannan


Disciplines: Animalism, Ogham, Presence

Weakness: The Lhiannan were part nature spirit, and the mark of their inhumanity ran strong within them. All difficulties to detect their nature via Auspex were reduced by two, and even normal humans felt vaguely uncomfortable in their presence. Additionally, any Lhiannan who left her territory became agitated — all dice pools were reduced by one die per week (to a minimum of the character’s Stamina) that she was gone. Once she re-entered her territory, her dice pools returned to normal within a few hours.]==],
				},
				["Noiad"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 426


Noiad


Disciplines: Animalism, Auspex, Protean

Weakness: The Noiad were so intrinsically tied to the Samí and to their role as the divine protectors of the tribe that one of the legends about them came true. The Samí’s protectors, it was said, could not sup from animals, but could only take sustenance from the blood of the chosen (that is, the Samí). The Noiad, in fact, could not drink from animals, though they were capable of drinking from any mortal or Cainite, regardless of nationality or ethnicity.]==],
				},
				["Assamite Antitribu"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 428


Assamite Antitribu


Disciplines: Celerity, Obfuscate, Quietus

Weakness: Assamite antitribu have the post-curse weakness mentioned in the sidebar on the previous page. In fact, their weakness never changed, while the rest of the Clan shackled with the blood curse of the Tremere. Whenever an Assamite antitribu drinks vampire blood, the player must roll Self-Control or Instincts (difficulty 3 + the number of blood points consumed). If this roll fails, the character is addicted. Once addicted, the character will indulge in drinking Kindred blood whenever possible. When she is given the opportunity to do so, the player must roll Self-Control or Instincts (difficulty 6). If this roll fails, the character frenzies, attacks the target and drinks as much blood as she can.]==],
				},
				["Brujah Antitribu"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 429


Brujah Antitribu


Disciplines: Celerity, Potence, Presence

Weakness: The bloodline has the same weakness as the main body of the Clan (p. 51): All frenzy difficulties are increased by two, to a maximum of 10. Unlike Camarilla Brujah, though, the Brutes aren’t in the least bit sensitive about their tempers. Indeed, they revel in their rage.]==],
				},
				["City Gangrel"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 429


City Gangrel


Disciplines: Celerity, Obfuscate, Protean

Weakness: City Gangrel suffer the same weakness as the main line of the Clan (p. 55). Whenever a City Gangrel frenzies, he gains a temporary animalistic feature of some kind (which may replace an existing temporary one). The mechanical impact of such a feature is up to Storyteller discretion. City Gangrel tend to develop features reminiscent of the animals commonly found in urban environments — rats, dogs, cats, pigeons, and even insects.]==],
				},
				["Country Gangrel"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 430


Country Gangrel


Disciplines: Animalism, Fortitude, Protean

Weakness: The Hunters have the same weakness as their non-Sabbat counterparts (p. 55). Each time a Country Gangrel frenzies, he gains a temporary animalistic feature, which may replace an existing temporary one. The mechanical impact of such a feature is up to Storyteller discretion.]==],
				},
				["Malkavian Antitribu"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 430


Malkavian Antitribu


Disciplines: Auspex, Dementation, Obfuscate

Weakness: Like all Malkavians (p. 61), the Freaks are completely insane. At character creation, the player must choose a derangement that the character can never overcome.]==],
				},
				["Nosferatu Antitribu"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 430


Nosferatu Antitribu


Disciplines: Animalism, Obfuscate, Potence

Weakness: Sabbat Nosferatu are just as hideous as their Camarilla counterparts, and suffer the same weakness (p. 63): they all have an Appearance score of zero, and they may never improve it.]==],
				},
				["Ravnos Antitribu"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 431


Ravnos Antitribu


Disciplines: Animalism, Chimerstry, Fortitude

Weakness: Each Ravnos antitribu, just like their parent Clan (p. 65), has a penchant for some sort of vice — breaking taboos is hard-wired into the Rogues just as it is into the Ravnos proper. When presented with the opportunity to engage in that vice, the Rogue must indulge it unless her player succeeds on a Self-Control or Instincts roll (difficulty 6).]==],
				},
				["Salubri Antitribu"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 431


Salubri Antitribu


Disciplines: Auspex, Fortitude, Valeren

Weakness: Unlike their nonviolent brethren, Sabbat Salubri must consume blood taken by force, preferably in the heat of battle. Unless the vampire feeds on blood from a fallen foe or fights his target before feeding, the Vitae offers no nourishment. In addition, Salubri antitribu cannot start lower than Tenth Generation or higher than Twelfth, as their blood has yet to spread across a wider spectrum than that.]==],
				},
				["Serpents of the Light"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 432


Serpents of the Light


Disciplines: Presence, Obfuscate, Serpentis

Weakness: The Serpents of the Light, despite the name, are just as vulnerable to bright illumination as their parent Clan (p. 53). They suffer two additional health levels of damage from sunlight, and a one-die penalty to all rolls when subject to bright light of any kind.]==],
				},
				["Toreador Antitribu"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 432


Toreador Antitribu


Disciplines: Auspex, Celerity, Presence

Weakness: Over time, the propensity for the Toreador to become fascinated by beauty has twisted itself into a perverse need for cruelty. When faced with an opportunity to inflict emotional or physical pain — a captive that might be tortured, or a protégé whose ambitions might be squashed — the Toreador antitribu’s player must make a Self-Control or Instinct roll (difficulty 6), or spend a Willpower point. If the roll fails, the character must indulge in her savage desires.]==],
				},
				["Tremere Antitribu"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 432


Tremere Antitribu


Disciplines: Auspex, Dominate, Thaumaturgy

Weakness: The Tremere antitribu were all immediately recognizable as traitors to Camarilla Warlocks. The mark wasn’t a physical disfigurement, but a change to the character’s very presence. This wasn’t a weakness that carries an immediate mechanical disadvantage, but once identified, the Tremere antitribu could expect to be hunted down and burned as soon as the Tremere can possibly manage it. They were also still susceptible to the power of the blood, gaining a +1 to all Vinculum rolls. In addition, Tremere antitribu were barred from taking leadership roles in the Sabbat.]==],
				},
				["Assamite Sorcerers"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 433


Assamite Sorcerers


Disciplines: Assamite Sorcery, Obfuscate, Quietus

Weakness: The line as a whole has practiced the art for so long that it permeates their blood, making each individual sorcerer stand out like a beacon to anyone with supernatural perception. Any use of a supernatural power on a sorcerer for purposes of perception enjoys a -2 difficulty. Additionally, attempts to penetrate a sorcerer’s supernatural concealment using an opposed power are considered to operate one level higher than normal (so a character with Auspex 2 trying to penetrate a sorcerer’s Obfuscate has an effective Auspex of 3).]==],
				},
				["Assamite Viziers"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 434


Assamite Viziers


Disciplines: Auspex, Celerity, Quietus

Weakness: The viziers are mad. Every vizier finds himself caught up in the continuance of his chosen pursuits to the exclusion of trivial concerns such as daily shelter or nightly nourishment. Each vizier has an Obsessive-Compulsive derangement (p. 292) associated with his highest-rated intellectual or creative Ability. If the character’s focus of effort shifts, so does the focus of the derangement.]==],
				},
				["Daitya"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 434


Daitya


Disciplines: Presence, Obfuscate, Serpentis

Weakness: The Daitya suffer the same weakness as the Followers of Set (p. 53): They suffer two additional health levels of damage from sunlight, and a one-die penalty to all rolls when subject to bright light of any kind.]==],
				},
				["Tlacique"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 435


Tlacique


Disciplines: Obfuscate, Presence, Protean

Weakness: The Tlacique’s weakness is one of the only ways to trace the line’s lineage to the Setites. They, like the Followers of Set (p. 53), suffer two additional health levels of damage from sunlight, and a one-die penalty to all rolls when subjected to bright light of any kind.]==],
				},
				["Warrior Setites"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 435


Warrior Setites


Disciplines: Potence, Presence, Serpentis

Weakness: The warriors suffer same weakness as the Followers of Set (p. 53): They suffer two additional health levels of damage from sunlight, and a one-die penalty to all rolls when subjected to bright light of any kind.]==],
				},
				["Gangrel (Marine)"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 435


Gangrel (Marine)


Disciplines: Animalism, Fortitude, Protean

Weakness: As with most Gangrel (p. 55), the Mariners gain an animalistic feature each time they frenzy. These features, though, resemble fish, aquatic worms, cephalopods, and other sea creatures (the rare Gangrel develops a cetacean or seal-like feature). The alien nature of these features should be taken into consideration by Storytellers determining the mechanical impact of such features.]==],
				},
				["Lasombra Antitribu"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 436


Lasombra Antitribu


Disciplines: Dominate, Obtenebration, Potence

Weakness: In addition to the Clan’s usual problem with reflections (p. 59), Lasombra antitribu also have the “weakness” of being hunted relentlessly by the Sabbat, and targeted for destruction whenever their existence is made public.]==],
				},
				["Dominate Malkavians"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 436


Dominate Malkavians


Disciplines: Auspex, Dominate, Obfuscate

Weakness: Like all Malkavians (p. 61), the Carriers are irretrievably insane. As a rule, their insanity tends to be “quieter” than the average Lunatic’s, but the Dominate Malkavians still have at least one derangement that cannot be cured.]==],
				},
				["Brahman"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 437


Brahman


Disciplines: Animalism, Auspex, Chimerstry

Weakness: The Brahman suffer the same weakness as the main body of Clan Ravnos (p. 65). Each one has a preferred form of vice (though the Brahman have a special love for swindling through psychic readings and séances). Whenever the Brahman is given the chance to indulge in his favorite vice, the player must roll SelfControl or Instinct (difficulty 6) to resist the temptation.]==],
				},
				["Telyavelic Tremere"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 438


Telyavelic Tremere


Disciplines: Auspex, Presence, Thaumaturgy

Weakness: The Telyavs bound their fates so tightly to their pagan herds that they took on some of the same fears and enemies. They are weak against Christian symbols and faith. Difficulties to resist frenzy are two higher than normal when confronted by an enemy using True Faith as a defense. They recoil from the sight of the cross or other symbols of the Christian faith.]==],
				},
				["Old Clan Tzimisce"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 439


Old Clan Tzimisce


Disciplines: Animalism, Auspex, Dominate

Weakness: As with the rest of the Clan (p. 71), the Old Clan Tzimisce must sleep in at least two handfuls of soil from their homeland. Failure to meet this requirement halves the Tzimisce’s dice pools every 24 hours, until all pools fall to one die. This penalty remains until they are able to rest for a full day in their earth.]==],
				},
				["Gargoyles (Modern)"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 400


Gargoyles (Modern)


Disciplines: Flight, Fortitude, Potence, Visceratika

Weakness: The Slaves are hideous. That grotesquery takes different forms, but always results in an Appearance of zero. They are also highly susceptible to mind control from any source. A Gargoyle’s Willpower score (current or permanent) is considered two points lower when used to resist such powers.]==],
				},
				["Gargoyles (Scout)"] = {
					en = [==[Lore of the Bloodlines, p. 36


Gargoyles (Scout)


Disciplines: Auspex, Obfuscate, Flight

Weakness: All Health penalties from injures double as the Gargoyle’s damaged body turns back to stone. These penalties only go away when the Gargoyle awakens in an evening with no health boxes crossed off.]==],
				},
				["Gargoyles (Sentinel)"] = {
					en = [==[Lore of the Bloodlines, p. 36


Gargoyles (Sentinel)


Disciplines: Flight, Potence, Fortitude

Weakness: If a Sentinel Gargoyle finds itself truly alone without someone to call master, mate, ally or friend, all dice pools are halved until the Gargoyle can find someone to trust and serve in the world.]==],
				},
				["Gargoyles (Warrior)"] = {
					en = [==[Lore of the Bloodlines, p. 36


Gargoyles (Warrior)


Disciplines: Flight, Fortitude, Protean

Weakness: Whenever a Warrior Gargoyle frenzies, a part of their body turns to stone. Choose a body part and an Attribute that reflects the part (such as eyes for Perception or legs for Dexterity). Until the next sunrise, any rolls requiring the attribute are considered an automatic failure. The next evening, the body part returns to normal.]==],
				},
				["Ventrue Antitribu"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 433


Ventrue Antitribu


Disciplines: Dominate, Fortitude, plus Auspex or Presence

Weakness: Sabbat Ventrue have the same weakness as their Camarilla brethren (see p. 73). The player decides with the Storyteller what specific type of blood suits the Crusader, and this choice is permanent. Blood of other types (even animals) simply offers the vampire no blood pool increase, no matter how much he consumes.]==],
				},
				["Salubri (Wu Zao / Watchers)"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 438


Salubri (Wu Zao / Watchers)


Disciplines: Auspex, Fortitude, plus Obeah or Valeren (chosen at creation)

Weakness: The Wu Zao are scholars by nature, and each of them has a special focus. At character creation, the player must select an area of arcane study — the Wan Kuei, the culture of a specific mortal group, a group of mystical tomes lost to the ages, etc. Whenever the opportunity arises to learn something about this subject, the player must make a Willpower roll (difficulty 6) to avoid pursuing that lead to the exclusion of all else.]==],
				},
				["Angellis Ater"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 436


Angellis Ater


Disciplines: Daimoinon, Dominate, plus one of Potence, Presence or Obfuscate

Weakness: The Angellis Ater have the same weakness as other Lasombra (p. 59) — they do not cast reflections.]==],
				},
				["Maeghar"] = {
					en = [==[The Black Hand: A Guide to the Tal’Mahe’Ra, p. 167


Maeghar


Disciplines: Mytherceria or Necromancy (chosen at creation), plus two from the sire's Clan

Weakness: Due to her fae-marked physique, rolls to recognize the Maeghar as otherworldly are at -1 difficulty. Secondly, her fae heritage makes her vulnerable to cold iron: not only do weapons made from cold iron inflict aggravated damage to her, but such damage triggers an immediate roll to avoid either frenzy or Rötschreck as befitting the context. Lastly, a Maeghar feels such revulsion at feeding from a warm, smelly, and sweaty human that she must drain her victim’s blood in a clean container before consuming it. This restriction does not apply when feeding from vampires.]==],
				},
				["Panders"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 431


Panders


Disciplines: No Clan Disciplines: any three, chosen at creation with Storyteller approval

Weakness: Panders do not have a specific weakness. Pander characters cannot start lower than Ninth Generation, though they can subsequently lower their Generation via diablerie.]==],
				},
				["Caitiff"] = {
					en = [==[Anarchs Unbound, p. 39


Caitiff


Disciplines: No Clan Disciplines: any three, chosen at creation; raising any Discipline costs the current rating x 6

Weakness: Caitiff have no Clan-based Disciplines, just as they have no Clan. For them, the cost of raising all Disciplines is the current rating x 6. This is both the curse and the blessing of being Clanless.]==],
				},
				["Children of Osiris"] = {
					en = [==[Vampire: The Masquerade 20th Anniversary Edition, p. 420


Children of Osiris


Disciplines: As appropriate for the character's original Clan; Bardo is also an in-Clan Discipline

Weakness: As appropriate for the character’s original Clan.]==],
				},
				-- <<< CLAN_DESC_END
};
